// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkAlgorithmOutput.h>
#include <vtkFitToHeightMapFilter.h>

VTKSHARP_API vtkFitToHeightMapFilter* vtkFitToHeightMapFilter_New() { return vtkFitToHeightMapFilter::New(); }

VTKSHARP_API void vtkFitToHeightMapFilter_SetFittingStrategyToCellAverageHeight(vtkFitToHeightMapFilter* self) { self->SetFittingStrategyToCellAverageHeight(); }

VTKSHARP_API void vtkFitToHeightMapFilter_SetFittingStrategyToPointProjection(vtkFitToHeightMapFilter* self) { self->SetFittingStrategyToPointProjection(); }

VTKSHARP_API void vtkFitToHeightMapFilter_SetHeightMapConnection(vtkFitToHeightMapFilter* self, vtkAlgorithmOutput* algOutput) { self->SetHeightMapConnection(algOutput); }

VTKSHARP_API void vtkFitToHeightMapFilter_UseHeightMapOffsetOn(vtkFitToHeightMapFilter* self) { self->UseHeightMapOffsetOn(); }
