// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Abstract render pass with shader modifications.
/// </summary>
/// <remarks>
/// Allows a render pass to update shader code using a new virtual API.
/// </remarks>
public unsafe partial class vtkOpenGLRenderPass : vtkRenderPass
{
    protected vtkOpenGLRenderPass(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkOpenGLRenderPass FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkOpenGLRenderPass TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkOpenGLRenderPass Register(vtkOpenGLRenderPass sourceObject)
    {
        var target = new vtkOpenGLRenderPass(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
