// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// OpenGL rendering window
/// </summary>
/// <remarks>
/// vtkOpenGLRenderWindow is a concrete implementation of the abstract class
/// vtkRenderWindow. vtkOpenGLRenderer interfaces to the OpenGL graphics
/// library. Application programmers should normally use vtkRenderWindow
/// instead of the OpenGL specific version.
/// </remarks>
public unsafe partial class vtkOpenGLRenderWindow : vtkRenderWindow
{
    protected vtkOpenGLRenderWindow(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkOpenGLRenderWindow New() => new(vtkOpenGLRenderWindow_New(), ownsReference: true);
    public new static vtkOpenGLRenderWindow FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkOpenGLRenderWindow TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkOpenGLRenderWindow Register(vtkOpenGLRenderWindow sourceObject)
    {
        var target = new vtkOpenGLRenderWindow(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Handle opengl specific code and calls superclass
    /// </summary>
    public new void Render()
    {
        vtkOpenGLRenderWindow_Render(this.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkOpenGLRenderWindow_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkOpenGLRenderWindow_Render(nint self);
    #endregion
}
