// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkValuePass : vtkOpenGLRenderPass
{
    protected vtkValuePass(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkValuePass New() => new(vtkValuePass_New(), ownsReference: true);
    public new static vtkValuePass FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkValuePass TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkValuePass Register(vtkValuePass sourceObject)
    {
        var target = new vtkValuePass(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new vtkFloatArray GetFloatImageDataArray(vtkRenderer ren)
    {
        return vtkFloatArray.FromBorrowedPointer(vtkValuePass_GetFloatImageDataArray(this.NativePointer, ren.NativePointer));
    }

    public new void ReleaseGraphicsResources(vtkWindow win)
    {
        vtkValuePass_ReleaseGraphicsResources(this.NativePointer, win.NativePointer);
    }

    public new void SetInputArrayToProcess(int fieldAssociation, string name)
    {
        #if NET8_0_OR_GREATER
        vtkValuePass_SetInputArrayToProcess_int_constCharPtr(this.NativePointer, fieldAssociation, name);
        #else
        vtkValuePass_SetInputArrayToProcess_int_constCharPtr(this.NativePointer, fieldAssociation, VtkString.ToNullTerminatedUtf8(name));
        #endif
    }

    public new void SetInputArrayToProcess(int fieldAssociation, int fieldId)
    {
        vtkValuePass_SetInputArrayToProcess_int_int(this.NativePointer, fieldAssociation, fieldId);
    }

    public new void SetInputComponentToProcess(int component)
    {
        vtkValuePass_SetInputComponentToProcess(this.NativePointer, component);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkValuePass_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkValuePass_GetFloatImageDataArray(nint self, nint ren);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkValuePass_ReleaseGraphicsResources(nint self, nint win);

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkValuePass_SetInputArrayToProcess_int_constCharPtr(nint self, int fieldAssociation, string name);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkValuePass_SetInputArrayToProcess_int_constCharPtr(nint self, int fieldAssociation, byte[] name);
#endif

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkValuePass_SetInputArrayToProcess_int_int(nint self, int fieldAssociation, int fieldId);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkValuePass_SetInputComponentToProcess(nint self, int component);
    #endregion
}
