// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkWin32OpenGLRenderWindow : vtkOpenGLRenderWindow
{
    protected vtkWin32OpenGLRenderWindow(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkWin32OpenGLRenderWindow New() => new(vtkWin32OpenGLRenderWindow_New(), ownsReference: true);
    public new static vtkWin32OpenGLRenderWindow WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkWin32OpenGLRenderWindow Register(vtkWin32OpenGLRenderWindow sourceObject)
    {
        var target = new vtkWin32OpenGLRenderWindow(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new nint GetWindowId()
    {
        return vtkWin32OpenGLRenderWindow_GetWindowId(this.NativePointer);
    }

    public new void SetParentId(nint _arg1)
    {
        vtkWin32OpenGLRenderWindow_SetParentId(this.NativePointer, _arg1);
    }

    public new void SetWindowName(string _arg1)
    {
        #if NET8_0_OR_GREATER
        vtkWin32OpenGLRenderWindow_SetWindowName(this.NativePointer, _arg1);
        #else
        vtkWin32OpenGLRenderWindow_SetWindowName(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg1));
        #endif
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkWin32OpenGLRenderWindow_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkWin32OpenGLRenderWindow_GetWindowId(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWin32OpenGLRenderWindow_SetParentId(nint self, nint _arg1);

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkWin32OpenGLRenderWindow_SetWindowName(nint self, string _arg1);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWin32OpenGLRenderWindow_SetWindowName(nint self, byte[] _arg1);
#endif
    #endregion
}
