// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkMeshQuality.h>

VTKSHARP_API vtkMeshQuality* vtkMeshQuality_New() { return vtkMeshQuality::New(); }

VTKSHARP_API void vtkMeshQuality_SetTriangleQualityMeasureToArea(vtkMeshQuality* self) { self->SetTriangleQualityMeasureToArea(); }
