// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkInteractorStyleRubberBandPick.h>

VTKSHARP_API vtkInteractorStyleRubberBandPick* vtkInteractorStyleRubberBandPick_New() { return vtkInteractorStyleRubberBandPick::New(); }
