// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkInteractorStyleSwitch.h>

VTKSHARP_API vtkInteractorStyleSwitch* vtkInteractorStyleSwitch_New() { return vtkInteractorStyleSwitch::New(); }
