// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkBorderRepresentation.h>
#include <vtkBorderWidget.h>

VTKSHARP_API vtkBorderWidget* vtkBorderWidget_New() { return vtkBorderWidget::New(); }

VTKSHARP_API void vtkBorderWidget_CreateDefaultRepresentation(vtkBorderWidget* self) { self->CreateDefaultRepresentation(); }

VTKSHARP_API vtkBorderRepresentation* vtkBorderWidget_GetBorderRepresentation(vtkBorderWidget* self) { return self->GetBorderRepresentation(); }

VTKSHARP_API vtkTypeBool vtkBorderWidget_GetResizable(vtkBorderWidget* self) { return self->GetResizable(); }

VTKSHARP_API vtkTypeBool vtkBorderWidget_GetSelectable(vtkBorderWidget* self) { return self->GetSelectable(); }

VTKSHARP_API void vtkBorderWidget_ResizableOff(vtkBorderWidget* self) { self->ResizableOff(); }

VTKSHARP_API void vtkBorderWidget_ResizableOn(vtkBorderWidget* self) { self->ResizableOn(); }

VTKSHARP_API void vtkBorderWidget_SelectableOff(vtkBorderWidget* self) { self->SelectableOff(); }

VTKSHARP_API void vtkBorderWidget_SelectableOn(vtkBorderWidget* self) { self->SelectableOn(); }

VTKSHARP_API void vtkBorderWidget_SetRepresentation(vtkBorderWidget* self, vtkBorderRepresentation* r) { self->SetRepresentation(r); }

VTKSHARP_API void vtkBorderWidget_SetResizable(vtkBorderWidget* self, vtkTypeBool _arg) { self->SetResizable(_arg); }

VTKSHARP_API void vtkBorderWidget_SetSelectable(vtkBorderWidget* self, vtkTypeBool _arg) { self->SetSelectable(_arg); }
