// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// extract a subset from a vtkDataSet.
/// </summary>
/// <remarks>
/// <para>
/// vtkExtractSelection extracts some subset of cells and points from
/// its input data object. The data object is given on its first input port.
/// The subset is described by the contents of the vtkSelection on its
/// second input port.  Depending on the contents of the vtkSelection
/// this will create various vtkSelectors to identify the
/// selected elements.
/// </para>
/// <para>
/// This filter supports vtkCompositeDataSet, vtkDataSet, vtkHyperTreeGrid and vtkTable.
/// </para>
/// <para>
/// 1. If preserve topology is on, the output type is the same as the input.
/// 2. If preserve topology is on.
/// 1. If input is a subclass of vtkDataObjectTree, the output is the same subclass.
/// 2. If input is vtkUniformGridAMR, the output is vtkPartitionedDataSetCollection.
/// 3. If input is vtkDataSet, the output is vtkUnstructuredGrid.
/// 4. If input is vtkHyperTreeGrid, the output is vtkHyperTreeGrid or vtkUnstructuredGrid
/// depending on the HyperTreeGridToUnstructuredGrid flag.
/// 5. If input is vtkTable, the output is vtkTable.
/// </para>
/// <para>
/// Other types of input are not processed and the corresponding output is a
/// default constructed object of the input type.
/// </para>
/// <para>
/// See also: vtkSelection vtkSelector vtkSelectionNode
/// </para>
/// </remarks>
public unsafe partial class vtkExtractSelection : vtkDataObjectAlgorithm
{
    static vtkExtractSelection() => NativeModuleLoader.EnsureLoaded("VtkSharp.Native.FiltersExtraction.dll");

    protected vtkExtractSelection(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkExtractSelection New() => new(vtkExtractSelection_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkExtractSelection FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkExtractSelection TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkExtractSelection Register(vtkExtractSelection sourceObject)
    {
        var target = new vtkExtractSelection(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport("VtkSharp.Native.FiltersExtraction.dll")]
    private static extern nint vtkExtractSelection_New();
    #endregion
}
