// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// filter used to convert a vtkTable to a vtkPolyData
/// consisting of vertices.
/// </summary>
/// <remarks>
/// vtkTableToPolyData is a filter used to convert a vtkTable  to a vtkPolyData
/// consisting of vertices.
/// </remarks>
public unsafe partial class vtkTableToPolyData : vtkPolyDataAlgorithm
{
    protected vtkTableToPolyData(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkTableToPolyData New() => new(vtkTableToPolyData_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkTableToPolyData FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkTableToPolyData TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkTableToPolyData Register(vtkTableToPolyData sourceObject)
    {
        var target = new vtkTableToPolyData(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Set the name of the column to use as the X coordinate for the points.
    /// </summary>
    public new void SetXColumn(string _arg)
    {
        #if NET8_0_OR_GREATER
        vtkTableToPolyData_SetXColumn(this.NativePointer, _arg);
        #else
        vtkTableToPolyData_SetXColumn(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg));
        #endif
    }

    /// <summary>
    /// Set the name of the column to use as the Y coordinate for the points.
    /// Default is 0.
    /// </summary>
    public new void SetYColumn(string _arg)
    {
        #if NET8_0_OR_GREATER
        vtkTableToPolyData_SetYColumn(this.NativePointer, _arg);
        #else
        vtkTableToPolyData_SetYColumn(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg));
        #endif
    }

    /// <summary>
    /// Set the name of the column to use as the Z coordinate for the points.
    /// Default is 0.
    /// </summary>
    public new void SetZColumn(string _arg)
    {
        #if NET8_0_OR_GREATER
        vtkTableToPolyData_SetZColumn(this.NativePointer, _arg);
        #else
        vtkTableToPolyData_SetZColumn(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg));
        #endif
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkTableToPolyData_New();

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkTableToPolyData_SetXColumn(nint self, string _arg);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTableToPolyData_SetXColumn(nint self, byte[] _arg);
#endif

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkTableToPolyData_SetYColumn(nint self, string _arg);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTableToPolyData_SetYColumn(nint self, byte[] _arg);
#endif

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkTableToPolyData_SetZColumn(nint self, string _arg);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTableToPolyData_SetZColumn(nint self, byte[] _arg);
#endif
    #endregion
}
