// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Make a vtkPolyData with a vertex on each point.
/// </summary>
/// <remarks>
/// This filter throws away all of the cells in the input and replaces them with
/// a vertex on each point.  The intended use of this filter is roughly
/// equivalent to the vtkGlyph3D filter, except this filter is specifically for
/// data that has many vertices, making the rendered result faster and less
/// cluttered than the glyph filter. This filter may take a graph or point set
/// as input.
/// </remarks>
public unsafe partial class vtkVertexGlyphFilter : vtkPolyDataAlgorithm
{
    protected vtkVertexGlyphFilter(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkVertexGlyphFilter New() => new(vtkVertexGlyphFilter_New(), ownsReference: true);
    public new static vtkVertexGlyphFilter FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkVertexGlyphFilter TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkVertexGlyphFilter Register(vtkVertexGlyphFilter sourceObject)
    {
        var target = new vtkVertexGlyphFilter(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkVertexGlyphFilter_New();
    #endregion
}
