// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkAppendPolyData : vtkPolyDataAlgorithm
{
    protected vtkAppendPolyData(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkAppendPolyData New() => new(vtkAppendPolyData_New(), ownsReference: true);
    public new static vtkAppendPolyData WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkAppendPolyData Register(vtkAppendPolyData sourceObject)
    {
        var target = new vtkAppendPolyData(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new void AddInputData(vtkPolyData _arg1)
    {
        vtkAppendPolyData_AddInputData(this.NativePointer, _arg1.NativePointer);
    }

    public new void SetInputDataByNumber(int num, vtkPolyData ds)
    {
        vtkAppendPolyData_SetInputDataByNumber(this.NativePointer, num, ds.NativePointer);
    }

    public new void SetNumberOfInputs(int num)
    {
        vtkAppendPolyData_SetNumberOfInputs(this.NativePointer, num);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkAppendPolyData_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkAppendPolyData_AddInputData(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkAppendPolyData_SetInputDataByNumber(nint self, int num, nint ds);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkAppendPolyData_SetNumberOfInputs(nint self, int num);
    #endregion
}
