// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// extract cell edges from any type of dataset
/// </summary>
/// <remarks>
/// <para>
/// vtkExtractEdges is a filter to extract edges from a dataset. Edges
/// are extracted as lines in an output vtkPolyData.
/// </para>
/// <para>
/// There are two modes of extraction depending on the data member
/// UseAllPoints, If UseAllPoints is enabled, then the output points contain
/// all the input points, and the point ids of the output lines (i.e.,
/// edges) remain unchanged from the input point numbering.  If UseAllPoints
/// is disabled (which is the default), then the numbering of the output points
/// may change, and any unused points are omitted from the filter output.
/// </para>
/// <para>
/// Warning:
/// If present in the filter input, output cell data is produced for the
/// output edges. Since an edge may be used by more than one cell, this is
/// potentially an undefined behavior. To ensure deterministic output, the
/// cell data from the cell with the smallest cell id is copied to the output
/// edge.
/// </para>
/// <para>
/// See also: vtkFeatureEdges
/// </para>
/// </remarks>
public unsafe partial class vtkExtractEdges : vtkPolyDataAlgorithm
{
    protected vtkExtractEdges(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Standard methods for instantiation, obtaining type information, and
    /// printing the state of an instance.
    /// default an instance of vtkMergePoints is used.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkExtractEdges New() => new(vtkExtractEdges_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkExtractEdges FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkExtractEdges TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkExtractEdges Register(vtkExtractEdges sourceObject)
    {
        var target = new vtkExtractEdges(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkExtractEdges_New();
    #endregion
}
