// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// extract cell edges from any type of dataset
/// </summary>
/// <remarks>
/// <para>
/// vtkExtractEdges is a filter to extract edges from a dataset. Edges
/// are extracted as lines in an output vtkPolyData.
/// </para>
/// <para>
/// There are two modes of extraction depending on the data member
/// UseAllPoints, If UseAllPoints is enabled, then the output points contain
/// all the input points, and the point ids of the output lines (i.e.,
/// edges) remain unchanged from the input point numbering.  If UseAllPoints
/// is disabled (which is the default), then the numbering of the output points
/// may change, and any unused points are omitted from the filter output.
/// </para>
/// <para>
/// @warning
/// If present in the filter input, output cell data is produced for the
/// output edges. Since an edge may be used by more than one cell, this is
/// potentially an undefined behavior. To ensure deterministic output, the
/// cell data from the cell with the smallest cell id is copied to the output
/// edge.
/// </para>
/// <para>
/// @sa
/// vtkFeatureEdges
/// </para>
/// </remarks>
public unsafe partial class vtkExtractEdges : vtkPolyDataAlgorithm
{
    protected vtkExtractEdges(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Standard methods for instantiation, obtaining type information, and
    /// printing the state of an instance.
    /// default an instance of vtkMergePoints is used.
    /// </summary>
    public new static vtkExtractEdges New() => new(vtkExtractEdges_New(), ownsReference: true);
    public new static vtkExtractEdges FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkExtractEdges TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkExtractEdges Register(vtkExtractEdges sourceObject)
    {
        var target = new vtkExtractEdges(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkExtractEdges_New();
    #endregion
}
