// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// copy oriented and scaled glyph geometry to every input point
/// </summary>
/// <remarks>
/// <para>
/// vtkGlyph3D is a filter that copies a geometric representation (called
/// a glyph) to every point in the input dataset. The glyph is defined with
/// polygonal data from a source filter input. The glyph may be oriented
/// along the input vectors or normals, and it may be scaled according to
/// scalar data or vector magnitude. More than one glyph may be used by
/// creating a table of source objects, each defining a different glyph. If a
/// table of glyphs is defined, then the table can be indexed into by using
/// either scalar value or vector magnitude.
/// </para>
/// <para>
/// To use this object you'll have to provide an input dataset and a source
/// to define the glyph. Then decide whether you want to scale the glyph and
/// how to scale the glyph (using scalar value or vector magnitude). Next
/// decide whether you want to orient the glyph, and whether to use the
/// vector data or normal data to orient it. Finally, decide whether to use a
/// table of glyphs, or just a single glyph. If you use a table of glyphs,
/// you'll have to decide whether to index into it with scalar value or with
/// vector magnitude.
/// </para>
/// <para>
/// Warning:
/// The scaling of the glyphs is controlled by the ScaleFactor ivar multiplied
/// by the scalar value at each point (if VTK_SCALE_BY_SCALAR is set), or
/// multiplied by the vector magnitude (if VTK_SCALE_BY_VECTOR is set),
/// Alternatively (if VTK_SCALE_BY_VECTORCOMPONENTS is set), the scaling
/// may be specified for x,y,z using the vector components. The
/// scale factor can be further controlled by enabling clamping using the
/// Clamping ivar. If clamping is enabled, the scale is normalized by the
/// Range ivar, and then multiplied by the scale factor. The normalization
/// process includes clamping the scale value between (0,1).
/// </para>
/// <para>
/// Warning:
/// Typically this object operates on input data with scalar and/or vector
/// data. However, scalar and/or vector aren't necessary, and it can be used
/// to copy data from a single source to each point. In this case the scale
/// factor can be used to uniformly scale the glyphs.
/// </para>
/// <para>
/// Warning:
/// The object uses "vector" data to scale glyphs, orient glyphs, and/or index
/// into a table of glyphs. You can choose to use either the vector or normal
/// data at each input point. Use the method SetVectorModeToUseVector() to use
/// the vector input data, and SetVectorModeToUseNormal() to use the
/// normal input data.
/// </para>
/// <para>
/// Warning:
/// If you do use a table of glyphs, make sure to set the Range ivar to make
/// sure the index into the glyph table is computed correctly.
/// </para>
/// <para>
/// Warning:
/// You can turn off scaling of the glyphs completely by using the Scaling
/// ivar. You can also turn off scaling due to data (either vector or scalar)
/// by using the SetScaleModeToDataScalingOff() method.
/// </para>
/// <para>
/// Warning:
/// You can set what arrays to use for the scalars, vectors, normals, and
/// color scalars by using the SetInputArrayToProcess methods in
/// vtkAlgorithm. The first array is scalars, the next vectors, the next
/// normals and finally color scalars.
/// </para>
/// <para>
/// See also: vtkTensorGlyph
/// </para>
/// </remarks>
public unsafe partial class vtkGlyph3D : vtkPolyDataAlgorithm
{
    protected vtkGlyph3D(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Construct object with scaling on, scaling mode is by scalar value,
    /// scale factor = 1.0, the range is (0,1), orient geometry is on, and
    /// orientation is by vector. Clamping and indexing are turned off. No
    /// initial sources are defined.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkGlyph3D New() => new(vtkGlyph3D_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkGlyph3D FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkGlyph3D TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkGlyph3D Register(vtkGlyph3D sourceObject)
    {
        var target = new vtkGlyph3D(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Specify a source object at a specified table location. New style.
    /// Source connection is stored in port 1. This method is equivalent
    /// to SetInputConnection(1, id, outputPort).
    /// </summary>
    public new void SetSourceConnection(int id, vtkAlgorithmOutput algOutput)
    {
        vtkGlyph3D_SetSourceConnection_int_vtkAlgorithmOutputPtr(this.NativePointer, id, algOutput.NativePointer);
    }

    /// <summary>
    /// Specify a source object at a specified table location. New style.
    /// Source connection is stored in port 1. This method is equivalent
    /// to SetInputConnection(1, id, outputPort).
    /// </summary>
    public new void SetSourceConnection(vtkAlgorithmOutput algOutput)
    {
        vtkGlyph3D_SetSourceConnection_vtkAlgorithmOutputPtr(this.NativePointer, algOutput.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkGlyph3D_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkGlyph3D_SetSourceConnection_int_vtkAlgorithmOutputPtr(nint self, int id, nint algOutput);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkGlyph3D_SetSourceConnection_vtkAlgorithmOutputPtr(nint self, nint algOutput);
    #endregion
}
