// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkProbeFilter : vtkDataSetAlgorithm
{
    protected vtkProbeFilter(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkProbeFilter New() => new(vtkProbeFilter_New(), ownsReference: true);
    public new static vtkProbeFilter FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkProbeFilter TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkProbeFilter Register(vtkProbeFilter sourceObject)
    {
        var target = new vtkProbeFilter(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new void SetSourceData(vtkDataObject source)
    {
        vtkProbeFilter_SetSourceData(this.NativePointer, source.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkProbeFilter_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProbeFilter_SetSourceData(nint self, nint source);
    #endregion
}
