// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// extract polygonal data based on geometric connectivity
/// </summary>
/// <remarks>
/// <para>
/// vtkPolyDataConnectivityFilter is a filter that extracts cells that
/// share common points and/or satisfy a scalar threshold
/// criterion. (Such a group of cells is called a region.) The filter
/// works in one of six ways: 1) extract the largest (most points) connected region
/// in the dataset; 2) extract specified region numbers; 3) extract all
/// regions sharing specified point ids; 4) extract all regions sharing
/// specified cell ids; 5) extract the region closest to the specified
/// point; or 6) extract all regions (used to color regions).
/// </para>
/// <para>
/// This filter is specialized for polygonal data. This means it runs a bit
/// faster and is easier to construct visualization networks that process
/// polygonal data.
/// </para>
/// <para>
/// The behavior of vtkPolyDataConnectivityFilter can be modified by turning
/// on the boolean ivar ScalarConnectivity. If this flag is on, the
/// connectivity algorithm is modified so that cells are considered connected
/// only if 1) they are geometrically connected (share a point) and 2) the
/// scalar values of the cell's points falls in the scalar range specified.
/// If ScalarConnectivity and FullScalarConnectivity is ON, all the cell's
/// points must lie in the scalar range specified for the cell to qualify as
/// being connected. If FullScalarConnectivity is OFF, any one of the cell's
/// points may lie in the user specified scalar range for the cell to qualify
/// as being connected.
/// </para>
/// <para>
/// This use of ScalarConnectivity is particularly useful for selecting cells
/// for later processing.
/// </para>
/// <para>
/// See also: vtkConnectivityFilter
/// </para>
/// </remarks>
public unsafe partial class vtkPolyDataConnectivityFilter : vtkPolyDataAlgorithm
{
    protected vtkPolyDataConnectivityFilter(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Construct with default extraction mode to extract largest regions.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkPolyDataConnectivityFilter New() => new(vtkPolyDataConnectivityFilter_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkPolyDataConnectivityFilter FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkPolyDataConnectivityFilter TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkPolyDataConnectivityFilter Register(vtkPolyDataConnectivityFilter sourceObject)
    {
        var target = new vtkPolyDataConnectivityFilter(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>Named values for SetExtractionMode/GetExtractionMode. Unnamed native values are preserved.</summary>
    public enum ExtractionMode : int
    {
        /// <summary>Native: VTK_EXTRACT_ALL_REGIONS.</summary>
        AllRegions = 5,
        /// <summary>Native: VTK_EXTRACT_CELL_SEEDED_REGIONS.</summary>
        CellSeededRegions = 2,
        /// <summary>Native: VTK_EXTRACT_CLOSEST_POINT_REGION.</summary>
        ClosestPointRegion = 6,
        /// <summary>Native: VTK_EXTRACT_LARGEST_REGION.</summary>
        LargestRegion = 4,
        /// <summary>Native: VTK_EXTRACT_POINT_SEEDED_REGIONS.</summary>
        PointSeededRegions = 1,
        /// <summary>Native: VTK_EXTRACT_SPECIFIED_REGIONS.</summary>
        SpecifiedRegions = 3,
    }

    /// <summary>
    /// Turn on/off the coloring of connected regions.
    /// </summary>
    public new void ColorRegionsOn()
    {
        vtkPolyDataConnectivityFilter_ColorRegionsOn(this.NativePointer);
    }

    /// <summary>
    /// Control the extraction of connected surfaces.
    /// </summary>
    public new ExtractionMode GetExtractionMode() => (ExtractionMode)vtkPolyDataConnectivityFilter_GetExtractionMode(this.NativePointer);

    /// <summary>
    /// Control the extraction of connected surfaces.
    /// </summary>
    public new void SetExtractionMode(ExtractionMode _arg) => vtkPolyDataConnectivityFilter_SetExtractionMode(this.NativePointer, (int)_arg);

    /// <summary>
    /// Control the extraction of connected surfaces.
    /// </summary>
    public new void SetExtractionModeToAllRegions()
    {
        vtkPolyDataConnectivityFilter_SetExtractionModeToAllRegions(this.NativePointer);
    }

    /// <summary>
    /// Control the extraction of connected surfaces.
    /// </summary>
    public new void SetExtractionModeToCellSeededRegions()
    {
        vtkPolyDataConnectivityFilter_SetExtractionModeToCellSeededRegions(this.NativePointer);
    }

    /// <summary>
    /// Control the extraction of connected surfaces.
    /// </summary>
    public new void SetExtractionModeToClosestPointRegion()
    {
        vtkPolyDataConnectivityFilter_SetExtractionModeToClosestPointRegion(this.NativePointer);
    }

    /// <summary>
    /// Control the extraction of connected surfaces.
    /// </summary>
    public new void SetExtractionModeToLargestRegion()
    {
        vtkPolyDataConnectivityFilter_SetExtractionModeToLargestRegion(this.NativePointer);
    }

    /// <summary>
    /// Control the extraction of connected surfaces.
    /// </summary>
    public new void SetExtractionModeToPointSeededRegions()
    {
        vtkPolyDataConnectivityFilter_SetExtractionModeToPointSeededRegions(this.NativePointer);
    }

    /// <summary>
    /// Control the extraction of connected surfaces.
    /// </summary>
    public new void SetExtractionModeToSpecifiedRegions()
    {
        vtkPolyDataConnectivityFilter_SetExtractionModeToSpecifiedRegions(this.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPolyDataConnectivityFilter_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataConnectivityFilter_ColorRegionsOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkPolyDataConnectivityFilter_GetExtractionMode(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataConnectivityFilter_SetExtractionMode(nint self, int _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataConnectivityFilter_SetExtractionModeToAllRegions(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataConnectivityFilter_SetExtractionModeToCellSeededRegions(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataConnectivityFilter_SetExtractionModeToClosestPointRegion(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataConnectivityFilter_SetExtractionModeToLargestRegion(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataConnectivityFilter_SetExtractionModeToPointSeededRegions(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataConnectivityFilter_SetExtractionModeToSpecifiedRegions(nint self);
    #endregion
}
