// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// reduce the number of triangles in a mesh
/// </summary>
/// <remarks>
/// <para>
/// vtkQuadricDecimation is a filter to reduce the number of triangles in
/// a triangle mesh, forming a good approximation to the original geometry.
/// The input to vtkQuadricDecimation is a vtkPolyData object, and only
/// triangles are treated. If you desire to decimate polygonal meshes, first
/// triangulate the polygons with vtkTriangleFilter.
/// </para>
/// <para>
/// The algorithm is based on repeated edge collapses until the requested mesh
/// reduction is achieved. Edges are placed in a priority queue based on the
/// "cost" to delete the edge. The cost is an approximate measure of error
/// (distance to the original surface)--described by the so-called quadric
/// error measure. The quadric error measure is associated with each vertex of
/// the mesh and represents a matrix of planes incident on that vertex. The
/// distance of the planes to the vertex is the error in the position of the
/// vertex (originally the vertex error iz zero). As edges are deleted, the
/// quadric error measure associated with the two end points of the edge are
/// summed (this combines the plane equations) and an optimal collapse point
/// can be computed. Edges connected to the collapse point are then reinserted
/// into the queue after computing the new cost to delete them. The process
/// continues until the desired reduction level is reached or topological
/// constraints prevent further reduction. Note that this basic algorithm can
/// be extended to higher dimensions by
/// taking into account variation in attributes (i.e., scalars, vectors, and
/// so on). Attributes are interpolated during the edge collapse,
/// except for vtkIdType arrays: values of removed points are discarded.
/// </para>
/// <para>
/// This paper is based on the work of Garland and Heckbert who first
/// presented the quadric error measure at Siggraph '97 "Surface
/// Simplification Using Quadric Error Metrics". For details of the algorithm
/// Michael Garland's Ph.D. thesis is also recommended. Hughues Hoppe's Vis
/// '99 paper, "New Quadric Metric for Simplifying Meshes with Appearance
/// Attributes" is also a good take on the subject especially as it pertains
/// to the error metric applied to attributes.
/// </para>
/// </remarks>
public unsafe partial class vtkQuadricDecimation : vtkPolyDataAlgorithm
{
    protected vtkQuadricDecimation(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkQuadricDecimation New() => new(vtkQuadricDecimation_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkQuadricDecimation FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkQuadricDecimation TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkQuadricDecimation Register(vtkQuadricDecimation sourceObject)
    {
        var target = new vtkQuadricDecimation(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Set/Get the desired reduction (expressed as a fraction of the original
    /// number of triangles). The actual reduction may be less depending on
    /// triangulation, topological constraints and optional maximum error limit.
    /// </summary>
    /// <remarks>
    /// See also: SetMaximumError
    /// </remarks>
    public new void SetTargetReduction(double _arg)
    {
        vtkQuadricDecimation_SetTargetReduction(this.NativePointer, _arg);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkQuadricDecimation_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkQuadricDecimation_SetTargetReduction(nint self, double _arg);
    #endregion
}
