// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkTubeFilter : vtkPolyDataAlgorithm
{
    protected vtkTubeFilter(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkTubeFilter New() => new(vtkTubeFilter_New(), ownsReference: true);
    public new static vtkTubeFilter WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkTubeFilter Register(vtkTubeFilter sourceObject)
    {
        var target = new vtkTubeFilter(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new void SetNumberOfSides(int _arg)
    {
        vtkTubeFilter_SetNumberOfSides(this.NativePointer, _arg);
    }

    public new void SetRadius(double _arg)
    {
        vtkTubeFilter_SetRadius(this.NativePointer, _arg);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkTubeFilter_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTubeFilter_SetNumberOfSides(nint self, int _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTubeFilter_SetRadius(nint self, double _arg);
    #endregion
}
