// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkSubdivisionFilter.h>

VTKSHARP_API void vtkSubdivisionFilter_SetNumberOfSubdivisions(vtkSubdivisionFilter* self, int _arg) { self->SetNumberOfSubdivisions(_arg); }
