// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkAbstractTransform.h>
#include <vtkTransformPolyDataFilter.h>

VTKSHARP_API vtkTransformPolyDataFilter* vtkTransformPolyDataFilter_New() { return vtkTransformPolyDataFilter::New(); }

VTKSHARP_API void vtkTransformPolyDataFilter_SetTransform(vtkTransformPolyDataFilter* self, vtkAbstractTransform* _arg1) { self->SetTransform(_arg1); }
