// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkImageCast.h>

VTKSHARP_API vtkImageCast* vtkImageCast_New() { return vtkImageCast::New(); }

VTKSHARP_API void vtkImageCast_SetOutputScalarTypeToUnsignedChar(vtkImageCast* self) { self->SetOutputScalarTypeToUnsignedChar(); }
