// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkAlgorithmOutput.h>
#include <vtkGlyph3D.h>

VTKSHARP_API vtkGlyph3D* vtkGlyph3D_New() { return vtkGlyph3D::New(); }

VTKSHARP_API void vtkGlyph3D_SetSourceConnection_int_vtkAlgorithmOutputPtr(vtkGlyph3D* self, int id, vtkAlgorithmOutput* algOutput) { self->SetSourceConnection(id, algOutput); }

VTKSHARP_API void vtkGlyph3D_SetSourceConnection_vtkAlgorithmOutputPtr(vtkGlyph3D* self, vtkAlgorithmOutput* algOutput) { self->SetSourceConnection(algOutput); }
