// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkMarchingSquares.h>

VTKSHARP_API vtkMarchingSquares* vtkMarchingSquares_New() { return vtkMarchingSquares::New(); }

VTKSHARP_API void vtkMarchingSquares_SetValue(vtkMarchingSquares* self, int i, double value) { self->SetValue(i, value); }
