// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkQuadricDecimation.h>

VTKSHARP_API vtkQuadricDecimation* vtkQuadricDecimation_New() { return vtkQuadricDecimation::New(); }

VTKSHARP_API void vtkQuadricDecimation_SetTargetReduction(vtkQuadricDecimation* self, double _arg) { self->SetTargetReduction(_arg); }
