// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkTubeFilter.h>

VTKSHARP_API vtkTubeFilter* vtkTubeFilter_New() { return vtkTubeFilter::New(); }

VTKSHARP_API void vtkTubeFilter_SetNumberOfSides(vtkTubeFilter* self, int _arg) { self->SetNumberOfSides(_arg); }

VTKSHARP_API void vtkTubeFilter_SetRadius(vtkTubeFilter* self, double _arg) { self->SetRadius(_arg); }
