// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Superclass for all sources, filters, and sinks in VTK.
/// </summary>
/// <remarks>
/// <para>
/// vtkAlgorithm is the superclass for all sources, filters, and sinks
/// in VTK.  It defines a generalized interface for executing data
/// processing algorithms.  Pipeline connections are associated with
/// input and output ports that are independent of the type of data
/// passing through the connections.
/// </para>
/// <para>
/// Instances may be used independently or within pipelines with a
/// variety of architectures and update mechanisms.  Pipelines are
/// controlled by instances of vtkExecutive.  Every vtkAlgorithm
/// instance has an associated vtkExecutive when it is used in a
/// pipeline.  The executive is responsible for data flow.
/// </para>
/// </remarks>
public unsafe partial class vtkAlgorithm : vtkObject
{
    protected vtkAlgorithm(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkAlgorithm New() => new(vtkAlgorithm_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkAlgorithm FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkAlgorithm TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkAlgorithm Register(vtkAlgorithm sourceObject)
    {
        var target = new vtkAlgorithm(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Get a proxy object corresponding to the given output port of this
    /// algorithm.  The proxy object can be passed to another algorithm's
    /// SetInputConnection(), AddInputConnection(), and
    /// RemoveInputConnection() methods to modify pipeline connectivity.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkAlgorithmOutput GetOutputPort(int index)
    {
        return vtkAlgorithmOutput.FromBorrowedPointer(vtkAlgorithm_GetOutputPort_int(this.NativePointer, index));
    }

    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkAlgorithmOutput GetOutputPort()
    {
        return vtkAlgorithmOutput.FromBorrowedPointer(vtkAlgorithm_GetOutputPort_(this.NativePointer));
    }

    /// <summary>
    /// Set the connection for the given input port index.  Each input
    /// port of a filter has a specific purpose.  A port may have zero or
    /// more connections and the required number is specified by each
    /// filter.  Setting the connection with this method removes all
    /// other connections from the port.  To add more than one connection
    /// use AddInputConnection().
    /// </summary>
    /// <remarks>
    /// <para>
    /// The input for the connection is the output port of another
    /// filter, which is obtained with GetOutputPort().  Typical usage is
    /// </para>
    /// <para>
    /// filter2-&gt;SetInputConnection(0, filter1-&gt;GetOutputPort(0)).
    /// </para>
    /// </remarks>
    public new void SetInputConnection(int port, vtkAlgorithmOutput input)
    {
        vtkAlgorithm_SetInputConnection_int_vtkAlgorithmOutputPtr(this.NativePointer, port, input.NativePointer);
    }

    /// <summary>
    /// Set the connection for the given input port index.  Each input
    /// port of a filter has a specific purpose.  A port may have zero or
    /// more connections and the required number is specified by each
    /// filter.  Setting the connection with this method removes all
    /// other connections from the port.  To add more than one connection
    /// use AddInputConnection().
    /// </summary>
    /// <remarks>
    /// <para>
    /// The input for the connection is the output port of another
    /// filter, which is obtained with GetOutputPort().  Typical usage is
    /// </para>
    /// <para>
    /// filter2-&gt;SetInputConnection(0, filter1-&gt;GetOutputPort(0)).
    /// </para>
    /// </remarks>
    public new void SetInputConnection(vtkAlgorithmOutput input)
    {
        vtkAlgorithm_SetInputConnection_vtkAlgorithmOutputPtr(this.NativePointer, input.NativePointer);
    }

    /// <summary>
    /// Bring this algorithm's outputs up-to-date.
    /// </summary>
    public new bool Update()
    {
        return vtkAlgorithm_Update_(this.NativePointer);
    }

    /// <summary>
    /// Bring this algorithm's outputs up-to-date.
    /// </summary>
    public new bool Update(int port)
    {
        return vtkAlgorithm_Update_int(this.NativePointer, port);
    }

    /// <summary>
    /// This method enables the passing of data requests to the algorithm
    /// to be used during execution (in addition to bringing a particular
    /// port up-to-date). The requests argument should contain an information
    /// object for each port that requests need to be passed. For each
    /// of those, the pipeline will copy all keys to the output information
    /// before execution. This is equivalent to:
    /// </summary>
    /// <remarks>
    /// Available requests include UPDATE_PIECE_NUMBER(), UPDATE_NUMBER_OF_PIECES()
    /// UPDATE_EXTENT() etc etc.
    /// </remarks>
    public new bool Update(int port, vtkInformationVector requests)
    {
        return vtkAlgorithm_Update_int_vtkInformationVectorPtr(this.NativePointer, port, requests.NativePointer) != 0;
    }

    /// <summary>
    /// Convenience method to update an algorithm after passing requests
    /// to its first output port. See documentation for
    /// Update(int port, vtkInformationVector* requests) for details.
    /// </summary>
    public new bool Update(vtkInformation requests)
    {
        return vtkAlgorithm_Update_vtkInformationPtr(this.NativePointer, requests.NativePointer) != 0;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkAlgorithm_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkAlgorithm_GetOutputPort_int(nint self, int index);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkAlgorithm_GetOutputPort_(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkAlgorithm_SetInputConnection_int_vtkAlgorithmOutputPtr(nint self, int port, nint input);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkAlgorithm_SetInputConnection_vtkAlgorithmOutputPtr(nint self, nint input);

    [DllImport(InteropInfo.NativeLibraryName)]
    [return: MarshalAs(UnmanagedType.U1)]
    private static extern bool vtkAlgorithm_Update_(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    [return: MarshalAs(UnmanagedType.U1)]
    private static extern bool vtkAlgorithm_Update_int(nint self, int port);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkAlgorithm_Update_int_vtkInformationVectorPtr(nint self, int port, nint requests);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkAlgorithm_Update_vtkInformationPtr(nint self, nint requests);
    #endregion
}
