// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Superclass for algorithms that process vtkPointSet input
/// </summary>
/// <remarks>
/// <para>
/// vtkPointSetAlgorithm is a convenience class to make writing algorithms
/// easier. Filter subclasses of vtkPointSetAlgorithm take vtkPointSet (and
/// derived classes) as input to the filter, and produce vtkPointSet as
/// output. (Note that overriding FillInputPortInformation() and
/// FillOutputPortInformation() can be used to change this behavior.)
/// </para>
/// <para>
/// There are some assumptions and defaults made by this class you should be
/// aware of. This class defaults such that your filter will have one input
/// port and one output port. If that is not the case simply change it with
/// SetNumberOfInputPorts() etc. See this classes constructor for the
/// default. To implement a filter, developers should implement the subclass's
/// algorithm in the RequestData(request,inputVec,outputVec) method.
/// </para>
/// </remarks>
public unsafe partial class vtkPointSetAlgorithm : vtkAlgorithm
{
    protected vtkPointSetAlgorithm(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Standard methods for instantiation, obtaining type information, and
    /// printing instances of the class.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkPointSetAlgorithm New() => new(vtkPointSetAlgorithm_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkPointSetAlgorithm FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkPointSetAlgorithm TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkPointSetAlgorithm Register(vtkPointSetAlgorithm sourceObject)
    {
        var target = new vtkPointSetAlgorithm(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPointSetAlgorithm_New();
    #endregion
}
