// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkThreadedImageAlgorithm : vtkImageAlgorithm
{
    protected vtkThreadedImageAlgorithm(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkThreadedImageAlgorithm WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkThreadedImageAlgorithm Register(vtkThreadedImageAlgorithm sourceObject)
    {
        var target = new vtkThreadedImageAlgorithm(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
