// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// represent and manipulate 4x4 transformation matrices
/// </summary>
/// <remarks>
/// <para>
/// vtkMatrix4x4 is a class to represent and manipulate 4x4 matrices.
/// Specifically, it is designed to work on 4x4 transformation matrices
/// found in 3D rendering using homogeneous coordinates [x y z w].
/// Many of the methods take an array of 16 doubles in row-major format.
/// Note that OpenGL stores matrices in column-major format, so the matrix
/// contents must be transposed when they are moved between OpenGL and VTK.
/// </para>
/// <para>
/// See also: vtkTransform
/// </para>
/// </remarks>
public unsafe partial class vtkMatrix4x4 : vtkObject
{
    protected vtkMatrix4x4(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Construct a 4x4 identity matrix.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkMatrix4x4 New() => new(vtkMatrix4x4_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkMatrix4x4 FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkMatrix4x4 TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkMatrix4x4 Register(vtkMatrix4x4 sourceObject)
    {
        var target = new vtkMatrix4x4(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Returns the raw double array holding the matrix.
    /// </summary>
    internal new double* GetData_Internal()
    {
        return vtkMatrix4x4_GetData(this.NativePointer);
    }

    /// <summary>
    /// Returns the element i,j from the matrix.
    /// </summary>
    public new double GetElement(int i, int j)
    {
        return vtkMatrix4x4_GetElement(this.NativePointer, i, j);
    }

    public new void Invert()
    {
        vtkMatrix4x4_Invert(this.NativePointer);
    }

    /// <param name="in">
    /// Buffer length: 4 elements.
    /// </param>
    internal new double* MultiplyPoint_Internal(ReadOnlySpan<double> @in)
    {
        fixed (double* inPtr = @in)
        {
            return vtkMatrix4x4_MultiplyPoint_doubleConstArray4(this.NativePointer, inPtr);
        }
    }

    /// <summary>
    /// For use in Java or Python.
    /// </summary>
    /// <param name="in">
    /// Buffer length: 4 elements.
    /// </param>
    internal new float* MultiplyPoint_Internal(ReadOnlySpan<float> @in)
    {
        fixed (float* inPtr = @in)
        {
            return vtkMatrix4x4_MultiplyPoint_floatConstArray4(this.NativePointer, inPtr);
        }
    }

    /// <param name="in">
    /// Buffer length: 4 elements.
    /// </param>
    /// <param name="out">
    /// Buffer length: 4 elements.
    /// </param>
    public new void MultiplyPoint(ReadOnlySpan<double> @in, Span<double> @out)
    {
        fixed (double* inPtr = @in)
        {
            fixed (double* outPtr = @out)
            {
                vtkMatrix4x4_MultiplyPoint_doubleConstArray4_doubleArray4(this.NativePointer, inPtr, outPtr);
            }
        }
    }

    /// <summary>
    /// Multiply a homogeneous coordinate by this matrix, i.e. out = A*in.
    /// The in[4] and out[4] can be the same array.
    /// </summary>
    /// <param name="in">
    /// Buffer length: 4 elements.
    /// </param>
    /// <param name="out">
    /// Buffer length: 4 elements.
    /// </param>
    public new void MultiplyPoint(ReadOnlySpan<float> @in, Span<float> @out)
    {
        fixed (float* inPtr = @in)
        {
            fixed (float* outPtr = @out)
            {
                vtkMatrix4x4_MultiplyPoint_floatConstArray4_floatArray4(this.NativePointer, inPtr, outPtr);
            }
        }
    }

    /// <summary>
    /// Copies data into the matrix.
    /// </summary>
    /// <param name="data">
    /// Buffer length: 16 elements.
    /// </param>
    public new void SetData(ReadOnlySpan<double> data)
    {
        fixed (double* dataPtr = data)
        {
            vtkMatrix4x4_SetData(this.NativePointer, dataPtr);
        }
    }

    /// <summary>
    /// Sets the element i,j in the matrix.
    /// </summary>
    public new void SetElement(int i, int j, double value)
    {
        vtkMatrix4x4_SetElement(this.NativePointer, i, j, value);
    }

    public new void Transpose()
    {
        vtkMatrix4x4_Transpose(this.NativePointer);
    }

    /// <summary>
    /// Set all of the elements to zero.
    /// </summary>
    public new void Zero()
    {
        vtkMatrix4x4_Zero(this.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkMatrix4x4_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double* vtkMatrix4x4_GetData(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double vtkMatrix4x4_GetElement(nint self, int i, int j);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMatrix4x4_Invert(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double* vtkMatrix4x4_MultiplyPoint_doubleConstArray4(nint self, double* @in);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern float* vtkMatrix4x4_MultiplyPoint_floatConstArray4(nint self, float* @in);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMatrix4x4_MultiplyPoint_doubleConstArray4_doubleArray4(nint self, double* @in, double* @out);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMatrix4x4_MultiplyPoint_floatConstArray4_floatArray4(nint self, float* @in, float* @out);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMatrix4x4_SetData(nint self, double* data);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMatrix4x4_SetElement(nint self, int i, int j, double value);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMatrix4x4_Transpose(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMatrix4x4_Zero(nint self);
    #endregion
}
