// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// extract geometry for structured points
/// </summary>
/// <remarks>
/// <para>
/// vtkImageDataGeometryFilter is a filter that extracts geometry from a
/// structured points dataset. By specifying appropriate i-j-k indices (via the
/// "Extent" instance variable), it is possible to extract a point, a line, a
/// plane (i.e., image), or a "volume" from dataset. (Since the output is
/// of type polydata, the volume is actually a (n x m x o) region of points.)
/// </para>
/// <para>
/// The extent specification is zero-offset. That is, the first k-plane in
/// a 50x50x50 volume is given by (0,49, 0,49, 0,0).
/// </para>
/// <para>
/// @warning
/// If you don't know the dimensions of the input dataset, you can use a large
/// number to specify extent (the number will be clamped appropriately). For
/// example, if the dataset dimensions are 50x50x50, and you want a the fifth
/// k-plane, you can use the extents (0,100, 0,100, 4,4). The 100 will
/// automatically be clamped to 49.
/// </para>
/// <para>
/// @sa
/// vtkGeometryFilter vtkStructuredGridSource
/// </para>
/// </remarks>
public unsafe partial class vtkImageDataGeometryFilter : vtkPolyDataAlgorithm
{
    protected vtkImageDataGeometryFilter(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Construct with initial extent of all the data
    /// </summary>
    public new static vtkImageDataGeometryFilter New() => new(vtkImageDataGeometryFilter_New(), ownsReference: true);
    public new static vtkImageDataGeometryFilter FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkImageDataGeometryFilter TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkImageDataGeometryFilter Register(vtkImageDataGeometryFilter sourceObject)
    {
        var target = new vtkImageDataGeometryFilter(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Set OutputTriangles to true if you wish to generate triangles instead of quads
    /// when extracting cells from 2D imagedata
    /// Currently this functionality is only implemented for 2D imagedata
    /// </summary>
    public new void SetOutputTriangles(bool _arg)
    {
        vtkImageDataGeometryFilter_SetOutputTriangles(this.NativePointer, _arg ? 1 : 0);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkImageDataGeometryFilter_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkImageDataGeometryFilter_SetOutputTriangles(nint self, int _arg);
    #endregion
}
