// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkPointSet.h>
#include <vtkPolyData.h>
#include <vtkPointSetAlgorithm.h>

VTKSHARP_API vtkPointSetAlgorithm* vtkPointSetAlgorithm_New() { return vtkPointSetAlgorithm::New(); }

VTKSHARP_API vtkPolyData* vtkPointSetAlgorithm_GetPolyDataOutput(vtkPointSetAlgorithm* self) { return self->GetPolyDataOutput(); }

VTKSHARP_API void vtkPointSetAlgorithm_SetInputData(vtkPointSetAlgorithm* self, vtkPointSet* _arg1) { self->SetInputData(_arg1); }
