// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// create a polygonal representation of a cube
/// </summary>
/// <remarks>
/// vtkCubeSource creates a cube centered at origin. The cube is represented
/// with four-sided polygons. It is possible to specify the length, width,
/// and height of the cube independently.
/// </remarks>
public unsafe partial class vtkCubeSource : vtkPolyDataAlgorithm
{
    protected vtkCubeSource(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkCubeSource New() => new(vtkCubeSource_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkCubeSource FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkCubeSource TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkCubeSource Register(vtkCubeSource sourceObject)
    {
        var target = new vtkCubeSource(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Set the center of the cube.
    /// </summary>
    public new void SetCenter(double _arg1, double _arg2, double _arg3)
    {
        vtkCubeSource_SetCenter_double_double_double(this.NativePointer, _arg1, _arg2, _arg3);
    }

    /// <summary>
    /// Set the center of the cube.
    /// </summary>
    /// <param name="_arg">
    /// Buffer length: 3 elements.
    /// </param>
    public new void SetCenter(ReadOnlySpan<double> _arg)
    {
        fixed (double* _argPtr = _arg)
        {
            vtkCubeSource_SetCenter_doubleConstArray3(this.NativePointer, _argPtr);
        }
    }

    /// <summary>
    /// Set the length of the cube in the x-direction.
    /// </summary>
    public new void SetXLength(double _arg)
    {
        vtkCubeSource_SetXLength(this.NativePointer, _arg);
    }

    /// <summary>
    /// Set the length of the cube in the y-direction.
    /// </summary>
    public new void SetYLength(double _arg)
    {
        vtkCubeSource_SetYLength(this.NativePointer, _arg);
    }

    /// <summary>
    /// Set the length of the cube in the z-direction.
    /// </summary>
    public new void SetZLength(double _arg)
    {
        vtkCubeSource_SetZLength(this.NativePointer, _arg);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkCubeSource_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCubeSource_SetCenter_double_double_double(nint self, double _arg1, double _arg2, double _arg3);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCubeSource_SetCenter_doubleConstArray3(nint self, double* _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCubeSource_SetXLength(nint self, double _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCubeSource_SetYLength(nint self, double _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCubeSource_SetZLength(nint self, double _arg);
    #endregion
}
