// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// create a random cloud of points
/// </summary>
/// <remarks>
/// <para>
/// vtkPointSource is a source object that creates a user-specified number of
/// points within a specified radius about a specified center point.  By
/// default the location of the points is random within the sphere. It is also
/// possible to generate random points only on the surface of the sphere; or a
/// exponential distribution weighted towards the center point. The output
/// PolyData has the specified number of points and a single cell - a
/// vtkPolyVertex cell referencing all of the points.
/// </para>
/// <para>
/// Note:
/// If Lambda set to zero, a uniform distribution is used. Negative lambda
/// values are allowed, but the distribution function becomes inverted.
/// </para>
/// <para>
/// Note:
/// If you desire to create complex point clouds (e.g., stellar distributions)
/// then use multiple point sources and then append them together using the
/// an append filter (e.g., vtkAppendPolyData).
/// </para>
/// <para>
/// See also: vtkAppendPolyData
/// </para>
/// </remarks>
public unsafe partial class vtkPointSource : vtkPolyDataAlgorithm
{

    protected vtkPointSource(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Standard methods for instantiation, type information, and printing.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkPointSource New() => new(vtkPointSource_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkPointSource FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkPointSource TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkPointSource Register(vtkPointSource sourceObject)
    {
        var target = new vtkPointSource(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Set the number of points to generate.
    /// </summary>
    public new void SetNumberOfPoints(long _arg)
    {
        vtkPointSource_SetNumberOfPoints(this.NativePointer, _arg);
    }

    /// <summary>
    /// Set the radius of the point cloud.  If you are
    /// generating a Gaussian distribution, then this is
    /// the standard deviation for each of x, y, and z.
    /// </summary>
    public new void SetRadius(double _arg)
    {
        vtkPointSource_SetRadius(this.NativePointer, _arg);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPointSource_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPointSource_SetNumberOfPoints(nint self, long _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPointSource_SetRadius(nint self, double _arg);
    #endregion
}
