// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Generate selection from given set of ids
/// </summary>
/// <remarks>
/// <para>
/// vtkSelectionSource generates a vtkSelection from a set of
/// (piece id, cell id) pairs. It will only generate the selection values
/// that match UPDATE_PIECE_NUMBER (i.e. piece == UPDATE_PIECE_NUMBER).
/// vtkSelectionSource can generate a vtkSelection with one or many
/// vtkSelectionNodes.
/// </para>
/// <para>
/// To generate only one vtkSelectionNode, use the functions which don't pass a nodeId
/// to set/get the node information. To generate more than one vtkSelectionNode, use the
/// SetNumberOfNodes/RemoveNode to manipulate the number of nodes,
/// and use the functions that pass the nodeId to set the node information
/// The different nodes can have different contentType per node but the
/// fieldType/elementType is common across all nodes.
/// </para>
/// <para>
/// To define the relation between the nodes you can use SetExpression. If non-empty,
/// the expression is a boolean expression that defines how the selection nodes present
/// in the selection are to be combined together to form the selection. If no expression
/// is specified and there are multiple selection nodes, then the default
/// expression simply combines all the selection nodes using an `or` operator.
/// </para>
/// <para>
/// User-supplied, application-specific selections (with a ContentType of
/// vtkSelectionNode::USER) are not supported.
/// </para>
/// </remarks>
public unsafe partial class vtkSelectionSource : vtkSelectionAlgorithm
{
    protected vtkSelectionSource(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkSelectionSource New() => new(vtkSelectionSource_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkSelectionSource FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkSelectionSource TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkSelectionSource Register(vtkSelectionSource sourceObject)
    {
        var target = new vtkSelectionSource(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Add a (piece, id) to the selection set. The source will generate
    /// only the ids for which piece == UPDATE_PIECE_NUMBER.
    /// If piece == -1, the id applies to all pieces.
    /// </summary>
    public new void AddID(uint nodeId, long piece, long id)
    {
        vtkSelectionSource_AddID(this.NativePointer, nodeId, piece, id);
    }

    /// <summary>
    /// Set/Get the content type.
    /// Possible values are as defined by
    /// vtkSelectionNode::SelectionContent.
    /// </summary>
    /// <remarks>
    /// The default is vtkSelectionNode::SelectionContent::INDICES.
    /// </remarks>
    public new void SetContentType(int contentType)
    {
        vtkSelectionSource_SetContentType(this.NativePointer, contentType);
    }

    /// <summary>
    /// Set/Get the field type for the generated selection.
    /// Possible values are as defined by
    /// vtkSelectionNode::SelectionField.
    /// </summary>
    /// <remarks>
    /// The default is vtkSelectionNode::SelectionField::CELL.
    /// </remarks>
    public new void SetFieldType(int _arg)
    {
        vtkSelectionSource_SetFieldType(this.NativePointer, _arg);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkSelectionSource_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkSelectionSource_AddID(nint self, uint nodeId, long piece, long id);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkSelectionSource_SetContentType(nint self, int contentType);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkSelectionSource_SetFieldType(nint self, int _arg);
    #endregion
}
