using System.Text;
using VtkSharp.Generator.Core.Types;
using VtkSharp.Generator.Core.Whitelist;

namespace VtkSharp.Generator.Core.Generation;

public sealed class CppExportEmitter
{
    private readonly ExportNameGenerator _exportNameGenerator = new();

    public string Emit(string className, IReadOnlyList<string> includeClassNames, bool hasStaticNew, IReadOnlyList<WhitelistFunction> functions)
    {
        var sb = new StringBuilder();
        var exportNames = this.CreateExportNames(className, functions);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#include \"vtksharp_api.h\"");
        if (functions.Any(UsesUnsignedLong))
        {
            sb.AppendLine("#include <cstdint>");
        }
        foreach (var valueStructHeader in functions
                     .Select(f => TypeClassifier.GetValueStructCppHeader(f.Return.Type))
                     .Where(h => h is not null)
                     .Distinct(StringComparer.Ordinal))
        {
            sb.AppendLine($"#include <{valueStructHeader}.h>");
        }
        foreach (var include in includeClassNames.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal))
            sb.AppendLine($"#include <{include}.h>");
        sb.AppendLine($"#include <{className}.h>");
        sb.AppendLine();
        if (hasStaticNew)
            sb.AppendLine($"VTKSHARP_API {className}* {className}_New() {{ return {className}::New(); }}");
        foreach (var function in functions)
        {
            if (hasStaticNew || function != functions[0])
                sb.AppendLine();
            EmitFunction(sb, className, function, exportNames[function]);
        }
        return sb.ToString();
    }

    private static void EmitFunction(StringBuilder sb, string className, WhitelistFunction function, string exportName)
    {
        var isValueStructReturn = TypeClassifier.IsVtkValueStruct(function.Return.Type);

        if (isValueStructReturn)
        {
            var componentCount = TypeClassifier.GetValueStructComponentCount(function.Return.Type);
            var outParamName = $"__out{function.Name}";
            var paramList = new List<string> { $"{className}* self" };
            paramList.AddRange(function.Parameters.Select(p => $"{BindingTypeMapper.ToCppType(p.Type)} {p.Name}"));
            paramList.Add($"double* {outParamName}");

            var args = string.Join(", ", function.Parameters.Select(p => p.Name));
            sb.AppendLine($"VTKSHARP_API void {exportName}({string.Join(", ", paramList)}) {{");
            sb.AppendLine($"    auto c = self->{function.Name}({args});");
            for (int i = 0; i < componentCount; i++)
                sb.AppendLine($"    {outParamName}[{i}] = c[{i}];");
            sb.AppendLine("}");
            return;
        }

        var returnType = BindingTypeMapper.ToCppExportType(function.Return.Type);
        var parameters = new[] { $"{className}* self" }
            .Concat(function.Parameters.Select(parameter => $"{BindingTypeMapper.ToCppExportType(parameter.Type)} {parameter.Name}"));

        var arguments = string.Join(", ", function.Parameters.Select(ToCppArgument));
        var call = $"self->{function.Name}({arguments})";
        if (function.Return.Type == "void")
            sb.AppendLine($"VTKSHARP_API {returnType} {exportName}({string.Join(", ", parameters)}) {{ {call}; }}");
        else if (function.Return.Type == "unsigned long")
            sb.AppendLine($"VTKSHARP_API {returnType} {exportName}({string.Join(", ", parameters)}) {{ return static_cast<std::uint64_t>({call}); }}");
        else
            sb.AppendLine($"VTKSHARP_API {returnType} {exportName}({string.Join(", ", parameters)}) {{ return {call}; }}");
    }

    private static string ToCppArgument(WhitelistParameter parameter)
        => parameter.Type == "unsigned long"
            ? $"static_cast<unsigned long>({parameter.Name})"
            : parameter.Name;

    private static bool UsesUnsignedLong(WhitelistFunction function)
        => function.Return.Type == "unsigned long" ||
           function.Parameters.Any(parameter => parameter.Type == "unsigned long");

    private Dictionary<WhitelistFunction, string> CreateExportNames(string className, IReadOnlyList<WhitelistFunction> functions)
    {
        return this._exportNameGenerator.CreateAll(className,
            functions.Select(f => (f, f.Name, (IReadOnlyList<CanonicalType>)f.Parameters.Select(p => new CanonicalType(p.Type)).ToList())).ToList());
    }
}
