// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// abstract class specifies interface to map data
/// </summary>
/// <remarks>
/// <para>
/// vtkAbstractMapper is an abstract class to specify interface between data and
/// graphics primitives or software rendering techniques. Subclasses of
/// vtkAbstractMapper can be used for rendering 2D data, geometry, or volumetric
/// data.
/// </para>
/// <para>
/// See also: vtkAbstractMapper3D vtkMapper vtkPolyDataMapper vtkVolumeMapper
/// </para>
/// </remarks>
public unsafe partial class vtkAbstractMapper : vtkAlgorithm
{
    protected vtkAbstractMapper(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkAbstractMapper FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkAbstractMapper TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkAbstractMapper Register(vtkAbstractMapper sourceObject)
    {
        var target = new vtkAbstractMapper(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
