// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkAbstractPropPicker : vtkAbstractPicker
{
    protected vtkAbstractPropPicker(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkAbstractPropPicker WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkAbstractPropPicker Register(vtkAbstractPropPicker sourceObject)
    {
        var target = new vtkAbstractPropPicker(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new vtkActor GetActor()
    {
        return vtkActor.WeakReference(vtkAbstractPropPicker_GetActor(this.NativePointer));
    }

    public new vtkProp GetViewProp()
    {
        return vtkProp.WeakReference(vtkAbstractPropPicker_GetViewProp(this.NativePointer));
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkAbstractPropPicker_GetActor(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkAbstractPropPicker_GetViewProp(nint self);
    #endregion
}
