// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// a list of 2D actors
/// </summary>
/// <remarks>
/// <para>
/// vtkActor2DCollection is a subclass of vtkCollection.  vtkActor2DCollection
/// maintains a collection of vtkActor2D objects that is sorted by layer
/// number, with lower layer numbers at the start of the list.  This allows
/// the vtkActor2D objects to be rendered in the correct order.
/// </para>
/// <para>
/// See also: vtkActor2D vtkCollection
/// </para>
/// </remarks>
public unsafe partial class vtkActor2DCollection : vtkPropCollection
{
    protected vtkActor2DCollection(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Destructor for the vtkActor2DCollection class. This removes all
    /// objects from the collection.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkActor2DCollection New() => new(vtkActor2DCollection_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkActor2DCollection FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkActor2DCollection TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkActor2DCollection Register(vtkActor2DCollection sourceObject)
    {
        var target = new vtkActor2DCollection(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkActor2DCollection_New();
    #endregion
}
