// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// perform coordinate transformation, and represent position, in a variety of vtk
/// coordinate systems
/// </summary>
/// <remarks>
/// <para>
/// vtkCoordinate represents position in a variety of coordinate systems, and
/// converts position to other coordinate systems. It also supports relative
/// positioning, so you can create a cascade of vtkCoordinate objects (no loops
/// please!) that refer to each other. The typical usage of this object is
/// to set the coordinate system in which to represent a position (e.g.,
/// SetCoordinateSystemToNormalizedDisplay()), set the value of the coordinate
/// (e.g., SetValue()), and then invoke the appropriate method to convert to
/// another coordinate system (e.g., GetComputedWorldValue()).
/// </para>
/// <para>
/// The coordinate systems in vtk are as follows:
/// &lt;PRE&gt;
/// DISPLAY -             x-y pixel values in window
/// 0, 0 is the lower left of the first pixel,
/// size, size is the upper right of the last pixel
/// NORMALIZED DISPLAY -  x-y (0,1) normalized values
/// 0, 0 is the lower left of the first pixel,
/// 1, 1 is the upper right of the last pixel
/// VIEWPORT -            x-y pixel values in viewport
/// 0, 0 is the lower left of the first pixel,
/// size, size is the upper right of the last pixel
/// NORMALIZED VIEWPORT - x-y (0,1) normalized value in viewport
/// 0, 0 is the lower left of the first pixel,
/// 1, 1 is the upper right of the last pixel
/// VIEW -                x-y-z (-1,1) values in pose coordinates. (z is depth)
/// POSE -                world coords translated and rotated to the camera
/// position and view direction
/// WORLD -               x-y-z global coordinate values
/// USERDEFINED -         x-y-z in User defined space
/// &lt;/PRE&gt;
/// </para>
/// <para>
/// If you cascade vtkCoordinate objects, you refer to another vtkCoordinate
/// object which in turn can refer to others, and so on. This allows you to
/// create composite groups of things like vtkActor2D that are positioned
/// relative to one another. Note that in cascaded sequences, each
/// vtkCoordinate object may be specified in different coordinate systems!
/// </para>
/// <para>
/// @sa
/// vtkActor2D vtkScalarBarActor
/// </para>
/// </remarks>
public unsafe partial class vtkCoordinate : vtkObject
{
    protected vtkCoordinate(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Creates an instance of this class with the following defaults:
    /// value of  (0,0,0) in world coordinates.
    /// </summary>
    public new static vtkCoordinate New() => new(vtkCoordinate_New(), ownsReference: true);
    public new static vtkCoordinate FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkCoordinate TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkCoordinate Register(vtkCoordinate sourceObject)
    {
        var target = new vtkCoordinate(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Set/get the coordinate system which this coordinate
    /// is defined in. The options are Display, Normalized Display,
    /// Viewport, Normalized Viewport, View, and World.
    /// </summary>
    public new void SetCoordinateSystemToDisplay()
    {
        vtkCoordinate_SetCoordinateSystemToDisplay(this.NativePointer);
    }

    /// <summary>
    /// Set/get the coordinate system which this coordinate
    /// is defined in. The options are Display, Normalized Display,
    /// Viewport, Normalized Viewport, View, and World.
    /// </summary>
    public new void SetCoordinateSystemToNormalizedDisplay()
    {
        vtkCoordinate_SetCoordinateSystemToNormalizedDisplay(this.NativePointer);
    }

    /// <summary>
    /// Set/get the coordinate system which this coordinate
    /// is defined in. The options are Display, Normalized Display,
    /// Viewport, Normalized Viewport, View, and World.
    /// </summary>
    public new void SetCoordinateSystemToNormalizedViewport()
    {
        vtkCoordinate_SetCoordinateSystemToNormalizedViewport(this.NativePointer);
    }

    /// <summary>
    /// Set/get the coordinate system which this coordinate
    /// is defined in. The options are Display, Normalized Display,
    /// Viewport, Normalized Viewport, View, and World.
    /// </summary>
    public new void SetCoordinateSystemToPose()
    {
        vtkCoordinate_SetCoordinateSystemToPose(this.NativePointer);
    }

    /// <summary>
    /// Set/get the coordinate system which this coordinate
    /// is defined in. The options are Display, Normalized Display,
    /// Viewport, Normalized Viewport, View, and World.
    /// </summary>
    public new void SetCoordinateSystemToView()
    {
        vtkCoordinate_SetCoordinateSystemToView(this.NativePointer);
    }

    /// <summary>
    /// Set/get the coordinate system which this coordinate
    /// is defined in. The options are Display, Normalized Display,
    /// Viewport, Normalized Viewport, View, and World.
    /// </summary>
    public new void SetCoordinateSystemToViewport()
    {
        vtkCoordinate_SetCoordinateSystemToViewport(this.NativePointer);
    }

    /// <summary>
    /// Set/get the coordinate system which this coordinate
    /// is defined in. The options are Display, Normalized Display,
    /// Viewport, Normalized Viewport, View, and World.
    /// </summary>
    public new void SetCoordinateSystemToWorld()
    {
        vtkCoordinate_SetCoordinateSystemToWorld(this.NativePointer);
    }

    /// <summary>
    /// Set/get the value of this coordinate. This can be thought of as
    /// the position of this coordinate in its coordinate system.
    /// </summary>
    public new void SetValue(double _arg1, double _arg2, double _arg3)
    {
        vtkCoordinate_SetValue_double_double_double(this.NativePointer, _arg1, _arg2, _arg3);
    }

    /// <summary>
    /// Set/get the value of this coordinate. This can be thought of as
    /// the position of this coordinate in its coordinate system.
    /// </summary>
    public new void SetValue(double a, double b)
    {
        vtkCoordinate_SetValue_double_double(this.NativePointer, a, b);
    }

    /// <summary>
    /// Set/get the value of this coordinate. This can be thought of as
    /// the position of this coordinate in its coordinate system.
    /// </summary>
    public new void SetValue(ReadOnlySpan<double> _arg)
    {
        fixed (double* _argPtr = _arg)
        {
            vtkCoordinate_SetValue_doubleConstArray3(this.NativePointer, _argPtr);
        }
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkCoordinate_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetCoordinateSystemToDisplay(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetCoordinateSystemToNormalizedDisplay(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetCoordinateSystemToNormalizedViewport(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetCoordinateSystemToPose(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetCoordinateSystemToView(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetCoordinateSystemToViewport(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetCoordinateSystemToWorld(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetValue_double_double_double(nint self, double _arg1, double _arg2, double _arg3);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetValue_double_double(nint self, double a, double b);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCoordinate_SetValue_doubleConstArray3(nint self, double* _arg);
    #endregion
}
