// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkPolyDataMapper : vtkMapper
{
    protected vtkPolyDataMapper(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkPolyDataMapper New() => new(vtkPolyDataMapper_New(), ownsReference: true);
    public new static vtkPolyDataMapper WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkPolyDataMapper Register(vtkPolyDataMapper sourceObject)
    {
        var target = new vtkPolyDataMapper(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new void SetInputConnection(vtkAlgorithmOutput input)
    {
        vtkPolyDataMapper_SetInputConnection(this.NativePointer, input.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPolyDataMapper_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataMapper_SetInputConnection(nint self, nint input);
    #endregion
}
