// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkProperty2D : vtkObject
{
    protected vtkProperty2D(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkProperty2D New() => new(vtkProperty2D_New(), ownsReference: true);
    public new static vtkProperty2D WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkProperty2D Register(vtkProperty2D sourceObject)
    {
        var target = new vtkProperty2D(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new void SetColor(double _arg1, double _arg2, double _arg3)
    {
        vtkProperty2D_SetColor_double_double_double(this.NativePointer, _arg1, _arg2, _arg3);
    }

    public new void SetColor(ReadOnlySpan<double> _arg)
    {
        fixed (double* _argPtr = _arg)
        {
            vtkProperty2D_SetColor_doubleConstArray3(this.NativePointer, _argPtr);
        }
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkProperty2D_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProperty2D_SetColor_double_double_double(nint self, double _arg1, double _arg2, double _arg3);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProperty2D_SetColor_doubleConstArray3(nint self, double* _arg);
    #endregion
}
