// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// an ordered list of Props
/// </summary>
/// <remarks>
/// <para>
/// vtkPropCollection represents and provides methods to manipulate a list of
/// Props (i.e., vtkProp and subclasses). The list is ordered and duplicate
/// entries are not prevented.
/// </para>
/// <para>
/// See also: vtkProp vtkCollection
/// </para>
/// </remarks>
public unsafe partial class vtkPropCollection : vtkCollection
{
    protected vtkPropCollection(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkPropCollection New() => new(vtkPropCollection_New(), ownsReference: true);
    public new static vtkPropCollection FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkPropCollection TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkPropCollection Register(vtkPropCollection sourceObject)
    {
        var target = new vtkPropCollection(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPropCollection_New();
    #endregion
}
