// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// abstract superclass for all actors, volumes and annotations
/// </summary>
/// <remarks>
/// <para>
/// vtkProp is an abstract superclass for any objects that can exist in a
/// rendered scene (either 2D or 3D). Instances of vtkProp may respond to
/// various render methods (e.g., RenderOpaqueGeometry()). vtkProp also
/// defines the API for picking, LOD manipulation, and common instance
/// variables that control visibility, picking, and dragging.
/// </para>
/// <para>
/// See also: vtkActor2D vtkActor vtkVolume vtkProp3D
/// </para>
/// </remarks>
public unsafe partial class vtkProp : vtkObject
{
    protected vtkProp(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkProp FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkProp TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkProp Register(vtkProp sourceObject)
    {
        var target = new vtkProp(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Method fires PickEvent if the prop is picked.
    /// </summary>
    public new void Pick()
    {
        vtkProp_Pick(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the pickable instance variable.  This determines if the vtkProp
    /// can be picked (typically using the mouse). Also see dragable.
    /// Initial value is true.
    /// </summary>
    public new void PickableOff()
    {
        vtkProp_PickableOff(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the pickable instance variable.  This determines if the vtkProp
    /// can be picked (typically using the mouse). Also see dragable.
    /// Initial value is true.
    /// </summary>
    public new void PickableOn()
    {
        vtkProp_PickableOn(this.NativePointer);
    }

    /// <summary>
    /// Set/Get visibility of this vtkProp. Initial value is true.
    /// </summary>
    public new void VisibilityOff()
    {
        vtkProp_VisibilityOff(this.NativePointer);
    }

    /// <summary>
    /// Set/Get visibility of this vtkProp. Initial value is true.
    /// </summary>
    public new void VisibilityOn()
    {
        vtkProp_VisibilityOn(this.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_Pick(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_PickableOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_PickableOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_VisibilityOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_VisibilityOn(nint self);
    #endregion
}
