// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// abstract superclass for all actors, volumes and annotations
/// </summary>
/// <remarks>
/// <para>
/// vtkProp is an abstract superclass for any objects that can exist in a
/// rendered scene (either 2D or 3D). Instances of vtkProp may respond to
/// various render methods (e.g., RenderOpaqueGeometry()). vtkProp also
/// defines the API for picking, LOD manipulation, and common instance
/// variables that control visibility, picking, and dragging.
/// </para>
/// <para>
/// See also: vtkActor2D vtkActor vtkVolume vtkProp3D
/// </para>
/// </remarks>
public unsafe partial class vtkProp : vtkObject
{
    protected vtkProp(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkProp FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkProp TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkProp Register(vtkProp sourceObject)
    {
        var target = new vtkProp(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Method fires PickEvent if the prop is picked.
    /// </summary>
    public new void Pick()
    {
        vtkProp_Pick(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the pickable instance variable.  This determines if the vtkProp
    /// can be picked (typically using the mouse). Also see dragable.
    /// Initial value is true.
    /// </summary>
    public new void PickableOff()
    {
        vtkProp_PickableOff(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the pickable instance variable.  This determines if the vtkProp
    /// can be picked (typically using the mouse). Also see dragable.
    /// Initial value is true.
    /// </summary>
    public new void PickableOn()
    {
        vtkProp_PickableOn(this.NativePointer);
    }

    /// <summary>
    /// Set/Get visibility of this vtkProp. Initial value is true.
    /// </summary>
    public new void VisibilityOff()
    {
        vtkProp_VisibilityOff(this.NativePointer);
    }

    /// <summary>
    /// Set/Get visibility of this vtkProp. Initial value is true.
    /// </summary>
    public new void VisibilityOn()
    {
        vtkProp_VisibilityOn(this.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_Pick(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_PickableOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_PickableOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_VisibilityOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkProp_VisibilityOn(nint self);
    #endregion
}
