// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// map vtkPolyData to graphics primitives
/// </summary>
/// <remarks>
/// vtkPolyDataMapper is a class that maps polygonal data (i.e., vtkPolyData)
/// to graphics primitives. vtkPolyDataMapper serves as a superclass for
/// device-specific poly data mappers, that actually do the mapping to the
/// rendering/graphics hardware/software.
/// </remarks>
public unsafe partial class vtkPolyDataMapper : vtkMapper
{
    protected vtkPolyDataMapper(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkPolyDataMapper New() => new(vtkPolyDataMapper_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkPolyDataMapper FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkPolyDataMapper TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkPolyDataMapper Register(vtkPolyDataMapper sourceObject)
    {
        var target = new vtkPolyDataMapper(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Specify the input data to map.
    /// </summary>
    public new void SetInputData(vtkPolyData @in)
    {
        vtkPolyDataMapper_SetInputData(this.NativePointer, @in.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPolyDataMapper_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataMapper_SetInputData(nint self, nint @in);
    #endregion
}
