// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkProp3D : vtkProp
{
    protected vtkProp3D(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkProp3D WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkProp3D Register(vtkProp3D sourceObject)
    {
        var target = new vtkProp3D(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
