// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// map vtkPolyData to graphics primitives
/// </summary>
/// <remarks>
/// vtkPolyDataMapper is a class that maps polygonal data (i.e., vtkPolyData)
/// to graphics primitives. vtkPolyDataMapper serves as a superclass for
/// device-specific poly data mappers, that actually do the mapping to the
/// rendering/graphics hardware/software.
/// </remarks>
public unsafe partial class vtkPolyDataMapper : vtkMapper
{
    protected vtkPolyDataMapper(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkPolyDataMapper New() => new(vtkPolyDataMapper_New(), ownsReference: true);
    public new static vtkPolyDataMapper FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkPolyDataMapper TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkPolyDataMapper Register(vtkPolyDataMapper sourceObject)
    {
        var target = new vtkPolyDataMapper(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Specify the input data to map.
    /// </summary>
    public new void SetInputData(vtkPolyData @in)
    {
        vtkPolyDataMapper_SetInputData(this.NativePointer, @in.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPolyDataMapper_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPolyDataMapper_SetInputData(nint self, nint @in);
    #endregion
}
