// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// abstract specification for renderers
/// </summary>
/// <remarks>
/// <para>
/// vtkRenderer provides an abstract specification for renderers. A renderer
/// is an object that controls the rendering process for objects. Rendering
/// is the process of converting geometry, a specification for lights, and
/// a camera view into an image. vtkRenderer also performs coordinate
/// transformation between world coordinates, view coordinates (the computer
/// graphics rendering coordinate system), and display coordinates (the
/// actual screen coordinates on the display device). Certain advanced
/// rendering features such as two-sided lighting can also be controlled.
/// </para>
/// <para>
/// See also: vtkRenderWindow vtkActor vtkCamera vtkLight vtkVolume
/// </para>
/// </remarks>
public unsafe partial class vtkRenderer : vtkViewport
{
    protected vtkRenderer(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Create a vtkRenderer with a black background, a white ambient light,
    /// two-sided lighting turned on, a viewport of (0,0,1,1), and backface
    /// culling turned off.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkRenderer New() => new(vtkRenderer_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkRenderer FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkRenderer TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkRenderer Register(vtkRenderer sourceObject)
    {
        var target = new vtkRenderer(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Add/Remove different types of props to the renderer.
    /// These methods are all synonyms to AddViewProp and RemoveViewProp.
    /// They are here for convenience and backwards compatibility.
    /// </summary>
    public new void AddActor(vtkProp p)
    {
        vtkRenderer_AddActor(this.NativePointer, p.NativePointer);
    }

    /// <summary>
    /// Add an culler to the list of cullers.
    /// </summary>
    public new void AddCuller(vtkCuller _arg1)
    {
        vtkRenderer_AddCuller(this.NativePointer, _arg1.NativePointer);
    }

    /// <summary>
    /// Add a light to the list of lights.
    /// </summary>
    public new void AddLight(vtkLight _arg1)
    {
        vtkRenderer_AddLight(this.NativePointer, _arg1.NativePointer);
    }

    /// <summary>
    /// Add/Remove different types of props to the renderer.
    /// These methods are all synonyms to AddViewProp and RemoveViewProp.
    /// They are here for convenience and backwards compatibility.
    /// </summary>
    public new void AddVolume(vtkProp p)
    {
        vtkRenderer_AddVolume(this.NativePointer, p.NativePointer);
    }

    /// <summary>
    /// Turn on/off a flag which disables the automatic light creation capability.
    /// Normally in VTK if no lights are associated with the renderer, then a light
    /// is automatically created. However, in special circumstances this feature is
    /// undesirable, so the following boolean is provided to disable automatic
    /// light creation. (Turn AutomaticLightCreation off if you do not want lights
    /// to be created.)
    /// </summary>
    public new void AutomaticLightCreationOff()
    {
        vtkRenderer_AutomaticLightCreationOff(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off a flag which disables the automatic light creation capability.
    /// Normally in VTK if no lights are associated with the renderer, then a light
    /// is automatically created. However, in special circumstances this feature is
    /// undesirable, so the following boolean is provided to disable automatic
    /// light creation. (Turn AutomaticLightCreation off if you do not want lights
    /// to be created.)
    /// </summary>
    public new void AutomaticLightCreationOn()
    {
        vtkRenderer_AutomaticLightCreationOn(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off using backing store. This may cause the re-rendering
    /// time to be slightly slower when the view changes. But it is
    /// much faster when the image has not changed, such as during an
    /// expose event.
    /// </summary>
    public new void BackingStoreOff()
    {
        vtkRenderer_BackingStoreOff(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off using backing store. This may cause the re-rendering
    /// time to be slightly slower when the view changes. But it is
    /// much faster when the image has not changed, such as during an
    /// expose event.
    /// </summary>
    public new void BackingStoreOn()
    {
        vtkRenderer_BackingStoreOn(this.NativePointer);
    }

    /// <summary>
    /// Clear the image to the background color.
    /// </summary>
    public new void Clear()
    {
        vtkRenderer_Clear(this.NativePointer);
    }

    /// <summary>
    /// Internal method temporarily removes lights before reloading them
    /// into graphics pipeline.
    /// </summary>
    public new void ClearLights()
    {
        vtkRenderer_ClearLights(this.NativePointer);
    }

    /// <summary>
    /// Create and add a light to renderer.
    /// </summary>
    public new void CreateLight()
    {
        vtkRenderer_CreateLight(this.NativePointer);
    }

    /// <summary>
    /// When this flag is off, render commands are ignored.  It is used to either
    /// multiplex a vtkRenderWindow or render only part of a vtkRenderWindow.
    /// By default, Draw is on.
    /// </summary>
    public new void DrawOff()
    {
        vtkRenderer_DrawOff(this.NativePointer);
    }

    /// <summary>
    /// When this flag is off, render commands are ignored.  It is used to either
    /// multiplex a vtkRenderWindow or render only part of a vtkRenderWindow.
    /// By default, Draw is on.
    /// </summary>
    public new void DrawOn()
    {
        vtkRenderer_DrawOn(this.NativePointer);
    }

    /// <summary>
    /// When this flag is off, the renderer will not erase the background
    /// or the Zbuffer.  It is used to have overlapping renderers.
    /// Both the RenderWindow Erase and Render Erase must be on
    /// for the camera to clear the renderer.  By default, Erase is on.
    /// </summary>
    public new void EraseOff()
    {
        vtkRenderer_EraseOff(this.NativePointer);
    }

    /// <summary>
    /// When this flag is off, the renderer will not erase the background
    /// or the Zbuffer.  It is used to have overlapping renderers.
    /// Both the RenderWindow Erase and Render Erase must be on
    /// for the camera to clear the renderer.  By default, Erase is on.
    /// </summary>
    public new void EraseOn()
    {
        vtkRenderer_EraseOn(this.NativePointer);
    }

    /// <summary>
    /// Get the current camera. If there is not camera assigned to the
    /// renderer already, a new one is created automatically.
    /// This does *not* reset the camera.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkCamera GetActiveCamera()
    {
        return vtkCamera.FromBorrowedPointer(vtkRenderer_GetActiveCamera(this.NativePointer));
    }

    /// <summary>
    /// Return any actors in this renderer.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkActorCollection GetActors()
    {
        return vtkActorCollection.FromBorrowedPointer(vtkRenderer_GetActors(this.NativePointer));
    }

    /// <summary>
    /// Specify the rendering window in which to draw. This is automatically set
    /// when the renderer is created by MakeRenderer.  The user probably
    /// shouldn't ever need to call this method.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkRenderWindow GetRenderWindow()
    {
        return vtkRenderWindow.FromBorrowedPointer(vtkRenderer_GetRenderWindow(this.NativePointer));
    }

    /// <summary>
    /// Compute the aspect ratio of this renderer for the current tile. When
    /// tiled displays are used the aspect ratio of the renderer for a given
    /// tile may be different that the aspect ratio of the renderer when rendered
    /// in it entirety
    /// </summary>
    public new double GetTiledAspectRatio()
    {
        return vtkRenderer_GetTiledAspectRatio(this.NativePointer);
    }

    /// <summary>
    /// Specify the rendering window in which to draw. This is automatically set
    /// when the renderer is created by MakeRenderer.  The user probably
    /// shouldn't ever need to call this method.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkWindow GetVTKWindow()
    {
        return vtkWindow.FromBorrowedPointer(vtkRenderer_GetVTKWindow(this.NativePointer));
    }

    /// <summary>
    /// Given a pixel location in window-system coordinates, return the Z value.
    /// </summary>
    /// <remarks>
    /// X and Y are in pixels with (0, 0) at the bottom-left corner of the render window.
    /// Returns 1.0 (far plane) for any coordinate outside [0, windowWidth-1] x [0, windowHeight-1].
    /// The Z value is normalized (0,1) between the front and back clipping planes.
    /// By default this function accesses the `vtkRenderWindow`'s depth buffer
    /// that is only valid right after this specific renderer has rendered.
    /// If `SafeGetZ` is On, this function will use a `vtkHardwareSelector` to
    /// get the depth information in flight. This approach always works,
    /// but takes more time as it invokes a render on the whole scene.
    /// </remarks>
    public new double GetZ(int x, int y)
    {
        return vtkRenderer_GetZ(this.NativePointer, x, y);
    }

    /// <summary>
    /// Turn on/off interactive status.  An interactive renderer is one that
    /// can receive events from an interactor.  Should only be set if
    /// there are multiple renderers in the same section of the viewport.
    /// </summary>
    public new void InteractiveOff()
    {
        vtkRenderer_InteractiveOff(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off interactive status.  An interactive renderer is one that
    /// can receive events from an interactor.  Should only be set if
    /// there are multiple renderers in the same section of the viewport.
    /// </summary>
    public new void InteractiveOn()
    {
        vtkRenderer_InteractiveOn(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off the automatic repositioning of lights as the camera moves.
    /// If LightFollowCamera is on, lights that are designated as Headlights
    /// or CameraLights will be adjusted to move with this renderer's camera.
    /// If LightFollowCamera is off, the lights will not be adjusted.
    /// </summary>
    /// <remarks>
    /// (Note: In previous versions of vtk, this light-tracking
    /// functionality was part of the interactors, not the renderer. For
    /// backwards compatibility, the older, more limited interactor
    /// behavior is enabled by default. To disable this mode, turn the
    /// interactor's LightFollowCamera flag OFF, and leave the renderer's
    /// LightFollowCamera flag ON.)
    /// </remarks>
    public new void LightFollowCameraOff()
    {
        vtkRenderer_LightFollowCameraOff(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off the automatic repositioning of lights as the camera moves.
    /// If LightFollowCamera is on, lights that are designated as Headlights
    /// or CameraLights will be adjusted to move with this renderer's camera.
    /// If LightFollowCamera is off, the lights will not be adjusted.
    /// </summary>
    /// <remarks>
    /// (Note: In previous versions of vtk, this light-tracking
    /// functionality was part of the interactors, not the renderer. For
    /// backwards compatibility, the older, more limited interactor
    /// behavior is enabled by default. To disable this mode, turn the
    /// interactor's LightFollowCamera flag OFF, and leave the renderer's
    /// LightFollowCamera flag ON.)
    /// </remarks>
    public new void LightFollowCameraOn()
    {
        vtkRenderer_LightFollowCameraOn(this.NativePointer);
    }

    /// <summary>
    /// Create a new Light sutible for use with this type of Renderer.
    /// For example, a vtkMesaRenderer should create a vtkMesaLight
    /// in this function.   The default is to just call vtkLight::New.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkLight MakeLight()
    {
        return vtkLight.FromBorrowedPointer(vtkRenderer_MakeLight(this.NativePointer));
    }

    /// <summary>
    /// Return the prop (via a vtkAssemblyPath) that has the highest z value
    /// at the given x, y position in the viewport.  Basically, the top most
    /// prop that renders the pixel at selectionX, selectionY will be returned.
    /// If nothing was picked then NULL is returned.  This method selects from
    /// the renderer's Prop list.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkAssemblyPath PickProp(double selectionX, double selectionY)
    {
        return vtkAssemblyPath.FromBorrowedPointer(vtkRenderer_PickProp_double_double(this.NativePointer, selectionX, selectionY));
    }

    /// <summary>
    /// Return the prop (via a vtkAssemblyPath) that has the highest z value
    /// at the given x, y position in the viewport.  Basically, the top most
    /// prop that renders the pixel at selectionX, selectionY will be returned.
    /// If nothing was picked then NULL is returned.  This method selects from
    /// the renderer's Prop list.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkAssemblyPath PickProp(double selectionX1, double selectionY1, double selectionX2, double selectionY2)
    {
        return vtkAssemblyPath.FromBorrowedPointer(vtkRenderer_PickProp_double_double_double_double(this.NativePointer, selectionX1, selectionY1, selectionX2, selectionY2));
    }

    /// <summary>
    /// Add/Remove different types of props to the renderer.
    /// These methods are all synonyms to AddViewProp and RemoveViewProp.
    /// They are here for convenience and backwards compatibility.
    /// </summary>
    public new void RemoveActor(vtkProp p)
    {
        vtkRenderer_RemoveActor(this.NativePointer, p.NativePointer);
    }

    /// <summary>
    /// Remove all lights from the list of lights.
    /// </summary>
    public new void RemoveAllLights()
    {
        vtkRenderer_RemoveAllLights(this.NativePointer);
    }

    /// <summary>
    /// Remove an actor from the list of cullers.
    /// </summary>
    public new void RemoveCuller(vtkCuller _arg1)
    {
        vtkRenderer_RemoveCuller(this.NativePointer, _arg1.NativePointer);
    }

    /// <summary>
    /// Remove a light from the list of lights.
    /// </summary>
    public new void RemoveLight(vtkLight _arg1)
    {
        vtkRenderer_RemoveLight(this.NativePointer, _arg1.NativePointer);
    }

    /// <summary>
    /// Add/Remove different types of props to the renderer.
    /// These methods are all synonyms to AddViewProp and RemoveViewProp.
    /// They are here for convenience and backwards compatibility.
    /// </summary>
    public new void RemoveVolume(vtkProp p)
    {
        vtkRenderer_RemoveVolume(this.NativePointer, p.NativePointer);
    }

    /// <summary>
    /// CALLED BY vtkRenderWindow ONLY. End-user pass your way and call
    /// vtkRenderWindow::Render().
    /// Create an image. This is a superclass method which will in turn
    /// call the DeviceRender method of Subclasses of vtkRenderer.
    /// </summary>
    public new void Render()
    {
        vtkRenderer_Render(this.NativePointer);
    }

    /// <summary>
    /// Automatically set up the camera based on the visible actors.
    /// The camera will reposition itself to view the center point of the actors,
    /// and move along its initial view plane normal (i.e., vector defined from
    /// camera position to focal point) so that all of the actors can be seen.
    /// Returns true if camera position was actually reset in the process.
    /// </summary>
    public new bool ResetCamera()
    {
        return vtkRenderer_ResetCamera_(this.NativePointer);
    }

    /// <summary>
    /// Automatically set up the camera based on a specified bounding box
    /// (xmin, xmax, ymin, ymax, zmin, zmax). Camera will reposition itself so
    /// that its focal point is the center of the bounding box, and adjust its
    /// distance and position to preserve its initial view plane normal
    /// (i.e., vector defined from camera position to focal point). Note: if
    /// the view plane is parallel to the view up axis, the view up axis will
    /// be reset to one of the three coordinate axes.
    /// </summary>
    /// <param name="bounds">
    /// Buffer length: 6 elements.
    /// </param>
    public new void ResetCamera(ReadOnlySpan<double> bounds)
    {
        fixed (double* boundsPtr = bounds)
        {
            vtkRenderer_ResetCamera_doubleConstArray6(this.NativePointer, boundsPtr);
        }
    }

    /// <summary>
    /// Alternative version of ResetCamera(bounds[6]);
    /// </summary>
    public new void ResetCamera(double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
    {
        vtkRenderer_ResetCamera_double_double_double_double_double_double(this.NativePointer, xmin, xmax, ymin, ymax, zmin, zmax);
    }

    /// <summary>
    /// Reset the camera clipping range based on the bounds of the
    /// visible actors. This ensures that no props are cut off
    /// </summary>
    public new void ResetCameraClippingRange()
    {
        vtkRenderer_ResetCameraClippingRange_(this.NativePointer);
    }

    /// <summary>
    /// Reset the camera clipping range based on a bounding box.
    /// </summary>
    /// <param name="bounds">
    /// Buffer length: 6 elements.
    /// </param>
    public new void ResetCameraClippingRange(ReadOnlySpan<double> bounds)
    {
        fixed (double* boundsPtr = bounds)
        {
            vtkRenderer_ResetCameraClippingRange_doubleConstArray6(this.NativePointer, boundsPtr);
        }
    }

    /// <summary>
    /// Reset the camera clipping range based on a bounding box.
    /// </summary>
    public new void ResetCameraClippingRange(double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
    {
        vtkRenderer_ResetCameraClippingRange_double_double_double_double_double_double(this.NativePointer, xmin, xmax, ymin, ymax, zmin, zmax);
    }

    /// <summary>
    /// If this flag is On `GetZ(int, int)` will use a vtkHardwareSelector
    /// internally to determine the Z value. Otherwise, it will use
    /// `vtkRenderWindow::GetZbufferValue`.
    /// See `GetZ(int, int)` documentation for more information.
    /// Default is off.
    /// </summary>
    public new void SafeGetZOff()
    {
        vtkRenderer_SafeGetZOff(this.NativePointer);
    }

    /// <summary>
    /// If this flag is On `GetZ(int, int)` will use a vtkHardwareSelector
    /// internally to determine the Z value. Otherwise, it will use
    /// `vtkRenderWindow::GetZbufferValue`.
    /// See `GetZ(int, int)` documentation for more information.
    /// Default is off.
    /// </summary>
    public new void SafeGetZOn()
    {
        vtkRenderer_SafeGetZOn(this.NativePointer);
    }

    /// <summary>
    /// Specify the camera to use for this renderer.
    /// </summary>
    public new void SetActiveCamera(vtkCamera _arg1)
    {
        vtkRenderer_SetActiveCamera(this.NativePointer, _arg1.NativePointer);
    }

    /// <summary>
    /// Set the intensity of ambient lighting.
    /// </summary>
    public new void SetAmbient(double _arg1, double _arg2, double _arg3)
    {
        vtkRenderer_SetAmbient_double_double_double(this.NativePointer, _arg1, _arg2, _arg3);
    }

    /// <summary>
    /// Set the intensity of ambient lighting.
    /// </summary>
    /// <param name="_arg">
    /// Buffer length: 3 elements.
    /// </param>
    public new void SetAmbient(ReadOnlySpan<double> _arg)
    {
        fixed (double* _argPtr = _arg)
        {
            vtkRenderer_SetAmbient_doubleConstArray3(this.NativePointer, _argPtr);
        }
    }

    public new void SetPass(vtkRenderPass p)
    {
        vtkRenderer_SetPass(this.NativePointer, p.NativePointer);
    }

    /// <summary>
    /// Specify the rendering window in which to draw. This is automatically set
    /// when the renderer is created by MakeRenderer.  The user probably
    /// shouldn't ever need to call this method.
    /// </summary>
    public new void SetRenderWindow(vtkRenderWindow _arg1)
    {
        vtkRenderer_SetRenderWindow(this.NativePointer, _arg1.NativePointer);
    }

    /// <summary>
    /// Set/Get whether this viewport should have a textured background.
    /// Default is off.
    /// </summary>
    public new void TexturedBackgroundOff()
    {
        vtkRenderer_TexturedBackgroundOff(this.NativePointer);
    }

    /// <summary>
    /// Set/Get whether this viewport should have a textured background.
    /// Default is off.
    /// </summary>
    public new void TexturedBackgroundOn()
    {
        vtkRenderer_TexturedBackgroundOn(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off two-sided lighting of surfaces. If two-sided lighting is
    /// off, then only the side of the surface facing the light(s) will be lit,
    /// and the other side dark. If two-sided lighting on, both sides of the
    /// surface will be lit.
    /// </summary>
    public new void TwoSidedLightingOff()
    {
        vtkRenderer_TwoSidedLightingOff(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off two-sided lighting of surfaces. If two-sided lighting is
    /// off, then only the side of the surface facing the light(s) will be lit,
    /// and the other side dark. If two-sided lighting on, both sides of the
    /// surface will be lit.
    /// </summary>
    public new void TwoSidedLightingOn()
    {
        vtkRenderer_TwoSidedLightingOn(this.NativePointer);
    }

    /// <summary>
    /// If this flag is true and the rendering engine supports it, image based
    /// lighting is enabled and surface rendering displays environment reflections.
    /// Image Based Lighting rely on the environment texture to compute lighting
    /// if it has been provided.
    /// </summary>
    public new void UseImageBasedLightingOff()
    {
        vtkRenderer_UseImageBasedLightingOff(this.NativePointer);
    }

    /// <summary>
    /// If this flag is true and the rendering engine supports it, image based
    /// lighting is enabled and surface rendering displays environment reflections.
    /// Image Based Lighting rely on the environment texture to compute lighting
    /// if it has been provided.
    /// </summary>
    public new void UseImageBasedLightingOn()
    {
        vtkRenderer_UseImageBasedLightingOn(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off rendering of shadows if supported
    /// Initial value is off.
    /// </summary>
    public new void UseShadowsOff()
    {
        vtkRenderer_UseShadowsOff(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off rendering of shadows if supported
    /// Initial value is off.
    /// </summary>
    public new void UseShadowsOn()
    {
        vtkRenderer_UseShadowsOn(this.NativePointer);
    }

    /// <summary>
    /// Convert view point coordinates to world coordinates.
    /// </summary>
    public new void ViewToWorld()
    {
        vtkRenderer_ViewToWorld(this.NativePointer);
    }

    /// <summary>
    /// Returns the number of visible actors.
    /// </summary>
    public new int VisibleActorCount()
    {
        return vtkRenderer_VisibleActorCount(this.NativePointer);
    }

    /// <summary>
    /// Returns the number of visible volumes.
    /// </summary>
    public new int VisibleVolumeCount()
    {
        return vtkRenderer_VisibleVolumeCount(this.NativePointer);
    }

    /// <summary>
    /// Convert world point coordinates to view coordinates.
    /// </summary>
    public new void WorldToView()
    {
        vtkRenderer_WorldToView(this.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkRenderer_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_AddActor(nint self, nint p);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_AddCuller(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_AddLight(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_AddVolume(nint self, nint p);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_AutomaticLightCreationOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_AutomaticLightCreationOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_BackingStoreOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_BackingStoreOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_Clear(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_ClearLights(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_CreateLight(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_DrawOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_DrawOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_EraseOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_EraseOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkRenderer_GetActiveCamera(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkRenderer_GetActors(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkRenderer_GetRenderWindow(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double vtkRenderer_GetTiledAspectRatio(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkRenderer_GetVTKWindow(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double vtkRenderer_GetZ(nint self, int x, int y);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_InteractiveOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_InteractiveOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_LightFollowCameraOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_LightFollowCameraOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkRenderer_MakeLight(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkRenderer_PickProp_double_double(nint self, double selectionX, double selectionY);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkRenderer_PickProp_double_double_double_double(nint self, double selectionX1, double selectionY1, double selectionX2, double selectionY2);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_RemoveActor(nint self, nint p);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_RemoveAllLights(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_RemoveCuller(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_RemoveLight(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_RemoveVolume(nint self, nint p);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_Render(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    [return: MarshalAs(UnmanagedType.U1)]
    private static extern bool vtkRenderer_ResetCamera_(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_ResetCamera_doubleConstArray6(nint self, double* bounds);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_ResetCamera_double_double_double_double_double_double(nint self, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_ResetCameraClippingRange_(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_ResetCameraClippingRange_doubleConstArray6(nint self, double* bounds);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_ResetCameraClippingRange_double_double_double_double_double_double(nint self, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_SafeGetZOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_SafeGetZOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_SetActiveCamera(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_SetAmbient_double_double_double(nint self, double _arg1, double _arg2, double _arg3);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_SetAmbient_doubleConstArray3(nint self, double* _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_SetPass(nint self, nint p);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_SetRenderWindow(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_TexturedBackgroundOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_TexturedBackgroundOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_TwoSidedLightingOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_TwoSidedLightingOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_UseImageBasedLightingOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_UseImageBasedLightingOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_UseShadowsOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_UseShadowsOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_ViewToWorld(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkRenderer_VisibleActorCount(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkRenderer_VisibleVolumeCount(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkRenderer_WorldToView(nint self);
    #endregion
}
