// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Perform part of the rendering of a vtkRenderer.
/// </summary>
/// <remarks>
/// <para>
/// vtkRenderPass is a deferred class with a simple deferred method Render.
/// This method performs a rendering pass of the scene described in
/// vtkRenderState.
/// Subclasses define what really happens during rendering.
/// </para>
/// <para>
/// Directions to write a subclass of vtkRenderPass:
/// It is up to the subclass to decide if it needs to delegate part of its job
/// to some other vtkRenderPass objects ("delegates").
/// - The subclass has to define ivar to set/get its delegates.
/// - The documentation of the subclass has to describe:
/// - what each delegate is supposed to perform
/// - if a delegate is supposed to be used once or multiple times
/// - what it expects to have in the framebuffer before starting (status
/// of colorbuffers, depth buffer, stencil buffer)
/// - what it will change in the framebuffer.
/// - A pass cannot modify the vtkRenderState where it will perform but
/// it can build a new vtkRenderState (it can change the FrameBuffer, change the
/// prop array, changed the required prop properties keys (usually adding some
/// to a copy of the existing list) but it has to keep the same vtkRenderer
/// object), make it current and pass it to its delegate.
/// - at the end of the execution of Render, the pass has to ensure the
/// current vtkRenderState is the one it has in argument.
/// </para>
/// <para>
/// See also: vtkRenderState vtkRenderer
/// </para>
/// </remarks>
public unsafe partial class vtkRenderPass : vtkObject
{
    protected vtkRenderPass(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkRenderPass FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkRenderPass TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkRenderPass Register(vtkRenderPass sourceObject)
    {
        var target = new vtkRenderPass(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
