// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkSelectVisiblePoints : vtkPolyDataAlgorithm
{
    protected vtkSelectVisiblePoints(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkSelectVisiblePoints New() => new(vtkSelectVisiblePoints_New(), ownsReference: true);
    public new static vtkSelectVisiblePoints WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkSelectVisiblePoints Register(vtkSelectVisiblePoints sourceObject)
    {
        var target = new vtkSelectVisiblePoints(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkSelectVisiblePoints_New();
    #endregion
}
