// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkTexturedActor2D : vtkActor2D
{
    protected vtkTexturedActor2D(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkTexturedActor2D New() => new(vtkTexturedActor2D_New(), ownsReference: true);
    public new static vtkTexturedActor2D WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkTexturedActor2D Register(vtkTexturedActor2D sourceObject)
    {
        var target = new vtkTexturedActor2D(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkTexturedActor2D_New();
    #endregion
}
