// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkTextProperty : vtkObject
{
    protected vtkTextProperty(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkTextProperty New() => new(vtkTextProperty_New(), ownsReference: true);
    public new static vtkTextProperty WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkTextProperty Register(vtkTextProperty sourceObject)
    {
        var target = new vtkTextProperty(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkTextProperty_New();
    #endregion
}
