// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkTDxInteractorStyle : vtkObject
{
    protected vtkTDxInteractorStyle(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    internal new static vtkTDxInteractorStyle FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    internal new static vtkTDxInteractorStyle TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkTDxInteractorStyle Register(vtkTDxInteractorStyle sourceObject)
    {
        var target = new vtkTDxInteractorStyle(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
