// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// represent text properties.
/// </summary>
/// <remarks>
/// <para>
/// vtkTextProperty is an object that represents text properties.
/// The primary properties that can be set are color, opacity, font size,
/// font family horizontal and vertical justification, bold/italic/shadow
/// styles.
/// </para>
/// <para>
/// See also: vtkTextMapper vtkTextActor vtkLegendBoxActor vtkCaptionActor2D
/// </para>
/// </remarks>
public unsafe partial class vtkTextProperty : vtkObject
{
    protected vtkTextProperty(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Creates a new text property with font size 12, bold off, italic off,
    /// and Arial font.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkTextProperty New() => new(vtkTextProperty_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkTextProperty FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkTextProperty TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkTextProperty Register(vtkTextProperty sourceObject)
    {
        var target = new vtkTextProperty(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Enable/disable text bolding.
    /// </summary>
    public new void BoldOff()
    {
        vtkTextProperty_BoldOff(this.NativePointer);
    }

    /// <summary>
    /// Enable/disable text bolding.
    /// </summary>
    public new void BoldOn()
    {
        vtkTextProperty_BoldOn(this.NativePointer);
    }

    /// <summary>
    /// Enable/disable text frame.
    /// </summary>
    public new void FrameOff()
    {
        vtkTextProperty_FrameOff(this.NativePointer);
    }

    /// <summary>
    /// Enable/disable text frame.
    /// </summary>
    public new void FrameOn()
    {
        vtkTextProperty_FrameOn(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the font size (in points).
    /// </summary>
    public new int GetFontSize()
    {
        return vtkTextProperty_GetFontSize(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the text's opacity. 1.0 is totally opaque and 0.0 is completely
    /// transparent.
    /// </summary>
    public new double GetOpacity()
    {
        return vtkTextProperty_GetOpacity(this.NativePointer);
    }

    /// <summary>
    /// Enable/disable text italic.
    /// </summary>
    public new void ItalicOff()
    {
        vtkTextProperty_ItalicOff(this.NativePointer);
    }

    /// <summary>
    /// Enable/disable text italic.
    /// </summary>
    public new void ItalicOn()
    {
        vtkTextProperty_ItalicOn(this.NativePointer);
    }

    /// <summary>
    /// Set the color of the text.
    /// </summary>
    public new void SetColor(double _arg1, double _arg2, double _arg3)
    {
        vtkTextProperty_SetColor_double_double_double(this.NativePointer, _arg1, _arg2, _arg3);
    }

    /// <summary>
    /// Set the color of the text.
    /// </summary>
    /// <param name="_arg">
    /// Buffer length: 3 elements.
    /// </param>
    public new void SetColor(ReadOnlySpan<double> _arg)
    {
        fixed (double* _argPtr = _arg)
        {
            vtkTextProperty_SetColor_doubleConstArray3(this.NativePointer, _argPtr);
        }
    }

    /// <summary>
    /// Set/Get the font family. Supports legacy three font family system.
    /// If the symbolic constant VTK_FONT_FILE is returned by GetFontFamily(), the
    /// string returned by GetFontFile() must be an absolute filepath
    /// to a local FreeType compatible font.
    /// </summary>
    public new void SetFontFamilyAsString(string _arg)
    {
        #if NET8_0_OR_GREATER
        vtkTextProperty_SetFontFamilyAsString(this.NativePointer, _arg);
        #else
        vtkTextProperty_SetFontFamilyAsString(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg));
        #endif
    }

    /// <summary>
    /// Set/Get the font family. Supports legacy three font family system.
    /// If the symbolic constant VTK_FONT_FILE is returned by GetFontFamily(), the
    /// string returned by GetFontFile() must be an absolute filepath
    /// to a local FreeType compatible font.
    /// </summary>
    public new void SetFontFamilyToArial()
    {
        vtkTextProperty_SetFontFamilyToArial(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the font family. Supports legacy three font family system.
    /// If the symbolic constant VTK_FONT_FILE is returned by GetFontFamily(), the
    /// string returned by GetFontFile() must be an absolute filepath
    /// to a local FreeType compatible font.
    /// </summary>
    public new void SetFontFamilyToCourier()
    {
        vtkTextProperty_SetFontFamilyToCourier(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the font family. Supports legacy three font family system.
    /// If the symbolic constant VTK_FONT_FILE is returned by GetFontFamily(), the
    /// string returned by GetFontFile() must be an absolute filepath
    /// to a local FreeType compatible font.
    /// </summary>
    public new void SetFontFamilyToTimes()
    {
        vtkTextProperty_SetFontFamilyToTimes(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the font size (in points).
    /// </summary>
    public new void SetFontSize(int _arg)
    {
        vtkTextProperty_SetFontSize(this.NativePointer, _arg);
    }

    /// <summary>
    /// Set/Get the horizontal justification to left (default), centered,
    /// or right.
    /// </summary>
    public new void SetJustificationToCentered()
    {
        vtkTextProperty_SetJustificationToCentered(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the horizontal justification to left (default), centered,
    /// or right.
    /// </summary>
    public new void SetJustificationToLeft()
    {
        vtkTextProperty_SetJustificationToLeft(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the horizontal justification to left (default), centered,
    /// or right.
    /// </summary>
    public new void SetJustificationToRight()
    {
        vtkTextProperty_SetJustificationToRight(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the (extra) spacing between lines,
    /// expressed as a text height multiplication factor.
    /// </summary>
    public new void SetLineSpacing(double _arg)
    {
        vtkTextProperty_SetLineSpacing(this.NativePointer, _arg);
    }

    /// <summary>
    /// Set/Get the text's opacity. 1.0 is totally opaque and 0.0 is completely
    /// transparent.
    /// </summary>
    public new void SetOpacity(double _arg)
    {
        vtkTextProperty_SetOpacity(this.NativePointer, _arg);
    }

    /// <summary>
    /// Set/Get the shadow offset, i.e. the distance from the text to
    /// its shadow, in the same unit as FontSize.
    /// </summary>
    public new void SetShadowOffset(int _arg1, int _arg2)
    {
        vtkTextProperty_SetShadowOffset_int_int(this.NativePointer, _arg1, _arg2);
    }

    /// <summary>
    /// Set/Get the shadow offset, i.e. the distance from the text to
    /// its shadow, in the same unit as FontSize.
    /// </summary>
    /// <param name="_arg">
    /// Buffer length: 2 elements.
    /// </param>
    public new void SetShadowOffset(ReadOnlySpan<int> _arg)
    {
        fixed (int* _argPtr = _arg)
        {
            vtkTextProperty_SetShadowOffset_intConstArray2(this.NativePointer, _argPtr);
        }
    }

    /// <summary>
    /// Set/Get the vertical justification to bottom (default), middle,
    /// or top.
    /// </summary>
    public new void SetVerticalJustificationToBottom()
    {
        vtkTextProperty_SetVerticalJustificationToBottom(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the vertical justification to bottom (default), middle,
    /// or top.
    /// </summary>
    public new void SetVerticalJustificationToCentered()
    {
        vtkTextProperty_SetVerticalJustificationToCentered(this.NativePointer);
    }

    /// <summary>
    /// Set/Get the vertical justification to bottom (default), middle,
    /// or top.
    /// </summary>
    public new void SetVerticalJustificationToTop()
    {
        vtkTextProperty_SetVerticalJustificationToTop(this.NativePointer);
    }

    /// <summary>
    /// Enable/disable text shadow.
    /// </summary>
    public new void ShadowOff()
    {
        vtkTextProperty_ShadowOff(this.NativePointer);
    }

    /// <summary>
    /// Enable/disable text shadow.
    /// </summary>
    public new void ShadowOn()
    {
        vtkTextProperty_ShadowOn(this.NativePointer);
    }

    /// <summary>
    /// Shallow copy of a text property.
    /// </summary>
    public new void ShallowCopy(vtkTextProperty tprop)
    {
        vtkTextProperty_ShallowCopy(this.NativePointer, tprop.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkTextProperty_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_BoldOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_BoldOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_FrameOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_FrameOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkTextProperty_GetFontSize(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double vtkTextProperty_GetOpacity(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_ItalicOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_ItalicOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetColor_double_double_double(nint self, double _arg1, double _arg2, double _arg3);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetColor_doubleConstArray3(nint self, double* _arg);

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkTextProperty_SetFontFamilyAsString(nint self, string _arg);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetFontFamilyAsString(nint self, byte[] _arg);
#endif

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetFontFamilyToArial(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetFontFamilyToCourier(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetFontFamilyToTimes(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetFontSize(nint self, int _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetJustificationToCentered(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetJustificationToLeft(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetJustificationToRight(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetLineSpacing(nint self, double _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetOpacity(nint self, double _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetShadowOffset_int_int(nint self, int _arg1, int _arg2);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetShadowOffset_intConstArray2(nint self, int* _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetVerticalJustificationToBottom(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetVerticalJustificationToCentered(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_SetVerticalJustificationToTop(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_ShadowOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_ShadowOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkTextProperty_ShallowCopy(nint self, nint tprop);
    #endregion
}
