// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkViewport : vtkObject
{
    protected vtkViewport(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkViewport WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkViewport Register(vtkViewport sourceObject)
    {
        var target = new vtkViewport(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
