// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkViewport : vtkObject
{
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_AddViewProp(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkViewport_GetViewProps(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    [return:MarshalAs(UnmanagedType.U4)]
    private static extern bool vtkViewport_HasViewProp(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_RemoveViewProp(nint self, nint _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_RemoveAllViewProps(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkViewport_GetActors2D(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_SetBackground(nint self, double _arg1, double _arg2, double _arg3);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double* vtkViewport_GetBackground(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_SetBackground2(nint self, double _arg1, double _arg2, double _arg3);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double* vtkViewport_GetBackground2(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_GradientBackgroundOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_GradientBackgroundOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_DisplayToView(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_ViewToDisplay(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_WorldToView(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_ViewToWorld(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_DisplayToWorld(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_WorldToDisplay(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_GradientEnvironmentalBGOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkViewport_GradientEnvironmentalBGOff(nint self);

    protected vtkViewport(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkViewport WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkViewport Register(vtkViewport sourceObject)
    {
        var target = new vtkViewport(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new void AddViewProp(vtkProp _arg1)
    {
        vtkViewport_AddViewProp(this.NativePointer, _arg1.NativePointer);
    }
    
    public new bool HasViewProp(vtkProp _arg1)
    {
        return vtkViewport_HasViewProp(this.NativePointer, _arg1.NativePointer);
    }

    public new void RemoveViewProp(vtkProp _arg1)
    {
        vtkViewport_RemoveViewProp(this.NativePointer, _arg1.NativePointer);
    }

    public new void RemoveAllViewProps()
    {
        vtkViewport_RemoveAllViewProps(this.NativePointer);
    }
    
    public new void SetBackground(double _arg1, double _arg2, double _arg3)
    {
        vtkViewport_SetBackground(this.NativePointer, _arg1, _arg2, _arg3);
    }

    internal new double* GetBackground_Internal()
    {
        return vtkViewport_GetBackground(this.NativePointer);
    }

    public new void SetBackground2(double _arg1, double _arg2, double _arg3)
    {
        vtkViewport_SetBackground2(this.NativePointer, _arg1, _arg2, _arg3);
    }

    internal new double* GetBackground2_Internal()
    {
        return vtkViewport_GetBackground2(this.NativePointer);
    }

    public new void GradientBackgroundOn()
    {
        vtkViewport_GradientBackgroundOn(this.NativePointer);
    }

    public new void GradientBackgroundOff()
    {
        vtkViewport_GradientBackgroundOff(this.NativePointer);
    }

    public new void DisplayToView()
    {
        vtkViewport_DisplayToView(this.NativePointer);
    }

    public new void ViewToDisplay()
    {
        vtkViewport_ViewToDisplay(this.NativePointer);
    }

    public new void WorldToView()
    {
        vtkViewport_WorldToView(this.NativePointer);
    }

    public new void ViewToWorld()
    {
        vtkViewport_ViewToWorld(this.NativePointer);
    }

    public new void DisplayToWorld()
    {
        vtkViewport_DisplayToWorld(this.NativePointer);
    }

    public new void WorldToDisplay()
    {
        vtkViewport_WorldToDisplay(this.NativePointer);
    }

    public new void GradientEnvironmentalBGOn()
    {
        vtkViewport_GradientEnvironmentalBGOn(this.NativePointer);
    }

    public new void GradientEnvironmentalBGOff()
    {
        vtkViewport_GradientEnvironmentalBGOff(this.NativePointer);
    }
}
