// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkWindowToImageFilter : vtkAlgorithm
{
    protected vtkWindowToImageFilter(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkWindowToImageFilter New() => new(vtkWindowToImageFilter_New(), ownsReference: true);
    public new static vtkWindowToImageFilter WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkWindowToImageFilter Register(vtkWindowToImageFilter sourceObject)
    {
        var target = new vtkWindowToImageFilter(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkWindowToImageFilter_New();
    #endregion
}
