using System.Text;
using VtkSharp.Generator.Core.Configuration;
using VtkSharp.Generator.Core.Whitelist;

namespace VtkSharp.Generator.Core.Generation;

public sealed class CMakeModulesEmitter
{
    public string Emit(
        NativeModuleLayout layout,
        IReadOnlyList<WhitelistDocument> documents,
        IReadOnlySet<string>? manuallyBoundClasses = null)
    {
        var targetModules = layout.Targets.ToDictionary(
            target => target.Name,
            target => target.Modules.Select(ToComponent).Order(StringComparer.Ordinal).ToArray(),
            StringComparer.OrdinalIgnoreCase);
        var targetAutoinitModules = layout.Targets.ToDictionary(
            target => target.Name,
            target => target.Modules.Concat(target.InitializationProviders).Distinct(StringComparer.Ordinal)
                .Select(ToComponent).Order(StringComparer.Ordinal).ToArray(),
            StringComparer.OrdinalIgnoreCase);
        var allComponents = targetModules.Values.SelectMany(static modules => modules)
            .Concat(targetAutoinitModules.Values.SelectMany(static modules => modules))
            .Select(ToComponent).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
        var sourcesByModule = documents.ToDictionary(
            document => document.Module,
            document => document.Classes
                .Where(item => manuallyBoundClasses?.Contains(item.Name) is not true)
                .Select(item => $"src/{document.Module}/{item.Name}_export_gen.cpp")
                .Order(StringComparer.Ordinal).ToArray(),
            StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("# This file is generated by VtkSharp.Generator. Do not edit manually.");
        AppendSet(sb, "VTKSHARP_VTK_COMPONENTS", allComponents);
        AppendSet(sb, "VTKSHARP_NATIVE_TARGETS", layout.Targets.Select(static target => target.Name));

        foreach (var target in layout.Targets)
        {
            var targetComponents = targetModules[target.Name];
            var targetSources = target.Modules.SelectMany(module => sourcesByModule[module])
                .Concat(layout.ManualSourcesByTarget.TryGetValue(target.Name, out var manualSources)
                    ? manualSources.Select(source => $"src/{source}")
                    : [])
                .Order(StringComparer.Ordinal).ToArray();
            AppendSet(sb, $"VTKSHARP_NATIVE_TARGET_{target.Key}_MODULES", targetComponents);
            AppendSet(sb, $"VTKSHARP_NATIVE_TARGET_{target.Key}_AUTOINIT_MODULES", targetAutoinitModules[target.Name]);
            AppendSet(sb, $"VTKSHARP_NATIVE_TARGET_{target.Key}_SOURCES", targetSources);
        }

        return sb.ToString().TrimEnd('\r', '\n') + Environment.NewLine;
    }

    private static string ToComponent(string module)
        => module.StartsWith("vtk", StringComparison.Ordinal) ? module[3..] : module;

    private static void AppendSet(StringBuilder sb, string variable, IEnumerable<string> values)
    {
        sb.AppendLine($"set({variable}");
        foreach (var value in values.Order(StringComparer.Ordinal))
            sb.AppendLine($"  {value}");
        sb.AppendLine(")");
        sb.AppendLine();
    }
}
