// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// place a border around a 2D rectangular region
/// </summary>
/// <remarks>
/// <para>
/// This class is a superclass for 2D widgets that may require a rectangular
/// border. Besides drawing a border, the widget provides methods for resizing
/// and moving the rectangular region (and associated border). The widget
/// provides methods and internal data members so that subclasses can take
/// advantage of this widgets capabilities, requiring only that the subclass
/// defines a "representation", i.e., some combination of props or actors
/// that can be managed in the 2D rectangular region.
/// </para>
/// <para>
/// The class defines basic positioning functionality, including the ability
/// to size the widget with locked x/y proportions. The area within the border
/// may be made "selectable" as well, meaning that a selection event interior
/// to the widget invokes a virtual SelectRegion() method, which can be used
/// to pick objects or otherwise manipulate data interior to the widget.
/// </para>
/// <para>
/// @par Event Bindings:
/// By default, the widget responds to the following VTK events (i.e., it
/// watches the vtkRenderWindowInteractor for these events):
/// &lt;pre&gt;
/// On the boundary of the widget:
/// LeftButtonPressEvent - select boundary
/// LeftButtonReleaseEvent - deselect boundary
/// MouseMoveEvent - move/resize widget depending on which portion of the
/// boundary was selected.
/// On the interior of the widget:
/// LeftButtonPressEvent - invoke SelectButton() callback (if the ivar
/// Selectable is on)
/// Anywhere on the widget:
/// MiddleButtonPressEvent - move the widget
/// &lt;/pre&gt;
/// </para>
/// <para>
/// @par Event Bindings:
/// Note that the event bindings described above can be changed using this
/// class's vtkWidgetEventTranslator. This class translates VTK events
/// into the vtkBorderWidget's widget events:
/// &lt;pre&gt;
/// vtkWidgetEvent::Select -- some part of the widget has been selected
/// vtkWidgetEvent::EndSelect -- the selection process has completed
/// vtkWidgetEvent::Translate -- the widget is to be translated
/// vtkWidgetEvent::Move -- a request for slider motion has been invoked
/// &lt;/pre&gt;
/// </para>
/// <para>
/// @par Event Bindings:
/// In turn, when these widget events are processed, this widget invokes the
/// following VTK events on itself (which observers can listen for):
/// &lt;pre&gt;
/// vtkCommand::StartInteractionEvent (on vtkWidgetEvent::Select)
/// vtkCommand::EndInteractionEvent (on vtkWidgetEvent::EndSelect)
/// vtkCommand::InteractionEvent (on vtkWidgetEvent::Move)
/// &lt;/pre&gt;
/// </para>
/// <para>
/// @sa
/// vtkInteractorObserver vtkCameraInterpolator
/// </para>
/// </remarks>
public unsafe partial class vtkBorderWidget : vtkAbstractWidget
{
    protected vtkBorderWidget(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Method to instantiate class.
    /// </summary>
    public new static vtkBorderWidget New() => new(vtkBorderWidget_New(), ownsReference: true);
    public new static vtkBorderWidget FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkBorderWidget TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkBorderWidget Register(vtkBorderWidget sourceObject)
    {
        var target = new vtkBorderWidget(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Create the default widget representation if one is not set.
    /// </summary>
    public new void CreateDefaultRepresentation()
    {
        vtkBorderWidget_CreateDefaultRepresentation(this.NativePointer);
    }

    /// <summary>
    /// Return the representation as a vtkBorderRepresentation.
    /// </summary>
    public new vtkBorderRepresentation GetBorderRepresentation()
    {
        return vtkBorderRepresentation.FromBorrowedPointer(vtkBorderWidget_GetBorderRepresentation(this.NativePointer));
    }

    /// <summary>
    /// Indicate whether the boundary of the widget can be resized.
    /// If not, the cursor will not change to "resize" type when mouse
    /// over the boundary.
    /// </summary>
    public new bool GetResizable()
    {
        return vtkBorderWidget_GetResizable(this.NativePointer) != 0;
    }

    /// <summary>
    /// Indicate whether the interior region of the widget can be selected or
    /// not. If not, then events (such as left mouse down) allow the user to
    /// "move" the widget, and no selection is possible. Otherwise the
    /// SelectRegion() method is invoked.
    /// </summary>
    public new bool GetSelectable()
    {
        return vtkBorderWidget_GetSelectable(this.NativePointer) != 0;
    }

    /// <summary>
    /// Indicate whether the boundary of the widget can be resized.
    /// If not, the cursor will not change to "resize" type when mouse
    /// over the boundary.
    /// </summary>
    public new void ResizableOff()
    {
        vtkBorderWidget_ResizableOff(this.NativePointer);
    }

    /// <summary>
    /// Indicate whether the boundary of the widget can be resized.
    /// If not, the cursor will not change to "resize" type when mouse
    /// over the boundary.
    /// </summary>
    public new void ResizableOn()
    {
        vtkBorderWidget_ResizableOn(this.NativePointer);
    }

    /// <summary>
    /// Indicate whether the interior region of the widget can be selected or
    /// not. If not, then events (such as left mouse down) allow the user to
    /// "move" the widget, and no selection is possible. Otherwise the
    /// SelectRegion() method is invoked.
    /// </summary>
    public new void SelectableOff()
    {
        vtkBorderWidget_SelectableOff(this.NativePointer);
    }

    /// <summary>
    /// Indicate whether the interior region of the widget can be selected or
    /// not. If not, then events (such as left mouse down) allow the user to
    /// "move" the widget, and no selection is possible. Otherwise the
    /// SelectRegion() method is invoked.
    /// </summary>
    public new void SelectableOn()
    {
        vtkBorderWidget_SelectableOn(this.NativePointer);
    }

    /// <summary>
    /// Specify an instance of vtkWidgetRepresentation used to represent this
    /// widget in the scene. Note that the representation is a subclass of vtkProp
    /// so it can be added to the renderer independent of the widget.
    /// </summary>
    public new void SetRepresentation(vtkBorderRepresentation r)
    {
        vtkBorderWidget_SetRepresentation(this.NativePointer, r.NativePointer);
    }

    /// <summary>
    /// Indicate whether the boundary of the widget can be resized.
    /// If not, the cursor will not change to "resize" type when mouse
    /// over the boundary.
    /// </summary>
    public new void SetResizable(bool _arg)
    {
        vtkBorderWidget_SetResizable(this.NativePointer, _arg ? 1 : 0);
    }

    /// <summary>
    /// Indicate whether the interior region of the widget can be selected or
    /// not. If not, then events (such as left mouse down) allow the user to
    /// "move" the widget, and no selection is possible. Otherwise the
    /// SelectRegion() method is invoked.
    /// </summary>
    public new void SetSelectable(bool _arg)
    {
        vtkBorderWidget_SetSelectable(this.NativePointer, _arg ? 1 : 0);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkBorderWidget_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkBorderWidget_CreateDefaultRepresentation(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkBorderWidget_GetBorderRepresentation(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkBorderWidget_GetResizable(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkBorderWidget_GetSelectable(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkBorderWidget_ResizableOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkBorderWidget_ResizableOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkBorderWidget_SelectableOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkBorderWidget_SelectableOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkBorderWidget_SetRepresentation(nint self, nint r);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkBorderWidget_SetResizable(nint self, int _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkBorderWidget_SetSelectable(nint self, int _arg);
    #endregion
}
