// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// 2D widget for manipulating a scalar bar
/// </summary>
/// <remarks>
/// <para>
/// This class provides support for interactively manipulating the position,
/// size, and orientation of a scalar bar. It listens to Left mouse events and
/// mouse movement. It also listens to Right mouse events and notifies any
/// observers of Right mouse events on this object when they occur.
/// It will change the cursor shape based on its location. If
/// the cursor is over an edge of the scalar bar it will change the cursor
/// shape to a resize edge shape. If the position of a scalar bar is moved to
/// be close to the center of one of the four edges of the viewport, then the
/// scalar bar will change its orientation to align with that edge. This
/// orientation is sticky in that it will stay that orientation until the
/// position is moved close to another edge.
/// </para>
/// <para>
/// See also: vtkInteractorObserver
/// </para>
/// </remarks>
public unsafe partial class vtkScalarBarWidget : vtkBorderWidget
{
    protected vtkScalarBarWidget(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkScalarBarWidget New() => new(vtkScalarBarWidget_New(), ownsReference: true);
    public new static vtkScalarBarWidget FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkScalarBarWidget TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkScalarBarWidget Register(vtkScalarBarWidget sourceObject)
    {
        var target = new vtkScalarBarWidget(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Create the default widget representation if one is not set.
    /// </summary>
    public new void CreateDefaultRepresentation()
    {
        vtkScalarBarWidget_CreateDefaultRepresentation(this.NativePointer);
    }

    /// <summary>
    /// Can the widget be moved. On by default. If off, the widget cannot be moved
    /// around.
    /// </summary>
    /// <remarks>
    /// TODO: This functionality should probably be moved to the superclass.
    /// </remarks>
    public new bool GetRepositionable()
    {
        return vtkScalarBarWidget_GetRepositionable(this.NativePointer) != 0;
    }

    /// <summary>
    /// Get the ScalarBar used by this Widget. One is created automatically.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkScalarBarActor GetScalarBarActor()
    {
        return vtkScalarBarActor.FromBorrowedPointer(vtkScalarBarWidget_GetScalarBarActor(this.NativePointer));
    }

    /// <summary>
    /// Return the representation as a vtkScalarBarRepresentation.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkScalarBarRepresentation GetScalarBarRepresentation()
    {
        return vtkScalarBarRepresentation.FromBorrowedPointer(vtkScalarBarWidget_GetScalarBarRepresentation(this.NativePointer));
    }

    /// <summary>
    /// Can the widget be moved. On by default. If off, the widget cannot be moved
    /// around.
    /// </summary>
    /// <remarks>
    /// TODO: This functionality should probably be moved to the superclass.
    /// </remarks>
    public new void RepositionableOff()
    {
        vtkScalarBarWidget_RepositionableOff(this.NativePointer);
    }

    /// <summary>
    /// Can the widget be moved. On by default. If off, the widget cannot be moved
    /// around.
    /// </summary>
    /// <remarks>
    /// TODO: This functionality should probably be moved to the superclass.
    /// </remarks>
    public new void RepositionableOn()
    {
        vtkScalarBarWidget_RepositionableOn(this.NativePointer);
    }

    /// <summary>
    /// Can the widget be moved. On by default. If off, the widget cannot be moved
    /// around.
    /// </summary>
    /// <remarks>
    /// TODO: This functionality should probably be moved to the superclass.
    /// </remarks>
    public new void SetRepositionable(bool _arg)
    {
        vtkScalarBarWidget_SetRepositionable(this.NativePointer, _arg ? 1 : 0);
    }

    /// <summary>
    /// Specify an instance of vtkWidgetRepresentation used to represent this
    /// widget in the scene. Note that the representation is a subclass of vtkProp
    /// so it can be added to the renderer independent of the widget.
    /// </summary>
    public new void SetRepresentation(vtkScalarBarRepresentation rep)
    {
        vtkScalarBarWidget_SetRepresentation(this.NativePointer, rep.NativePointer);
    }

    /// <summary>
    /// Get the ScalarBar used by this Widget. One is created automatically.
    /// </summary>
    public new void SetScalarBarActor(vtkScalarBarActor actor)
    {
        vtkScalarBarWidget_SetScalarBarActor(this.NativePointer, actor.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkScalarBarWidget_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkScalarBarWidget_CreateDefaultRepresentation(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkScalarBarWidget_GetRepositionable(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkScalarBarWidget_GetScalarBarActor(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkScalarBarWidget_GetScalarBarRepresentation(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkScalarBarWidget_RepositionableOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkScalarBarWidget_RepositionableOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkScalarBarWidget_SetRepositionable(nint self, int _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkScalarBarWidget_SetRepresentation(nint self, nint rep);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkScalarBarWidget_SetScalarBarActor(nint self, nint actor);
    #endregion
}
