// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// abstract class defines interface between the widget and widget representation classes
/// </summary>
/// <remarks>
/// <para>
/// This class is used to define the API for, and partially implement, a
/// representation for different types of widgets. Note that the widget
/// representation (i.e., subclasses of vtkWidgetRepresentation) are a type of
/// vtkProp; meaning that they can be associated with a vtkRenderer end
/// embedded in a scene like any other vtkActor. However,
/// vtkWidgetRepresentation also defines an API that enables it to be paired
/// with a subclass vtkAbstractWidget, meaning that it can be driven by a
/// widget, serving to represent the widget as the widget responds to
/// registered events.
/// </para>
/// <para>
/// The API defined here should be regarded as a guideline for implementing
/// widgets and widget representations. Widget behavior is complex, as is the
/// way the representation responds to the registered widget events, so the API
/// may vary from widget to widget to reflect this complexity.
/// </para>
/// <para>
/// Clients of VTK, like ParaView, need a uniform way to set colors on widgets.
/// Most widgets have standard color setters - new widgets should follow this pattern.
/// The intended use of these colors is as follows:
/// | Color       | Description |
/// | ----------- | ----------- |
/// | `HandleColor`      | Widget handles that are available to interact with via click+drag. | |
/// `InteractionColor` | Widget handles the user is interacting with (via a click+drag) or hovering
/// over.     | | `ForegroundColor`  | Widget elements meant to contrast with the background and
/// which are not interactive. |
/// </para>
/// <para>
/// When hovering, the `InteractionColor` can also be used to show which parts
/// of the widget will change if this handle is dragged. For instance, using the
/// `vtkDisplaySizedImplicitPlaneRepresentation`, hovering the axis also displays
/// the plane disc in the `InteractionColor`, to show it will change when the
/// axis is rotated.
/// </para>
/// <para>
/// Warning:
/// The separation of the widget event handling and representation enables
/// users and developers to create new appearances for the widget. It also
/// facilitates parallel processing, where the client application handles
/// events, and remote representations of the widget are slaves to the
/// client (and do not handle events).
/// </para>
/// </remarks>
public unsafe partial class vtkWidgetRepresentation : vtkProp
{
    protected vtkWidgetRepresentation(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkWidgetRepresentation FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkWidgetRepresentation TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkWidgetRepresentation Register(vtkWidgetRepresentation sourceObject)
    {
        var target = new vtkWidgetRepresentation(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Subclasses of vtkWidgetRepresentation must implement these methods. This is
    /// considered the minimum API for a widget representation.
    /// &lt;pre&gt;
    /// SetRenderer() - the renderer in which the representations draws itself.
    /// Typically the renderer is set by the associated widget.
    /// Use the widget's SetCurrentRenderer() method in most cases;
    /// otherwise there is a risk of inconsistent behavior as events
    /// and drawing may be performed in different viewports.
    /// BuildRepresentation() - update the geometry of the widget based on its
    /// current state.
    /// &lt;/pre&gt;
    /// WARNING: The renderer is NOT reference counted by the representation,
    /// in order to avoid reference loops.  Be sure that the representation
    /// lifetime does not extend beyond the renderer lifetime.
    /// </summary>
    public new void BuildRepresentation()
    {
        vtkWidgetRepresentation_BuildRepresentation(this.NativePointer);
    }

    public new int GetInteractionState()
    {
        return vtkWidgetRepresentation_GetInteractionState(this.NativePointer);
    }

    /// <summary>
    /// Some subclasses use this data member to keep track of whether to render
    /// or not (i.e., to minimize the total number of renders).
    /// </summary>
    public new bool GetNeedToRender()
    {
        return vtkWidgetRepresentation_GetNeedToRender(this.NativePointer) != 0;
    }

    /// <summary>
    /// Set/Get a factor representing the scaling of the widget upon placement
    /// (via the PlaceWidget() method). Normally the widget is placed so that
    /// it just fits within the bounding box defined in PlaceWidget(bounds).
    /// The PlaceFactor will make the widget larger (PlaceFactor &gt; 1) or smaller
    /// (PlaceFactor &lt; 1). By default, PlaceFactor is set to 0.5.
    /// </summary>
    public new double GetPlaceFactor()
    {
        return vtkWidgetRepresentation_GetPlaceFactor(this.NativePointer);
    }

    /// <summary>
    /// Subclasses of vtkWidgetRepresentation must implement these methods. This is
    /// considered the minimum API for a widget representation.
    /// &lt;pre&gt;
    /// SetRenderer() - the renderer in which the representations draws itself.
    /// Typically the renderer is set by the associated widget.
    /// Use the widget's SetCurrentRenderer() method in most cases;
    /// otherwise there is a risk of inconsistent behavior as events
    /// and drawing may be performed in different viewports.
    /// BuildRepresentation() - update the geometry of the widget based on its
    /// current state.
    /// &lt;/pre&gt;
    /// WARNING: The renderer is NOT reference counted by the representation,
    /// in order to avoid reference loops.  Be sure that the representation
    /// lifetime does not extend beyond the renderer lifetime.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkRenderer GetRenderer()
    {
        return vtkRenderer.FromBorrowedPointer(vtkWidgetRepresentation_GetRenderer(this.NativePointer));
    }

    /// <summary>
    /// Some subclasses use this data member to keep track of whether to render
    /// or not (i.e., to minimize the total number of renders).
    /// </summary>
    public new void NeedToRenderOff()
    {
        vtkWidgetRepresentation_NeedToRenderOff(this.NativePointer);
    }

    /// <summary>
    /// Some subclasses use this data member to keep track of whether to render
    /// or not (i.e., to minimize the total number of renders).
    /// </summary>
    public new void NeedToRenderOn()
    {
        vtkWidgetRepresentation_NeedToRenderOn(this.NativePointer);
    }

    /// <summary>
    /// The following is a suggested API for widget representations. These methods
    /// define the communication between the widget and its representation. These
    /// methods are only suggestions because widgets take on so many different
    /// forms that a universal API is not deemed practical. However, these methods
    /// should be implemented when possible to ensure that the VTK widget hierarchy
    /// remains self-consistent.
    /// &lt;pre&gt;
    /// PlaceWidget() - given a bounding box (xmin,xmax,ymin,ymax,zmin,zmax), place
    /// the widget inside of it. The current orientation of the widget
    /// is preserved, only scaling and translation is performed.
    /// StartWidgetInteraction() - generally corresponds to a initial event (e.g.,
    /// mouse down) that starts the interaction process
    /// with the widget.
    /// WidgetInteraction() - invoked when an event causes the widget to change
    /// appearance.
    /// EndWidgetInteraction() - generally corresponds to a final event (e.g., mouse up)
    /// and completes the interaction sequence.
    /// ComputeInteractionState() - given (X,Y) display coordinates in a renderer, with a
    /// possible flag that modifies the computation,
    /// what is the state of the widget?
    /// GetInteractionState() - return the current state of the widget. Note that the
    /// value of "0" typically refers to "outside". The
    /// interaction state is strictly a function of the
    /// representation, and the widget/represent must agree
    /// on what they mean.
    /// Highlight() - turn on or off any highlights associated with the widget.
    /// Highlights are generally turned on when the widget is selected.
    /// &lt;/pre&gt;
    /// Note that subclasses may ignore some of these methods and implement their own
    /// depending on the specifics of the widget.
    /// </summary>
    /// <param name="_arg1">
    /// Buffer length: 6 elements.
    /// </param>
    public new void PlaceWidget(Span<double> _arg1)
    {
        fixed (double* _arg1Ptr = _arg1)
        {
            vtkWidgetRepresentation_PlaceWidget(this.NativePointer, _arg1Ptr);
        }
    }

    /// <summary>
    /// Some subclasses use this data member to keep track of whether to render
    /// or not (i.e., to minimize the total number of renders).
    /// </summary>
    public new void SetNeedToRender(bool _arg)
    {
        vtkWidgetRepresentation_SetNeedToRender(this.NativePointer, _arg ? 1 : 0);
    }

    /// <summary>
    /// Set/Get a factor representing the scaling of the widget upon placement
    /// (via the PlaceWidget() method). Normally the widget is placed so that
    /// it just fits within the bounding box defined in PlaceWidget(bounds).
    /// The PlaceFactor will make the widget larger (PlaceFactor &gt; 1) or smaller
    /// (PlaceFactor &lt; 1). By default, PlaceFactor is set to 0.5.
    /// </summary>
    public new void SetPlaceFactor(double _arg)
    {
        vtkWidgetRepresentation_SetPlaceFactor(this.NativePointer, _arg);
    }

    /// <summary>
    /// Subclasses of vtkWidgetRepresentation must implement these methods. This is
    /// considered the minimum API for a widget representation.
    /// &lt;pre&gt;
    /// SetRenderer() - the renderer in which the representations draws itself.
    /// Typically the renderer is set by the associated widget.
    /// Use the widget's SetCurrentRenderer() method in most cases;
    /// otherwise there is a risk of inconsistent behavior as events
    /// and drawing may be performed in different viewports.
    /// BuildRepresentation() - update the geometry of the widget based on its
    /// current state.
    /// &lt;/pre&gt;
    /// WARNING: The renderer is NOT reference counted by the representation,
    /// in order to avoid reference loops.  Be sure that the representation
    /// lifetime does not extend beyond the renderer lifetime.
    /// </summary>
    public new void SetRenderer(vtkRenderer ren)
    {
        vtkWidgetRepresentation_SetRenderer(this.NativePointer, ren.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWidgetRepresentation_BuildRepresentation(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkWidgetRepresentation_GetInteractionState(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkWidgetRepresentation_GetNeedToRender(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double vtkWidgetRepresentation_GetPlaceFactor(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkWidgetRepresentation_GetRenderer(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWidgetRepresentation_NeedToRenderOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWidgetRepresentation_NeedToRenderOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWidgetRepresentation_PlaceWidget(nint self, double* _arg1);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWidgetRepresentation_SetNeedToRender(nint self, int _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWidgetRepresentation_SetPlaceFactor(nint self, double _arg);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWidgetRepresentation_SetRenderer(nint self, nint ren);
    #endregion
}
