// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkMinimalStandardRandomSequence.h>

VTKSHARP_API vtkMinimalStandardRandomSequence* vtkMinimalStandardRandomSequence_New() { return vtkMinimalStandardRandomSequence::New(); }

VTKSHARP_API double vtkMinimalStandardRandomSequence_GetValue(vtkMinimalStandardRandomSequence* self) { return self->GetValue(); }

VTKSHARP_API void vtkMinimalStandardRandomSequence_Next(vtkMinimalStandardRandomSequence* self) { self->Next(); }

VTKSHARP_API void vtkMinimalStandardRandomSequence_SetSeed(vtkMinimalStandardRandomSequence* self, int value) { self->SetSeed(value); }
