// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// interpolate over point cloud using various kernels
/// </summary>
/// <remarks>
/// <para>
///
/// vtkPointInterpolator probes a point cloud Pc (the filter Source) with a
/// set of points P (the filter Input), interpolating the data values from Pc
/// onto P. Note however that the descriptive phrase "point cloud" is a
/// misnomer: Pc can be represented by any vtkDataSet type, with the points of
/// the dataset forming Pc. Similarly, the output P can also be represented by
/// any vtkDataSet type; and the topology/geometry structure of P is passed
/// through to the output along with the newly interpolated arrays.
/// </para>
/// <para>
/// A key input to this filter is the specification of the interpolation
/// kernel, and the parameters which control the associated interpolation
/// process. Interpolation kernels include Voronoi, Gaussian, Shepard, and SPH
/// (smoothed particle hydrodynamics), with additional kernels to be added in
/// the future.
/// </para>
/// <para>
/// An overview of the algorithm is as follows. For each p from P, Np "close"
/// points to p are found. (The meaning of what is "close" can be specified as
/// either the N closest points, or all points within a given radius Rp. This
/// depends on how the kernel is defined.) Once the Np close points are found,
/// then the interpolation kernel is applied to compute new data values
/// located on p. Note that for reasonable performance, finding the Np closest
/// points requires a point locator. The locator may be specified as input to
/// the algorithm. (By default, a vtkStaticPointLocator is used because
/// generally it is much faster to build, delete, and search with. However,
/// with highly non-uniform point distributions, octree- or kd-tree based
/// locators may perform better.)
/// </para>
/// <para>
/// Warning:
/// This class has been threaded with vtkSMPTools. Using TBB or other
/// non-sequential type (set in the CMake variable
/// VTK_SMP_IMPLEMENTATION_TYPE) may improve performance significantly.
/// </para>
/// <para>
/// Warning:
/// For widely spaced points in Pc, or when p is located outside the bounding
/// region of Pc, the interpolation may behave badly and the interpolation
/// process will adapt as necessary to produce output. For example, if the N
/// closest points within R are requested to interpolate p, if N=0 then the
/// interpolation will switch to a different strategy (which can be controlled
/// as in the NullPointsStrategy).
/// </para>
/// <para>
/// See also: vtkPointInterpolator2D vtkProbeFilter vtkGaussianSplatter
/// vtkCheckerboardSplatter vtkShepardMethod vtkVoronoiKernel vtkShepardKernel
/// vtkGaussianKernel vtkSPHKernel
/// </para>
/// </remarks>
public unsafe partial class vtkPointInterpolator : vtkDataSetAlgorithm
{
    protected vtkPointInterpolator(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Standard methods for instantiating, obtaining type information, and
    /// printing.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkPointInterpolator New() => new(vtkPointInterpolator_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkPointInterpolator FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkPointInterpolator TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkPointInterpolator Register(vtkPointInterpolator sourceObject)
    {
        var target = new vtkPointInterpolator(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Specify an interpolation kernel. By default a vtkLinearKernel is used
    /// (i.e., linear combination of closest points). The interpolation kernel
    /// changes the basis of the interpolation.
    /// </summary>
    public new void SetKernel(vtkInterpolationKernel kernel)
    {
        vtkPointInterpolator_SetKernel(this.NativePointer, kernel.NativePointer);
    }

    /// <summary>
    /// Specify the dataset Pc that will be probed by the input points P.  The
    /// Input P defines the dataset structure (the points and cells) for the
    /// output, while the Source Pc is probed (interpolated) to generate the
    /// scalars, vectors, etc. for the output points based on the point
    /// locations.
    /// </summary>
    public new void SetSourceData(vtkDataObject source)
    {
        vtkPointInterpolator_SetSourceData(this.NativePointer, source.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPointInterpolator_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPointInterpolator_SetKernel(nint self, nint kernel);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPointInterpolator_SetSourceData(nint self, nint source);
    #endregion
}
