// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Generate Enneper's surface.
/// </summary>
/// <remarks>
/// <para>
/// vtkParametricEnneper generates Enneper's surface.
/// Enneper's surface is a self-intersecting minimal surface
/// possessing constant negative Gaussian curvature
/// </para>
/// <para>
/// For further information about this surface, please consult the
/// technical description "Parametric surfaces" in http://www.vtk.org/publications
/// in the "VTK Technical Documents" section in the VTk.org web pages.
/// </para>
/// <para>
/// @par Thanks:
/// Andrew Maclean andrew.amaclean@gmail.com for creating and contributing the
/// class.
/// </para>
/// </remarks>
public unsafe partial class vtkParametricEnneper : vtkParametricFunction
{
    protected vtkParametricEnneper(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Construct Enneper's surface with the following parameters:
    /// MinimumU = -2, MaximumU = 2,
    /// MinimumV = -2, MaximumV = 2,
    /// JoinU = 0, JoinV = 0,
    /// TwistU = 0, TwistV = 0,
    /// ClockwiseOrdering = 0,
    /// DerivativesAvailable = 1
    /// </summary>
    public new static vtkParametricEnneper New() => new(vtkParametricEnneper_New(), ownsReference: true);
    public new static vtkParametricEnneper FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkParametricEnneper TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkParametricEnneper Register(vtkParametricEnneper sourceObject)
    {
        var target = new vtkParametricEnneper(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkParametricEnneper_New();
    #endregion
}
