// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkDoubleArray : vtkDataArray
{
    protected vtkDoubleArray(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkDoubleArray New() => new(vtkDoubleArray_New(), ownsReference: true);
    public new static vtkDoubleArray WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkDoubleArray Register(vtkDoubleArray sourceObject)
    {
        var target = new vtkDoubleArray(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkDoubleArray_New();
    #endregion
}
