// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkInformationVector : vtkObject
{
    protected vtkInformationVector(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkInformationVector New() => new(vtkInformationVector_New(), ownsReference: true);
    public new static vtkInformationVector WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkInformationVector Register(vtkInformationVector sourceObject)
    {
        var target = new vtkInformationVector(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInformationVector_New();
    #endregion
}
