// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkInformation : vtkObject
{
    protected vtkInformation(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkInformation New() => new(vtkInformation_New(), ownsReference: true);
    public new static vtkInformation WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkInformation Register(vtkInformation sourceObject)
    {
        var target = new vtkInformation(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInformation_New();
    #endregion
}
