// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkMinimalStandardRandomSequence : vtkRandomSequence
{
    protected vtkMinimalStandardRandomSequence(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkMinimalStandardRandomSequence New() => new(vtkMinimalStandardRandomSequence_New(), ownsReference: true);
    public new static vtkMinimalStandardRandomSequence WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkMinimalStandardRandomSequence Register(vtkMinimalStandardRandomSequence sourceObject)
    {
        var target = new vtkMinimalStandardRandomSequence(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new double GetValue()
    {
        return vtkMinimalStandardRandomSequence_GetValue(this.NativePointer);
    }

    public new void Next()
    {
        vtkMinimalStandardRandomSequence_Next(this.NativePointer);
    }

    public new void SetSeed(int value)
    {
        vtkMinimalStandardRandomSequence_SetSeed(this.NativePointer, value);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkMinimalStandardRandomSequence_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double vtkMinimalStandardRandomSequence_GetValue(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMinimalStandardRandomSequence_Next(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkMinimalStandardRandomSequence_SetSeed(nint self, int value);
    #endregion
}
