// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// represent and manipulate 3D points
/// </summary>
/// <remarks>
/// vtkPoints represents 3D points. The data model for vtkPoints is an
/// array of vx-vy-vz triplets accessible by (point or cell) id.
/// </remarks>
public unsafe partial class vtkPoints : vtkObject
{
    protected vtkPoints(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkPoints New() => new(vtkPoints_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkPoints FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkPoints TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkPoints Register(vtkPoints sourceObject)
    {
        var target = new vtkPoints(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Return number of points in array.
    /// </summary>
    public new long GetNumberOfPoints()
    {
        return vtkPoints_GetNumberOfPoints(this.NativePointer);
    }

    /// <summary>
    /// Copy point components into user provided array v[3] for specified
    /// id.
    /// </summary>
    /// <param name="id" />
    /// <param name="x">
    /// <para>
    /// Output parameter.
    /// </para>
    /// <para>
    /// Buffer length: 3 elements.
    /// </para>
    /// </param>
    public new void GetPoint(long id, Span<double> x)
    {
        fixed (double* xPtr = x)
        {
            vtkPoints_GetPoint(this.NativePointer, id, xPtr);
        }
    }

    /// <summary>
    /// Return object to instantiated state.
    /// </summary>
    public new void Initialize()
    {
        vtkPoints_Initialize(this.NativePointer);
    }

    /// <param name="x">
    /// Buffer length: 3 elements.
    /// </param>
    public new long InsertNextPoint(ReadOnlySpan<double> x)
    {
        fixed (double* xPtr = x)
        {
            return vtkPoints_InsertNextPoint_doubleConstArray3(this.NativePointer, xPtr);
        }
    }

    public new long InsertNextPoint(double x, double y, double z)
    {
        return vtkPoints_InsertNextPoint_double_double_double(this.NativePointer, x, y, z);
    }

    /// <summary>
    /// Insert point into next available slot. Returns id of slot.
    /// </summary>
    /// <param name="x">
    /// Buffer length: 3 elements.
    /// </param>
    public new long InsertNextPoint(ReadOnlySpan<float> x)
    {
        fixed (float* xPtr = x)
        {
            return vtkPoints_InsertNextPoint_floatConstArray3(this.NativePointer, xPtr);
        }
    }

    /// <summary>
    /// Insert point into object. Range checking performed and memory
    /// allocated as necessary.
    /// </summary>
    /// <param name="id" />
    /// <param name="x">
    /// Buffer length: 3 elements.
    /// </param>
    public new void InsertPoint(long id, ReadOnlySpan<double> x)
    {
        fixed (double* xPtr = x)
        {
            vtkPoints_InsertPoint_vtkIdType_doubleConstArray3(this.NativePointer, id, xPtr);
        }
    }

    /// <summary>
    /// Insert point into object. Range checking performed and memory
    /// allocated as necessary.
    /// </summary>
    public new void InsertPoint(long id, double x, double y, double z)
    {
        vtkPoints_InsertPoint_vtkIdType_double_double_double(this.NativePointer, id, x, y, z);
    }

    /// <summary>
    /// Insert point into object. Range checking performed and memory
    /// allocated as necessary.
    /// </summary>
    /// <param name="id" />
    /// <param name="x">
    /// Buffer length: 3 elements.
    /// </param>
    public new void InsertPoint(long id, ReadOnlySpan<float> x)
    {
        fixed (float* xPtr = x)
        {
            vtkPoints_InsertPoint_vtkIdType_floatConstArray3(this.NativePointer, id, xPtr);
        }
    }

    /// <summary>
    /// Update the modification time for this object and its Data.
    /// As this object acts as a shell around a DataArray and
    /// forwards Set methods it needs to forward Modified as well.
    /// </summary>
    public new void Modified()
    {
        vtkPoints_Modified(this.NativePointer);
    }

    /// <summary>
    /// Resize the internal array while conserving the data.  Returns 1 if
    /// resizing succeeded (including shrinking) and 0 (or throw std::bad_alloc
    /// based on VTK_DONT_THROW_BAD_ALLOC configuration) otherwise.
    /// </summary>
    public new bool Resize(long numPoints)
    {
        return vtkPoints_Resize(this.NativePointer, numPoints) != 0;
    }

    public new void SetDataTypeToBit()
    {
        vtkPoints_SetDataTypeToBit(this.NativePointer);
    }

    public new void SetDataTypeToChar()
    {
        vtkPoints_SetDataTypeToChar(this.NativePointer);
    }

    public new void SetDataTypeToDouble()
    {
        vtkPoints_SetDataTypeToDouble(this.NativePointer);
    }

    public new void SetDataTypeToFloat()
    {
        vtkPoints_SetDataTypeToFloat(this.NativePointer);
    }

    public new void SetDataTypeToInt()
    {
        vtkPoints_SetDataTypeToInt(this.NativePointer);
    }

    public new void SetDataTypeToLong()
    {
        vtkPoints_SetDataTypeToLong(this.NativePointer);
    }

    public new void SetDataTypeToShort()
    {
        vtkPoints_SetDataTypeToShort(this.NativePointer);
    }

    public new void SetDataTypeToUnsignedChar()
    {
        vtkPoints_SetDataTypeToUnsignedChar(this.NativePointer);
    }

    public new void SetDataTypeToUnsignedInt()
    {
        vtkPoints_SetDataTypeToUnsignedInt(this.NativePointer);
    }

    public new void SetDataTypeToUnsignedLong()
    {
        vtkPoints_SetDataTypeToUnsignedLong(this.NativePointer);
    }

    public new void SetDataTypeToUnsignedShort()
    {
        vtkPoints_SetDataTypeToUnsignedShort(this.NativePointer);
    }

    /// <summary>
    /// Specify the number of points for this object to hold. Does an
    /// allocation as well as setting the MaxId ivar. Used in conjunction with
    /// SetPoint() method for fast insertion.
    /// </summary>
    public new void SetNumberOfPoints(long numPoints)
    {
        vtkPoints_SetNumberOfPoints(this.NativePointer, numPoints);
    }

    /// <param name="id" />
    /// <param name="x">
    /// Buffer length: 3 elements.
    /// </param>
    public new void SetPoint(long id, ReadOnlySpan<double> x)
    {
        fixed (double* xPtr = x)
        {
            vtkPoints_SetPoint_vtkIdType_doubleConstArray3(this.NativePointer, id, xPtr);
        }
    }

    public new void SetPoint(long id, double x, double y, double z)
    {
        vtkPoints_SetPoint_vtkIdType_double_double_double(this.NativePointer, id, x, y, z);
    }

    /// <summary>
    /// Insert point into object. No range checking performed (fast!).
    /// Make sure you use SetNumberOfPoints() to allocate memory prior
    /// to using SetPoint(). You should call Modified() finally after
    /// changing points using this method as it will not do it itself.
    /// </summary>
    /// <param name="id" />
    /// <param name="x">
    /// Buffer length: 3 elements.
    /// </param>
    public new void SetPoint(long id, ReadOnlySpan<float> x)
    {
        fixed (float* xPtr = x)
        {
            vtkPoints_SetPoint_vtkIdType_floatConstArray3(this.NativePointer, id, xPtr);
        }
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPoints_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkPoints_GetNumberOfPoints(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_GetPoint(nint self, long id, double* x);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_Initialize(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkPoints_InsertNextPoint_doubleConstArray3(nint self, double* x);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkPoints_InsertNextPoint_double_double_double(nint self, double x, double y, double z);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkPoints_InsertNextPoint_floatConstArray3(nint self, float* x);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_InsertPoint_vtkIdType_doubleConstArray3(nint self, long id, double* x);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_InsertPoint_vtkIdType_double_double_double(nint self, long id, double x, double y, double z);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_InsertPoint_vtkIdType_floatConstArray3(nint self, long id, float* x);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_Modified(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkPoints_Resize(nint self, long numPoints);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToBit(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToChar(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToDouble(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToFloat(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToInt(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToLong(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToShort(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToUnsignedChar(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToUnsignedInt(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToUnsignedLong(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetDataTypeToUnsignedShort(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetNumberOfPoints(nint self, long numPoints);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetPoint_vtkIdType_doubleConstArray3(nint self, long id, double* x);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetPoint_vtkIdType_double_double_double(nint self, long id, double x, double y, double z);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkPoints_SetPoint_vtkIdType_floatConstArray3(nint self, long id, float* x);
    #endregion
}
