// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// dynamic, self-adjusting array of unsigned char
/// </summary>
/// <remarks>
/// vtkUnsignedCharArray is an array of values of type unsigned char.
/// It provides methods for insertion and retrieval of values and will
/// automatically resize itself to hold new data.
/// </remarks>
public unsafe partial class vtkUnsignedCharArray : vtkDataArray
{
    protected vtkUnsignedCharArray(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkUnsignedCharArray New() => new(vtkUnsignedCharArray_New(), ownsReference: true);
    public new static vtkUnsignedCharArray FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkUnsignedCharArray TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkUnsignedCharArray Register(vtkUnsignedCharArray sourceObject)
    {
        var target = new vtkUnsignedCharArray(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkUnsignedCharArray_New();
    #endregion
}
