// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// manipulate camera in scene with natural view up (e.g., terrain)
/// </summary>
/// <remarks>
/// <para>
/// vtkInteractorStyleTerrain is used to manipulate a camera which is viewing
/// a scene with a natural view up, e.g., terrain. The camera in such a
/// scene is manipulated by specifying azimuth (angle around the view
/// up vector) and elevation (the angle from the horizon).
/// </para>
/// <para>
/// The mouse binding for this class is as follows. Left mouse click followed
/// rotates the camera around the focal point using both elevation and azimuth
/// invocations on the camera. Left mouse motion in the horizontal direction
/// results in azimuth motion; left mouse motion in the vertical direction
/// results in elevation motion. Therefore, diagonal motion results in a
/// combination of azimuth and elevation. (If the shift key is held during
/// motion, then only one of elevation or azimuth is invoked, depending on the
/// whether the mouse motion is primarily horizontal or vertical.) Middle
/// mouse button pans the camera across the scene (again the shift key has a
/// similar effect on limiting the motion to the vertical or horizontal
/// direction. The right mouse is used to dolly (e.g., a type of zoom) towards
/// or away from the focal point.
/// </para>
/// <para>
/// The class also supports some keypress events. The "r" key resets the
/// camera.  The "e" key invokes the exit callback and by default exits the
/// program. The "f" key sets a new camera focal point and flys towards that
/// point. The "u" key invokes the user event. The "3" key toggles between
/// stereo and non-stero mode. The "l" key toggles on/off a latitude/longitude
/// markers that can be used to estimate/control position.
/// </para>
/// <para>
/// See also: vtkInteractorObserver vtkInteractorStyle vtk3DWidget
/// </para>
/// </remarks>
public unsafe partial class vtkInteractorStyleTerrain : vtkInteractorStyle
{
    protected vtkInteractorStyleTerrain(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Instantiate the object.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkInteractorStyleTerrain New() => new(vtkInteractorStyleTerrain_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkInteractorStyleTerrain FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkInteractorStyleTerrain TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkInteractorStyleTerrain Register(vtkInteractorStyleTerrain sourceObject)
    {
        var target = new vtkInteractorStyleTerrain(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new void Dolly()
    {
        vtkInteractorStyleTerrain_Dolly(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off the latitude/longitude lines.
    /// </summary>
    public new bool GetLatLongLines()
    {
        return vtkInteractorStyleTerrain_GetLatLongLines(this.NativePointer) != 0;
    }

    public new long GetNumberOfGenerationsFromBase(string type)
    {
        #if NET8_0_OR_GREATER
        return vtkInteractorStyleTerrain_GetNumberOfGenerationsFromBase(this.NativePointer, type);
        #else
        return vtkInteractorStyleTerrain_GetNumberOfGenerationsFromBase(this.NativePointer, VtkString.ToNullTerminatedUtf8(type));
        #endif
    }

    public new bool IsA(string type)
    {
        #if NET8_0_OR_GREATER
        return vtkInteractorStyleTerrain_IsA(this.NativePointer, type) != 0;
        #else
        return vtkInteractorStyleTerrain_IsA(this.NativePointer, VtkString.ToNullTerminatedUtf8(type)) != 0;
        #endif
    }

    /// <summary>
    /// Turn on/off the latitude/longitude lines.
    /// </summary>
    public new void LatLongLinesOff()
    {
        vtkInteractorStyleTerrain_LatLongLinesOff(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off the latitude/longitude lines.
    /// </summary>
    public new void LatLongLinesOn()
    {
        vtkInteractorStyleTerrain_LatLongLinesOn(this.NativePointer);
    }

    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkInteractorStyleTerrain NewInstance()
    {
        return vtkInteractorStyleTerrain.FromBorrowedPointer(vtkInteractorStyleTerrain_NewInstance(this.NativePointer));
    }

    /// <summary>
    /// Override the "fly-to" (f keypress) for images.
    /// </summary>
    public new void OnChar()
    {
        vtkInteractorStyleTerrain_OnChar(this.NativePointer);
    }

    /// <summary>
    /// Event bindings controlling the effects of pressing mouse buttons
    /// or moving the mouse.
    /// </summary>
    public new void OnLeftButtonDown()
    {
        vtkInteractorStyleTerrain_OnLeftButtonDown(this.NativePointer);
    }

    /// <summary>
    /// Event bindings controlling the effects of pressing mouse buttons
    /// or moving the mouse.
    /// </summary>
    public new void OnLeftButtonUp()
    {
        vtkInteractorStyleTerrain_OnLeftButtonUp(this.NativePointer);
    }

    /// <summary>
    /// Event bindings controlling the effects of pressing mouse buttons
    /// or moving the mouse.
    /// </summary>
    public new void OnMiddleButtonDown()
    {
        vtkInteractorStyleTerrain_OnMiddleButtonDown(this.NativePointer);
    }

    /// <summary>
    /// Event bindings controlling the effects of pressing mouse buttons
    /// or moving the mouse.
    /// </summary>
    public new void OnMiddleButtonUp()
    {
        vtkInteractorStyleTerrain_OnMiddleButtonUp(this.NativePointer);
    }

    /// <summary>
    /// Event bindings controlling the effects of pressing mouse buttons
    /// or moving the mouse.
    /// </summary>
    public new void OnMouseMove()
    {
        vtkInteractorStyleTerrain_OnMouseMove(this.NativePointer);
    }

    /// <summary>
    /// Event bindings controlling the effects of pressing mouse buttons
    /// or moving the mouse.
    /// </summary>
    public new void OnRightButtonDown()
    {
        vtkInteractorStyleTerrain_OnRightButtonDown(this.NativePointer);
    }

    /// <summary>
    /// Event bindings controlling the effects of pressing mouse buttons
    /// or moving the mouse.
    /// </summary>
    public new void OnRightButtonUp()
    {
        vtkInteractorStyleTerrain_OnRightButtonUp(this.NativePointer);
    }

    public new void Pan()
    {
        vtkInteractorStyleTerrain_Pan(this.NativePointer);
    }

    public new void Rotate()
    {
        vtkInteractorStyleTerrain_Rotate(this.NativePointer);
    }

    /// <summary>
    /// Turn on/off the latitude/longitude lines.
    /// </summary>
    public new void SetLatLongLines(bool _arg)
    {
        vtkInteractorStyleTerrain_SetLatLongLines(this.NativePointer, _arg ? 1 : 0);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInteractorStyleTerrain_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_Dolly(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkInteractorStyleTerrain_GetLatLongLines(nint self);

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial long vtkInteractorStyleTerrain_GetNumberOfGenerationsFromBase(nint self, string type);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkInteractorStyleTerrain_GetNumberOfGenerationsFromBase(nint self, byte[] type);
#endif

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial int vtkInteractorStyleTerrain_IsA(nint self, string type);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkInteractorStyleTerrain_IsA(nint self, byte[] type);
#endif

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_LatLongLinesOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_LatLongLinesOn(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInteractorStyleTerrain_NewInstance(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_OnChar(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_OnLeftButtonDown(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_OnLeftButtonUp(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_OnMiddleButtonDown(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_OnMiddleButtonUp(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_OnMouseMove(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_OnRightButtonDown(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_OnRightButtonUp(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_Pan(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_Rotate(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleTerrain_SetLatLongLines(nint self, int _arg);
    #endregion
}
