// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// interactive manipulation of the camera specialized for images
/// </summary>
/// <remarks>
/// <para>
/// vtkInteractorStyleImage allows the user to interactively manipulate
/// (rotate, pan, zoom etc.) the camera. vtkInteractorStyleImage is specially
/// designed to work with images that are being rendered with
/// vtkImageActor. Several events are overloaded from its superclass
/// vtkInteractorStyle, hence the mouse bindings are different. (The bindings
/// keep the camera's view plane normal perpendicular to the x-y plane.) In
/// summary the mouse events for 2D image interaction are as follows:
/// - Left Mouse button triggers window level events
/// - CTRL Left Mouse spins the camera around its view plane normal
/// - SHIFT Left Mouse pans the camera
/// - CTRL SHIFT Left Mouse dollys (a positional zoom) the camera
/// - Middle mouse button pans the camera
/// - Right mouse button dollys the camera.
/// - SHIFT Right Mouse triggers pick events
/// </para>
/// <para>
/// If SetInteractionModeToImageSlicing() is called, then some of the mouse
/// events are changed as follows:
/// - CTRL Left Mouse slices through the image
/// - SHIFT Middle Mouse slices through the image
/// - CTRL Right Mouse spins the camera
/// </para>
/// <para>
/// If SetInteractionModeToImage3D() is called, then some of the mouse
/// events are changed as follows:
/// - SHIFT Left Mouse rotates the camera for oblique slicing
/// - SHIFT Middle Mouse slices through the image
/// - CTRL Right Mouse also slices through the image
/// </para>
/// <para>
/// In all modes, the following key bindings are in effect:
/// - R Reset the Window/Level
/// - X Reset to a sagittal view
/// - Y Reset to a coronal view
/// - Z Reset to an axial view
/// </para>
/// <para>
/// Note that the renderer's actors are not moved; instead the camera is moved.
/// </para>
/// <para>
/// See also: vtkInteractorStyle vtkInteractorStyleTrackballActor
/// vtkInteractorStyleJoystickCamera vtkInteractorStyleJoystickActor
/// </para>
/// </remarks>
public unsafe partial class vtkInteractorStyleImage : vtkInteractorStyleTrackballCamera
{
    protected vtkInteractorStyleImage(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkInteractorStyleImage New() => new(vtkInteractorStyleImage_New(), ownsReference: true);
    public new static vtkInteractorStyleImage FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkInteractorStyleImage TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkInteractorStyleImage Register(vtkInteractorStyleImage sourceObject)
    {
        var target = new vtkInteractorStyleImage(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Set/Get current mode to 2D or 3D.  The default is 2D.  In 3D mode,
    /// it is possible to rotate the camera to view oblique slices.  In Slicing
    /// mode, it is possible to slice through the data, but not to generate oblique
    /// views by rotating the camera.
    /// </summary>
    public new void SetInteractionModeToImageSlicing()
    {
        vtkInteractorStyleImage_SetInteractionModeToImageSlicing(this.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInteractorStyleImage_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkInteractorStyleImage_SetInteractionModeToImageSlicing(nint self);
    #endregion
}
