// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// interactive manipulation of the camera
/// </summary>
/// <remarks>
/// <para>
///
/// vtkInteractorStyleJoystickCamera allows the user to move (rotate, pan,
/// etc.) the camera, the point of view for the scene.  The position of the
/// mouse relative to the center of the scene determines the speed at which
/// the camera moves, and the speed of the mouse movement determines the
/// acceleration of the camera, so the camera continues to move even if the
/// mouse if not moving.
/// For a 3-button mouse, the left button is for rotation, the right button
/// for zooming, the middle button for panning, and ctrl + left button for
/// spinning.  (With fewer mouse buttons, ctrl + shift + left button is
/// for zooming, and shift + left button is for panning.)
/// </para>
/// <para>
/// See also: vtkInteractorStyleJoystickActor vtkInteractorStyleTrackballCamera
/// vtkInteractorStyleTrackballActor
/// </para>
/// </remarks>
public unsafe partial class vtkInteractorStyleJoystickCamera : vtkInteractorStyle
{
    protected vtkInteractorStyleJoystickCamera(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkInteractorStyleJoystickCamera New() => new(vtkInteractorStyleJoystickCamera_New(), ownsReference: true);
    public new static vtkInteractorStyleJoystickCamera FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkInteractorStyleJoystickCamera TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkInteractorStyleJoystickCamera Register(vtkInteractorStyleJoystickCamera sourceObject)
    {
        var target = new vtkInteractorStyleJoystickCamera(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInteractorStyleJoystickCamera_New();
    #endregion
}
