// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkInteractorStyleRubberBandZoom : vtkInteractorStyle
{
    protected vtkInteractorStyleRubberBandZoom(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkInteractorStyleRubberBandZoom New() => new(vtkInteractorStyleRubberBandZoom_New(), ownsReference: true);
    public new static vtkInteractorStyleRubberBandZoom WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkInteractorStyleRubberBandZoom Register(vtkInteractorStyleRubberBandZoom sourceObject)
    {
        var target = new vtkInteractorStyleRubberBandZoom(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInteractorStyleRubberBandZoom_New();
    #endregion
}
