// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Like TrackBallCamera, but this can pick props underneath a rubber band selection
/// rectangle.
/// </summary>
/// <remarks>
/// <para>
///
/// This interactor style allows the user to draw a rectangle in the render
/// window by hitting 'r' and then using the left mouse button.
/// When the mouse button is released, the attached picker operates on the pixel
/// in the center of the selection rectangle. If the picker happens to be a
/// vtkAreaPicker it will operate on the entire selection rectangle.
/// When the 'p' key is hit the above pick operation occurs on a 1x1 rectangle.
/// In other respects it behaves the same as its parent class.
/// </para>
/// <para>
/// See also: vtkAreaPicker
/// </para>
/// </remarks>
public unsafe partial class vtkInteractorStyleRubberBandPick : vtkInteractorStyleTrackballCamera
{
    protected vtkInteractorStyleRubberBandPick(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkInteractorStyleRubberBandPick New() => new(vtkInteractorStyleRubberBandPick_New(), ownsReference: true);
    public new static vtkInteractorStyleRubberBandPick FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkInteractorStyleRubberBandPick TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkInteractorStyleRubberBandPick Register(vtkInteractorStyleRubberBandPick sourceObject)
    {
        var target = new vtkInteractorStyleRubberBandPick(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInteractorStyleRubberBandPick_New();
    #endregion
}
