// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkInteractorStyleJoystickCamera : vtkInteractorStyle
{
    protected vtkInteractorStyleJoystickCamera(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkInteractorStyleJoystickCamera New() => new(vtkInteractorStyleJoystickCamera_New(), ownsReference: true);
    public new static vtkInteractorStyleJoystickCamera WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkInteractorStyleJoystickCamera Register(vtkInteractorStyleJoystickCamera sourceObject)
    {
        var target = new vtkInteractorStyleJoystickCamera(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkInteractorStyleJoystickCamera_New();
    #endregion
}
