// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// A rubber band interactor for a 3D view
/// </summary>
/// <remarks>
///
/// vtkInteractorStyleRubberBand3D manages interaction in a 3D view.
/// The style also allows draws a rubber band using the left button.
/// All camera changes invoke StartInteractionEvent when the button
/// is pressed, InteractionEvent when the mouse (or wheel) is moved,
/// and EndInteractionEvent when the button is released.  The bindings
/// are as follows:
/// Left mouse - Select (invokes a SelectionChangedEvent).
/// Right mouse - Rotate.
/// Shift + right mouse - Zoom.
/// Middle mouse - Pan.
/// Scroll wheel - Zoom.
/// </remarks>
public unsafe partial class vtkInteractorStyleRubberBand3D : vtkInteractorStyleTrackballCamera
{
    static vtkInteractorStyleRubberBand3D() => NativeModuleLoader.EnsureLoaded("VtkSharp.Native.Rendering.dll");

    protected vtkInteractorStyleRubberBand3D(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkInteractorStyleRubberBand3D New() => new(vtkInteractorStyleRubberBand3D_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkInteractorStyleRubberBand3D FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkInteractorStyleRubberBand3D TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkInteractorStyleRubberBand3D Register(vtkInteractorStyleRubberBand3D sourceObject)
    {
        var target = new vtkInteractorStyleRubberBand3D(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport("VtkSharp.Native.Rendering.dll")]
    private static extern nint vtkInteractorStyleRubberBand3D_New();
    #endregion
}
