// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkMapper : vtkAbstractMapper3D
{
    protected vtkMapper(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkMapper WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkMapper Register(vtkMapper sourceObject)
    {
        var target = new vtkMapper(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }
}