// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// implements Win32 specific functions
/// required by vtkRenderWindowInteractor.
/// </summary>
/// <remarks>
///
/// By default the interactor installs a MessageProc callback which
/// intercepts windows' messages to the window and controls interactions by
/// routing them to the InteractoStyle classes.
/// MFC or BCB programs can prevent this and instead directly route any mouse/key
/// messages into the event bindings by setting InstallMessageProc to false.
/// This provides a minimal "Mapped" mode of interaction
/// </remarks>
public unsafe partial class vtkWin32RenderWindowInteractor : vtkRenderWindowInteractor
{
    protected vtkWin32RenderWindowInteractor(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Construct object so that light follows camera motion.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkWin32RenderWindowInteractor New() => new(vtkWin32RenderWindowInteractor_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkWin32RenderWindowInteractor FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkWin32RenderWindowInteractor TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkWin32RenderWindowInteractor Register(vtkWin32RenderWindowInteractor sourceObject)
    {
        var target = new vtkWin32RenderWindowInteractor(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Initialize the event handler
    /// </summary>
    public new void Initialize()
    {
        vtkWin32RenderWindowInteractor_Initialize(this.NativePointer);
    }

    /// <summary>
    /// By default the interactor installs a MessageProc callback which
    /// intercepts windows messages to the window and controls interactions.
    /// MFC or BCB programs can prevent this and instead directly route any mouse/key
    /// messages into the event bindings by setting InstallMessgeProc to false.
    /// </summary>
    public new void InstallMessageProcOff()
    {
        vtkWin32RenderWindowInteractor_InstallMessageProcOff(this.NativePointer);
    }

    /// <summary>
    /// By default the interactor installs a MessageProc callback which
    /// intercepts windows messages to the window and controls interactions.
    /// MFC or BCB programs can prevent this and instead directly route any mouse/key
    /// messages into the event bindings by setting InstallMessgeProc to false.
    /// </summary>
    public new void InstallMessageProcOn()
    {
        vtkWin32RenderWindowInteractor_InstallMessageProcOn(this.NativePointer);
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkWin32RenderWindowInteractor_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWin32RenderWindowInteractor_Initialize(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWin32RenderWindowInteractor_InstallMessageProcOff(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkWin32RenderWindowInteractor_InstallMessageProcOn(nint self);
    #endregion
}
