// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkLabelPlacementMapper.h>

VTKSHARP_API vtkLabelPlacementMapper* vtkLabelPlacementMapper_New() { return vtkLabelPlacementMapper::New(); }

VTKSHARP_API void vtkLabelPlacementMapper_SetIteratorType(vtkLabelPlacementMapper* self, int _arg) { self->SetIteratorType(_arg); }

VTKSHARP_API void vtkLabelPlacementMapper_SetMaximumLabelFraction(vtkLabelPlacementMapper* self, double _arg) { self->SetMaximumLabelFraction(_arg); }

VTKSHARP_API void vtkLabelPlacementMapper_SetUseDepthBuffer(vtkLabelPlacementMapper* self, bool _arg) { self->SetUseDepthBuffer(_arg); }

VTKSHARP_API void vtkLabelPlacementMapper_UseDepthBufferOff(vtkLabelPlacementMapper* self) { self->UseDepthBufferOff(); }
