// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkDEMReader.h>

VTKSHARP_API vtkDEMReader* vtkDEMReader_New() { return vtkDEMReader::New(); }

VTKSHARP_API void vtkDEMReader_SetFileName(vtkDEMReader* self, const char* _arg) { self->SetFileName(_arg); }
