using System.Text;
using VtkSharp.Generator.Core.Generation;

namespace VtkSharp.Generator.Tests;

public sealed class GeneratedOutputComparerTests
{
    [Fact]
    public void CompareDirectories_TreatsUtf8BomOnlyDifferenceAsEqual()
    {
        var expected = CreateDirectory();
        var actual = CreateDirectory();
        Directory.CreateDirectory(Path.Combine(expected, "vtkRenderingCore"));
        Directory.CreateDirectory(Path.Combine(actual, "vtkRenderingCore"));
        File.WriteAllText(
            Path.Combine(expected, "vtkRenderingCore", "vtkActor_gen.cs"),
            "// <auto-generated/>\n",
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
        File.WriteAllText(
            Path.Combine(actual, "vtkRenderingCore", "vtkActor_gen.cs"),
            "// <auto-generated/>\n",
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var differences = new GeneratedOutputComparer().CompareDirectories(expected, actual, "*_gen.cs");

        Assert.Empty(differences);
    }

    private static string CreateDirectory()
    {
        var directory = Path.Combine(Path.GetTempPath(), "VtkSharp.Generator.Tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        return directory;
    }
}
