// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkCamera.h>

VTKSHARP_API vtkCamera* vtkCamera_New() { return vtkCamera::New(); }

VTKSHARP_API void vtkCamera_Zoom(vtkCamera* self, double factor) { self->Zoom(factor); }
