// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkProp.h>

VTKSHARP_API void vtkProp_VisibilityOn(vtkProp* self) { self->VisibilityOn(); }
VTKSHARP_API void vtkProp_VisibilityOff(vtkProp* self) { self->VisibilityOff(); }
VTKSHARP_API void vtkProp_PickableOn(vtkProp* self) { self->PickableOn(); }
VTKSHARP_API void vtkProp_PickableOff(vtkProp* self) { self->PickableOff(); }
VTKSHARP_API void vtkProp_Pick(vtkProp* self) { self->Pick(); }
