// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkActorCollection.h>
#include <vtkAssemblyPath.h>
#include <vtkCamera.h>
#include <vtkCuller.h>
#include <vtkLight.h>
#include <vtkProp.h>
#include <vtkRenderWindow.h>
#include <vtkWindow.h>
#include <vtkRenderer.h>

VTKSHARP_API vtkRenderer* vtkRenderer_New() { return vtkRenderer::New(); }

VTKSHARP_API void vtkRenderer_AddActor(vtkRenderer* self, vtkProp* p) { self->AddActor(p); }

VTKSHARP_API void vtkRenderer_AddCuller(vtkRenderer* self, vtkCuller* _arg1) { self->AddCuller(_arg1); }

VTKSHARP_API void vtkRenderer_AddLight(vtkRenderer* self, vtkLight* _arg1) { self->AddLight(_arg1); }

VTKSHARP_API void vtkRenderer_AddVolume(vtkRenderer* self, vtkProp* p) { self->AddVolume(p); }

VTKSHARP_API void vtkRenderer_AutomaticLightCreationOff(vtkRenderer* self) { self->AutomaticLightCreationOff(); }

VTKSHARP_API void vtkRenderer_AutomaticLightCreationOn(vtkRenderer* self) { self->AutomaticLightCreationOn(); }

VTKSHARP_API void vtkRenderer_BackingStoreOff(vtkRenderer* self) { self->BackingStoreOff(); }

VTKSHARP_API void vtkRenderer_BackingStoreOn(vtkRenderer* self) { self->BackingStoreOn(); }

VTKSHARP_API void vtkRenderer_Clear(vtkRenderer* self) { self->Clear(); }

VTKSHARP_API void vtkRenderer_ClearLights(vtkRenderer* self) { self->ClearLights(); }

VTKSHARP_API void vtkRenderer_CreateLight(vtkRenderer* self) { self->CreateLight(); }

VTKSHARP_API void vtkRenderer_DrawOff(vtkRenderer* self) { self->DrawOff(); }

VTKSHARP_API void vtkRenderer_DrawOn(vtkRenderer* self) { self->DrawOn(); }

VTKSHARP_API void vtkRenderer_EraseOff(vtkRenderer* self) { self->EraseOff(); }

VTKSHARP_API void vtkRenderer_EraseOn(vtkRenderer* self) { self->EraseOn(); }

VTKSHARP_API vtkCamera* vtkRenderer_GetActiveCamera(vtkRenderer* self) { return self->GetActiveCamera(); }

VTKSHARP_API vtkActorCollection* vtkRenderer_GetActors(vtkRenderer* self) { return self->GetActors(); }

VTKSHARP_API vtkRenderWindow* vtkRenderer_GetRenderWindow(vtkRenderer* self) { return self->GetRenderWindow(); }

VTKSHARP_API double vtkRenderer_GetTiledAspectRatio(vtkRenderer* self) { return self->GetTiledAspectRatio(); }

VTKSHARP_API vtkWindow* vtkRenderer_GetVTKWindow(vtkRenderer* self) { return self->GetVTKWindow(); }

VTKSHARP_API double vtkRenderer_GetZ(vtkRenderer* self, int x, int y) { return self->GetZ(x, y); }

VTKSHARP_API void vtkRenderer_InteractiveOff(vtkRenderer* self) { self->InteractiveOff(); }

VTKSHARP_API void vtkRenderer_InteractiveOn(vtkRenderer* self) { self->InteractiveOn(); }

VTKSHARP_API void vtkRenderer_LightFollowCameraOff(vtkRenderer* self) { self->LightFollowCameraOff(); }

VTKSHARP_API void vtkRenderer_LightFollowCameraOn(vtkRenderer* self) { self->LightFollowCameraOn(); }

VTKSHARP_API vtkLight* vtkRenderer_MakeLight(vtkRenderer* self) { return self->MakeLight(); }

VTKSHARP_API vtkAssemblyPath* vtkRenderer_PickProp_double_double(vtkRenderer* self, double selectionX, double selectionY) { return self->PickProp(selectionX, selectionY); }

VTKSHARP_API vtkAssemblyPath* vtkRenderer_PickProp_double_double_double_double(vtkRenderer* self, double selectionX1, double selectionY1, double selectionX2, double selectionY2) { return self->PickProp(selectionX1, selectionY1, selectionX2, selectionY2); }

VTKSHARP_API void vtkRenderer_RemoveActor(vtkRenderer* self, vtkProp* p) { self->RemoveActor(p); }

VTKSHARP_API void vtkRenderer_RemoveAllLights(vtkRenderer* self) { self->RemoveAllLights(); }

VTKSHARP_API void vtkRenderer_RemoveCuller(vtkRenderer* self, vtkCuller* _arg1) { self->RemoveCuller(_arg1); }

VTKSHARP_API void vtkRenderer_RemoveLight(vtkRenderer* self, vtkLight* _arg1) { self->RemoveLight(_arg1); }

VTKSHARP_API void vtkRenderer_RemoveVolume(vtkRenderer* self, vtkProp* p) { self->RemoveVolume(p); }

VTKSHARP_API void vtkRenderer_Render(vtkRenderer* self) { self->Render(); }

VTKSHARP_API void vtkRenderer_ResetCamera_(vtkRenderer* self) { self->ResetCamera(); }

VTKSHARP_API void vtkRenderer_ResetCamera_doubleConstArray6(vtkRenderer* self, const double* bounds) { self->ResetCamera(bounds); }

VTKSHARP_API void vtkRenderer_ResetCamera_double_double_double_double_double_double(vtkRenderer* self, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax) { self->ResetCamera(xmin, xmax, ymin, ymax, zmin, zmax); }

VTKSHARP_API void vtkRenderer_ResetCameraClippingRange_(vtkRenderer* self) { self->ResetCameraClippingRange(); }

VTKSHARP_API void vtkRenderer_ResetCameraClippingRange_doubleConstArray6(vtkRenderer* self, const double* bounds) { self->ResetCameraClippingRange(bounds); }

VTKSHARP_API void vtkRenderer_ResetCameraClippingRange_double_double_double_double_double_double(vtkRenderer* self, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax) { self->ResetCameraClippingRange(xmin, xmax, ymin, ymax, zmin, zmax); }

VTKSHARP_API void vtkRenderer_SafeGetZOff(vtkRenderer* self) { self->SafeGetZOff(); }

VTKSHARP_API void vtkRenderer_SafeGetZOn(vtkRenderer* self) { self->SafeGetZOn(); }

VTKSHARP_API void vtkRenderer_SetActiveCamera(vtkRenderer* self, vtkCamera* _arg1) { self->SetActiveCamera(_arg1); }

VTKSHARP_API void vtkRenderer_SetAmbient_double_double_double(vtkRenderer* self, double _arg1, double _arg2, double _arg3) { self->SetAmbient(_arg1, _arg2, _arg3); }

VTKSHARP_API void vtkRenderer_SetAmbient_doubleConstArray3(vtkRenderer* self, const double* _arg) { self->SetAmbient(_arg); }

VTKSHARP_API void vtkRenderer_SetRenderWindow(vtkRenderer* self, vtkRenderWindow* _arg1) { self->SetRenderWindow(_arg1); }

VTKSHARP_API void vtkRenderer_TexturedBackgroundOff(vtkRenderer* self) { self->TexturedBackgroundOff(); }

VTKSHARP_API void vtkRenderer_TexturedBackgroundOn(vtkRenderer* self) { self->TexturedBackgroundOn(); }

VTKSHARP_API void vtkRenderer_TwoSidedLightingOff(vtkRenderer* self) { self->TwoSidedLightingOff(); }

VTKSHARP_API void vtkRenderer_TwoSidedLightingOn(vtkRenderer* self) { self->TwoSidedLightingOn(); }

VTKSHARP_API void vtkRenderer_UseImageBasedLightingOff(vtkRenderer* self) { self->UseImageBasedLightingOff(); }

VTKSHARP_API void vtkRenderer_UseImageBasedLightingOn(vtkRenderer* self) { self->UseImageBasedLightingOn(); }

VTKSHARP_API void vtkRenderer_UseShadowsOff(vtkRenderer* self) { self->UseShadowsOff(); }

VTKSHARP_API void vtkRenderer_UseShadowsOn(vtkRenderer* self) { self->UseShadowsOn(); }

VTKSHARP_API void vtkRenderer_ViewToWorld(vtkRenderer* self) { self->ViewToWorld(); }

VTKSHARP_API int vtkRenderer_VisibleActorCount(vtkRenderer* self) { return self->VisibleActorCount(); }

VTKSHARP_API int vtkRenderer_VisibleVolumeCount(vtkRenderer* self) { return self->VisibleVolumeCount(); }

VTKSHARP_API void vtkRenderer_WorldToView(vtkRenderer* self) { self->WorldToView(); }
