// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkProp.h>
#include <vtkRenderer.h>

VTKSHARP_API vtkRenderer* vtkRenderer_New() { return vtkRenderer::New(); }

VTKSHARP_API void vtkRenderer_AddActor(vtkRenderer* self, vtkProp* p) { self->AddActor(p); }
