# yaml-language-server: $schema=../schemas/vtksharp.generator.schema.json

vtk:
  version: "9.5"
  modulePrefix: vtk
  runtimeModules:
    - vtkCommonDataModel
    - vtkRenderingOpenGL2
    - vtkInteractionStyle
    - vtkRenderingUI

binding:
  namespace: VtkSharp
  nativeLibraryName: VtkSharp.Native
  manualBindingClasses:
    - vtkObjectBase
    - vtkObject

paths:
  whitelistDirectory: ../whitelist
  managedOutputDirectory: ../../bindings/VtkSharp
  nativeOutputDirectory: ../../bindings/VtkSharp.Native/src
  nativeProjectFile: ../../bindings/VtkSharp.Native/CMakeLists.txt
  nativeModulesFile: ../../bindings/VtkSharp.Native/vtksharp.modules.generated.cmake

generation:
  createManualExtensionFiles: false
  overwriteGeneratedFiles: true
  deleteOrphanGeneratedFiles: false
