// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Create an axis with tick marks and labels
/// </summary>
/// <remarks>
/// <para>
/// vtkAxisActor2D creates an axis with tick marks, labels, and/or a title,
/// depending on the particular instance variable settings. vtkAxisActor2D is
/// a 2D actor; that is, it is drawn on the overlay plane and is not
/// occluded by 3D geometry. To use this class, you typically specify two
/// points defining the start and end points of the line (x-y definition using
/// vtkCoordinate class), the number of labels, and the data range
/// (min,max).
/// </para>
/// <para>
/// ## Display
/// You can also control what parts of the axis are visible
/// including the line, the tick marks, the labels, and the title.
/// </para>
/// <para>
/// You can also specify the label format through the LabelTextProperty.
/// A legacy printf style format is still available.
/// </para>
/// <para>
/// This class decides what font size to use.
/// </para>
/// <para>
/// Set the text property/attributes of the title and the labels through the
/// vtkTextProperty objects associated to this actor.
/// </para>
/// <para>
/// Labels are drawn on the "right" side of the axis. The "right" side is
/// the side of the axis on the right as you move from Position to Position2.
/// The way the labels and title line up with the axis and tick marks depends on
/// whether the line is considered horizontal or vertical.
/// </para>
/// <para>
/// ## Number of ticks and their position
/// When `AdjustLabels` is on, vtkAxisActor2D also decides how to create reasonable
/// tick marks and labels. However, it does not follow `NumberOfLabels` target.
/// </para>
/// <para>
/// `SnapLabelsToGrid` is a similar mode and should be preferred. It uses `NumberOfLabels`
/// as a target to produce the list of labels. The number of labels and the range of values
/// may not match the number specified, but should be close.
/// </para>
/// <para>
/// When the computed `AdjustedRange` is larger than `Range`, some ticks may be
/// outside of `Range`. They are not displayed.
/// </para>
/// <para>
/// When `RulerMode` is on, `RulerDistance` is used to controls the ticks
/// position and thus their number. Otherwise `NumberOfLabels` is used as a
/// target for number of ticks.
/// </para>
/// <para>
/// ## Details
/// The vtkActor2D instance variables Position and Position2 are instances of
/// vtkCoordinate. Note that the Position2 is an absolute position in that
/// class (it was by default relative to Position in vtkActor2D).
/// </para>
/// <para>
/// What this means is that you can specify the axis in a variety of coordinate
/// systems. Also, the axis does not have to be either horizontal or vertical.
/// The tick marks are created so that they are perpendicular to the axis.
/// </para>
/// <para>
/// @sa
/// vtkCubeAxesActor2D can be used to create axes in world coordinate space.
/// </para>
/// <para>
/// @sa
/// vtkActor2D vtkTextMapper vtkPolyDataMapper2D vtkScalarBarActor
/// vtkCoordinate vtkTextProperty
/// </para>
/// </remarks>
public unsafe partial class vtkAxisActor2D : vtkActor2D
{
    protected vtkAxisActor2D(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Instantiate object.
    /// </summary>
    public new static vtkAxisActor2D New() => new(vtkAxisActor2D_New(), ownsReference: true);
    public new static vtkAxisActor2D FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkAxisActor2D TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkAxisActor2D Register(vtkAxisActor2D sourceObject)
    {
        var target = new vtkAxisActor2D(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkAxisActor2D_New();
    #endregion
}
