// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// annotate the render window with scale and distance information
/// </summary>
/// <remarks>
/// <para>
/// This class is used to annotate the render window. Its basic goal is to
/// provide an indication of the scale of the scene. Four axes surrounding the
/// render window indicate (in a variety of ways) the scale of what the camera
/// is viewing. An option also exists for displaying a scale legend.
/// </para>
/// <para>
/// The axes can be programmed either to display distance scales or
/// coordinate values. By default, the scales display a distance. However,
/// if you know that the view is down a scene axis, the scales can be programmed
/// to display coordinate values.
/// </para>
/// <para>
/// Warning:
/// Please be aware that the axes and scale values are subject to perspective
/// effects. The distances are computed in the focal plane of the camera.
/// When there are large view angles (i.e., perspective projection), the
/// computed distances may provide users the wrong sense of scale. These
/// effects are not present when parallel projection is enabled.
/// </para>
/// </remarks>
public unsafe partial class vtkLegendScaleActor : vtkProp
{
    protected vtkLegendScaleActor(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Instantiate the class.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkLegendScaleActor New() => new(vtkLegendScaleActor_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkLegendScaleActor FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkLegendScaleActor TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkLegendScaleActor Register(vtkLegendScaleActor sourceObject)
    {
        var target = new vtkLegendScaleActor(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Return the property used for the right axis
    /// which should be the same as the other ones if set using `SetAxesProperty`
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkProperty2D GetAxesProperty()
    {
        return vtkProperty2D.FromBorrowedPointer(vtkLegendScaleActor_GetAxesProperty(this.NativePointer));
    }

    /// <summary>
    /// These are methods to retrieve the vtkAxisActors used to represent
    /// the four axes that form this representation. Users may retrieve and
    /// then modify these axes to control their appearance.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkAxisActor2D GetBottomAxis()
    {
        return vtkAxisActor2D.FromBorrowedPointer(vtkLegendScaleActor_GetBottomAxis(this.NativePointer));
    }

    /// <summary>
    /// These are methods to retrieve the vtkAxisActors used to represent
    /// the four axes that form this representation. Users may retrieve and
    /// then modify these axes to control their appearance.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkAxisActor2D GetLeftAxis()
    {
        return vtkAxisActor2D.FromBorrowedPointer(vtkLegendScaleActor_GetLeftAxis(this.NativePointer));
    }

    /// <summary>
    /// These are methods to retrieve the vtkAxisActors used to represent
    /// the four axes that form this representation. Users may retrieve and
    /// then modify these axes to control their appearance.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkAxisActor2D GetRightAxis()
    {
        return vtkAxisActor2D.FromBorrowedPointer(vtkLegendScaleActor_GetRightAxis(this.NativePointer));
    }

    /// <summary>
    /// These are methods to retrieve the vtkAxisActors used to represent
    /// the four axes that form this representation. Users may retrieve and
    /// then modify these axes to control their appearance.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkAxisActor2D GetTopAxis()
    {
        return vtkAxisActor2D.FromBorrowedPointer(vtkLegendScaleActor_GetTopAxis(this.NativePointer));
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkLegendScaleActor_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkLegendScaleActor_GetAxesProperty(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkLegendScaleActor_GetBottomAxis(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkLegendScaleActor_GetLeftAxis(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkLegendScaleActor_GetRightAxis(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkLegendScaleActor_GetTopAxis(nint self);
    #endregion
}
