// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// read a digital elevation model (DEM) file
/// </summary>
/// <remarks>
/// vtkDEMReader reads digital elevation files and creates image data.
/// Digital elevation files are produced by the
/// &lt;A HREF="http://www.usgs.gov"&gt;US Geological Survey&lt;/A&gt;.
/// A complete description of the DEM file is located at the USGS site.
/// The reader reads the entire dem file and create a vtkImageData that
/// contains a single scalar component that is the elevation in meters.
/// The spacing is also expressed in meters. A number of get methods
/// provide access to fields on the header.
/// </remarks>
public unsafe partial class vtkDEMReader : vtkImageAlgorithm
{
    protected vtkDEMReader(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkDEMReader New() => new(vtkDEMReader_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkDEMReader FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkDEMReader TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkDEMReader Register(vtkDEMReader sourceObject)
    {
        var target = new vtkDEMReader(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Specify file name of Digital Elevation Model (DEM) file
    /// </summary>
    public new void SetFileName(string _arg)
    {
        #if NET8_0_OR_GREATER
        vtkDEMReader_SetFileName(this.NativePointer, _arg);
        #else
        vtkDEMReader_SetFileName(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg));
        #endif
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkDEMReader_New();

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkDEMReader_SetFileName(nint self, string _arg);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkDEMReader_SetFileName(nint self, byte[] _arg);
#endif
    #endregion
}
