// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// Writes images to files.
/// </summary>
/// <remarks>
/// vtkImageWriter writes images to files with any data type. The data type of
/// the file is the same scalar type as the input.  The dimensionality
/// determines whether the data will be written in one or multiple files.
/// This class is used as the superclass of most image writing classes
/// such as vtkBMPWriter etc. It supports streaming.
/// </remarks>
public unsafe partial class vtkImageWriter : vtkImageAlgorithm
{
    protected vtkImageWriter(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkImageWriter New() => new(vtkImageWriter_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkImageWriter FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkImageWriter TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkImageWriter Register(vtkImageWriter sourceObject)
    {
        var target = new vtkImageWriter(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new void DeleteFiles()
    {
        vtkImageWriter_DeleteFiles(this.NativePointer);
    }

    /// <summary>
    /// What dimension are the files to be written. Usually this is 2, or 3.
    /// If it is 2 and the input is a volume then the volume will be
    /// written as a series of 2d slices.
    /// </summary>
    public new int GetFileDimensionality()
    {
        return vtkImageWriter_GetFileDimensionality(this.NativePointer);
    }

    /// <summary>
    /// Specify file name for the image file. You should specify either
    /// a FileName or a FilePrefix. Use FilePrefix if the data is stored
    /// in multiple files.
    /// </summary>
    /// <remarks>
    /// The result is copied to a managed string. The caller does not release native memory for this return value.
    /// </remarks>
    public new string GetFileName()
    {
        return VtkString.FromUtf8Pointer(vtkImageWriter_GetFileName(this.NativePointer));
    }

    /// <summary>
    /// The std::format or printf style format used to build filename from FilePrefix and number.
    /// </summary>
    /// <remarks>
    /// The result is copied to a managed string. The caller does not release native memory for this return value.
    /// </remarks>
    public new string GetFilePattern()
    {
        return VtkString.FromUtf8Pointer(vtkImageWriter_GetFilePattern(this.NativePointer));
    }

    /// <summary>
    /// Specify file prefix for the image file(s).You should specify either
    /// a FileName or FilePrefix. Use FilePrefix if the data is stored
    /// in multiple files.
    /// </summary>
    /// <remarks>
    /// The result is copied to a managed string. The caller does not release native memory for this return value.
    /// </remarks>
    public new string GetFilePrefix()
    {
        return VtkString.FromUtf8Pointer(vtkImageWriter_GetFilePrefix(this.NativePointer));
    }

    /// <summary>
    /// What dimension are the files to be written. Usually this is 2, or 3.
    /// If it is 2 and the input is a volume then the volume will be
    /// written as a series of 2d slices.
    /// </summary>
    public new void SetFileDimensionality(int _arg)
    {
        vtkImageWriter_SetFileDimensionality(this.NativePointer, _arg);
    }

    /// <summary>
    /// Specify file name for the image file. You should specify either
    /// a FileName or a FilePrefix. Use FilePrefix if the data is stored
    /// in multiple files.
    /// </summary>
    public new void SetFileName(string _arg)
    {
        #if NET8_0_OR_GREATER
        vtkImageWriter_SetFileName(this.NativePointer, _arg);
        #else
        vtkImageWriter_SetFileName(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg));
        #endif
    }

    /// <summary>
    /// The std::format or printf style format used to build filename from FilePrefix and number.
    /// </summary>
    public new void SetFilePattern(string _arg1)
    {
        #if NET8_0_OR_GREATER
        vtkImageWriter_SetFilePattern(this.NativePointer, _arg1);
        #else
        vtkImageWriter_SetFilePattern(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg1));
        #endif
    }

    /// <summary>
    /// Specify file prefix for the image file(s).You should specify either
    /// a FileName or FilePrefix. Use FilePrefix if the data is stored
    /// in multiple files.
    /// </summary>
    public new void SetFilePrefix(string _arg)
    {
        #if NET8_0_OR_GREATER
        vtkImageWriter_SetFilePrefix(this.NativePointer, _arg);
        #else
        vtkImageWriter_SetFilePrefix(this.NativePointer, VtkString.ToNullTerminatedUtf8(_arg));
        #endif
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkImageWriter_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkImageWriter_DeleteFiles(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern int vtkImageWriter_GetFileDimensionality(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkImageWriter_GetFileName(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkImageWriter_GetFilePattern(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkImageWriter_GetFilePrefix(nint self);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkImageWriter_SetFileDimensionality(nint self, int _arg);

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkImageWriter_SetFileName(nint self, string _arg);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkImageWriter_SetFileName(nint self, byte[] _arg);
#endif

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkImageWriter_SetFilePattern(nint self, string _arg1);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkImageWriter_SetFilePattern(nint self, byte[] _arg1);
#endif

#if NET8_0_OR_GREATER
    [LibraryImport(InteropInfo.NativeLibraryName, StringMarshalling = StringMarshalling.Utf8)]
    private static partial void vtkImageWriter_SetFilePrefix(nint self, string _arg);
#else
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkImageWriter_SetFilePrefix(nint self, byte[] _arg);
#endif
    #endregion
}
