// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkJPEGWriter : vtkImageWriter
{
    protected vtkJPEGWriter(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkJPEGWriter New() => new(vtkJPEGWriter_New(), ownsReference: true);
    public new static vtkJPEGWriter WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkJPEGWriter Register(vtkJPEGWriter sourceObject)
    {
        var target = new vtkJPEGWriter(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkJPEGWriter_New();
    #endregion
}
