// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkGreedyTerrainDecimation.h>

VTKSHARP_API vtkGreedyTerrainDecimation* vtkGreedyTerrainDecimation_New() { return vtkGreedyTerrainDecimation::New(); }
