// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkCell : vtkObject
{
    protected vtkCell(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkCell WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkCell Register(vtkCell sourceObject)
    {
        var target = new vtkCell(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new vtkIdList GetPointIds()
    {
        return vtkIdList.WeakReference(vtkCell_GetPointIds(this.NativePointer));
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkCell_GetPointIds(nint self);
    #endregion
}
