// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// abstract class to specify cell behavior
/// </summary>
/// <remarks>
/// <para>
/// vtkCell is an abstract class that specifies the interfaces for data cells.
/// Data cells are simple topological elements like points, lines, polygons,
/// and tetrahedra of which visualization datasets are composed. In some
/// cases visualization datasets may explicitly represent cells (e.g.,
/// vtkPolyData, vtkUnstructuredGrid), and in some cases, the datasets are
/// implicitly composed of cells (e.g., vtkStructuredPoints).
/// </para>
/// <para>
/// Warning:
/// The \#define VTK_CELL_SIZE is a parameter used to construct cells and provide
/// a general guideline for controlling object execution. This parameter is
/// not a hard boundary: you can create cells with more points.
/// </para>
/// <para>
/// See also: vtkHexahedron vtkLine vtkPixel vtkPolyLine vtkPolyVertex
/// vtkPolygon vtkQuad vtkTetra vtkTriangle
/// vtkTriangleStrip vtkVertex vtkVoxel vtkWedge vtkPyramid
/// </para>
/// </remarks>
public unsafe partial class vtkCell : vtkObject
{
    protected vtkCell(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkCell FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkCell TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkCell Register(vtkCell sourceObject)
    {
        var target = new vtkCell(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Return the list of point ids defining the cell.
    /// </summary>
    /// <remarks>
    /// The C# wrapper borrows the native object without adding a reference. Dispose() does not release the borrowed reference. Use the wrapper only while the native object remains alive.
    /// </remarks>
    public new vtkIdList GetPointIds()
    {
        return vtkIdList.FromBorrowedPointer(vtkCell_GetPointIds(this.NativePointer));
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkCell_GetPointIds(nint self);
    #endregion
}
