// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// object to represent cell connectivity
/// </summary>
/// <remarks>
/// <para>
/// vtkCellArray stores dataset topologies as an explicit connectivity table
/// listing the point ids that make up each cell.
/// </para>
/// <para>
/// Internally, the connectivity table is represented as two arrays: Offsets and
/// Connectivity.
/// </para>
/// <para>
/// Offsets is an array of [numCells+1] values indicating the index in the
/// Connectivity array where each cell's points start. The last value is always
/// the length of the Connectivity array.
/// </para>
/// <para>
/// The Connectivity array stores the lists of point ids for each cell.
/// </para>
/// <para>
/// Thus, for a dataset consisting of 2 triangles, a quad, and a line, the
/// internal arrays will appear as follows:
/// </para>
/// <para>
/// ```
/// Topology:
/// ---------
/// Cell 0: Triangle | point ids: {0, 1, 2}
/// Cell 1: Triangle | point ids: {5, 7, 2}
/// Cell 2: Quad     | point ids: {3, 4, 6, 7}
/// Cell 3: Line     | point ids: {5, 8}
/// </para>
/// <para>
/// vtkCellArray (current):
/// -----------------------
/// Offsets:      {0, 3, 6, 10, 12}
/// Connectivity: {0, 1, 2, 5, 7, 2, 3, 4, 6, 7, 5, 8}
/// ```
/// </para>
/// <para>
/// While this class provides traversal methods (the legacy InitTraversal(),
/// GetNextCell() methods, and the newer method GetCellAtId()) these are in
/// general not thread-safe. Whenever possible it is preferable to use a
/// local thread-safe, vtkCellArrayIterator object, which can be obtained via:
/// </para>
/// <para>
/// ```
/// auto iter = vtk::TakeSmartPointer(cellArray-&gt;NewIterator());
/// for (iter-&gt;GoToFirstCell(); !iter-&gt;IsDoneWithTraversal(); iter-&gt;GoToNextCell())
/// {
/// // do work with iter
/// }
/// ```
/// (Note however that depending on the type and structure of internal
/// storage, a cell array iterator may be significantly slower than direct
/// traversal over the cell array due to extra data copying. Factors of 3-4X
/// are not uncommon. See vtkCellArrayIterator for more information. Also note
/// that an iterator may become invalid if the internal vtkCellArray storage
/// is modified.)
/// </para>
/// <para>
/// Other methods are also available for allocation and memory-related
/// management; insertion of new cells into the vtkCellArray; and limited
/// editing operations such as replacing one cell with a new cell of the
/// same size.
/// </para>
/// <para>
/// The internal arrays may store either 32- or 64-bit values, though most of
/// the API will prefer to use vtkIdType to refer to items in these
/// arrays. This enables significant memory savings when vtkIdType is 64-bit,
/// but 32 bits are sufficient to store all of the values in the connectivity
/// table. Using 64-bit storage with a 32-bit vtkIdType is permitted, but
/// values too large to fit in a 32-bit signed integer will be truncated when
/// accessed through the API. (The particular internal storage type has
/// implications on performance depending on vtkIdType. If the internal
/// storage is equivalent to vtkIdType, then methods that return pointers to
/// arrays of point ids can share the internal storage; otherwise a copy of
/// internal memory must be performed.)
/// </para>
/// <para>
/// Additionally, the internal arrays may be "fixed size", meaning that
/// each cell is required to have the same number of points. This allows
/// more compact storage and faster traversal, but is only appropriate for
/// datasets where all cells are the same type (e.g., all triangles, or all
/// quads, etc.). Fixed size storage with a cell size of N means that the
/// Connectivity array will have N entries per cell, and the Offsets array
/// will have values {0, N, 2N, 3N, ... }.
/// </para>
/// <para>
/// Methods for managing the storage type are:
/// </para>
/// <para>
/// - `bool IsStorage64Bit()`
/// - `bool IsStorage32Bit()`
/// - `bool IsStorageFixedSize64Bit()`
/// - `bool IsStorageFixedSize32Bit()`
/// - `bool IsStorageFixedSize() // Either 32- or 64-bit fixed size`
/// - `bool IsStorageGeneric()`
/// - `bool IsStorageShareable() // Can pointers to internal storage be shared`
/// - `void Use64BitStorage()`
/// - `void Use32BitStorage()`
/// - `void UseDefaultStorage() // Depends on vtkIdType`
/// - `void UseFixedSize64BitStorage(vtkIdType cellSize)`
/// - `void UseFixedSize32BitStorage(vtkIdType cellSize)`
/// - `void UseFixedSizeStorage(vtkIdType cellSize) // Depends on vtkIdType`
/// - `bool CanConvertTo32BitStorage()`
/// - `bool CanConvertTo64BitStorage()`
/// - `bool CanConvertToDefaultStorage() // Depends on vtkIdType`
/// - `bool CanConvertToFixedSize32BitStorage()`
/// - `bool CanConvertToFixedSize64BitStorage()`
/// - `bool CanConvertToFixedSizeStorage() // Depends on vtkIdType`
/// - `bool CanConvertToStorageType(int type) // Int64, Int32, FixedSizeInt64, FixedSizeInt32`
/// - `bool ConvertTo64BitStorage()`
/// - `bool ConvertTo32BitStorage()`
/// - `bool ConvertToDefaultStorage() // Depends on vtkIdType`
/// - `bool ConvertToFixedSize64BitStorage()`
/// - `bool ConvertToFixedSize32BitStorage()`
/// - `bool ConvertToFixedSizeStorage() // Depends on vtkIdType`
/// - `bool ConvertToSmallestStorage() // Depends on current values in arrays`
/// - `bool ConvertToStorageType(int type) // Int64, Int32, FixedSizeInt64, FixedSizeInt32`
/// </para>
/// <para>
/// There is an additional mode of storage to allow any kind of vtkDataArray derived
/// types. The Generic storage mode allows separate array types for offsets and connectivity.
/// There is no method to explicitly use generic storage mode.
/// vtkCellArray will automatically switch over to using generic
/// storage when any overload of vtkCellArray::SetData is invoked with array types that
/// are NOT in vtkArrayDispatch::ConnectivityArrays.
/// </para>
/// <para>
/// @sa vtkAbstractCellArray vtkStructuredCellArray vtkCellTypes vtkCellLinks
/// </para>
/// </remarks>
public unsafe partial class vtkCellArray : vtkAbstractCellArray
{
    protected vtkCellArray(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Standard methods for instantiation, type information, and
    /// printing.
    /// </summary>
    public new static vtkCellArray New() => new(vtkCellArray_New(), ownsReference: true);
    public new static vtkCellArray FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkCellArray TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkCellArray Register(vtkCellArray sourceObject)
    {
        var target = new vtkCellArray(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <summary>
    /// Used in conjunction with InsertNextCell(npts) to add another point
    /// to the list of cells.
    /// </summary>
    public new void InsertCellPoint(long id)
    {
        vtkCellArray_InsertCellPoint(this.NativePointer, id);
    }

    /// <summary>
    /// Create cells by specifying a count of total points to be inserted, and
    /// then adding points one at a time using method InsertCellPoint(). If you
    /// don't know the count initially, use the method UpdateCellCount() to
    /// complete the cell. Return the cell id of the cell.
    /// </summary>
    public new long InsertNextCell(int npts)
    {
        return vtkCellArray_InsertNextCell_int(this.NativePointer, npts);
    }

    /// <summary>
    /// Insert a cell object. Return the cell id of the cell.
    /// </summary>
    public new long InsertNextCell(vtkCell cell)
    {
        return vtkCellArray_InsertNextCell_vtkCellPtr(this.NativePointer, cell.NativePointer);
    }

    /// <summary>
    /// Create a cell by specifying a list of point ids. Return the cell id of
    /// the cell.
    /// </summary>
    public new long InsertNextCell(vtkIdList pts)
    {
        return vtkCellArray_InsertNextCell_vtkIdListPtr(this.NativePointer, pts.NativePointer);
    }

    /// <summary>
    /// Create a cell by specifying the number of points and an array of point
    /// id's.  Return the cell id of the cell.
    /// </summary>
    public new long InsertNextCell(long npts, ReadOnlySpan<long> pts)
    {
        fixed (long* ptsPtr = pts)
        {
            return vtkCellArray_InsertNextCell_vtkIdType_vtkIdTypeConstPtr(this.NativePointer, npts, ptsPtr);
        }
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkCellArray_New();

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkCellArray_InsertCellPoint(nint self, long id);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkCellArray_InsertNextCell_int(nint self, int npts);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkCellArray_InsertNextCell_vtkCellPtr(nint self, nint cell);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkCellArray_InsertNextCell_vtkIdListPtr(nint self, nint pts);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern long vtkCellArray_InsertNextCell_vtkIdType_vtkIdTypeConstPtr(nint self, long npts, long* pts);
    #endregion
}
