// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkDataObject : vtkObject
{
    protected vtkDataObject(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkDataObject New() => new(vtkDataObject_New(), ownsReference: true);
    public new static vtkDataObject WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkDataObject Register(vtkDataObject sourceObject)
    {
        var target = new vtkDataObject(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkDataObject_New();
    #endregion
}
