// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkDataSet : vtkDataObject
{
    protected vtkDataSet(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkDataSet WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkDataSet Register(vtkDataSet sourceObject)
    {
        var target = new vtkDataSet(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    public new vtkPointData GetPointData()
    {
        return vtkPointData.WeakReference(vtkDataSet_GetPointData(this.NativePointer));
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkDataSet_GetPointData(nint self);
    #endregion
}
