// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkImageData : vtkCartesianGrid
{
    protected vtkImageData(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkImageData New() => new(vtkImageData_New(), ownsReference: true);
    public new static vtkImageData WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkImageData Register(vtkImageData sourceObject)
    {
        var target = new vtkImageData(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkImageData_New();
    #endregion
}
