// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// represent and manipulate point attribute data
/// </summary>
/// <remarks>
/// <para>
/// vtkPointData is a class that is used to represent and manipulate
/// point attribute data (e.g., scalars, vectors, normals, texture
/// coordinates, etc.) Most of the functionality is handled by
/// vtkDataSetAttributes.
/// </para>
/// <para>
/// By default, `GhostTypesToSkip` is set to `DUPLICATEPOINT | HIDDENPOINT`.
/// See `vtkDataSetAttributes` for the definition of those constants.
/// </para>
/// </remarks>
public unsafe partial class vtkPointData : vtkDataSetAttributes
{
    protected vtkPointData(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkPointData New() => new(vtkPointData_New(), ownsReference: true);
    public new static vtkPointData FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkPointData TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkPointData Register(vtkPointData sourceObject)
    {
        var target = new vtkPointData(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkPointData_New();
    #endregion
}
