// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkTriangle : vtkCell
{
    protected vtkTriangle(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkTriangle New() => new(vtkTriangle_New(), ownsReference: true);
    internal new static vtkTriangle FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    internal new static vtkTriangle TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkTriangle Register(vtkTriangle sourceObject)
    {
        var target = new vtkTriangle(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkTriangle_New();
    #endregion
}
