// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// a cell that represents a triangle
/// </summary>
/// <remarks>
/// vtkTriangle is a concrete implementation of vtkCell to represent a triangle
/// located in 3-space.
/// </remarks>
public unsafe partial class vtkTriangle : vtkCell
{
    protected vtkTriangle(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkTriangle New() => new(vtkTriangle_New(), ownsReference: true);
    public new static vtkTriangle FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkTriangle TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkTriangle Register(vtkTriangle sourceObject)
    {
        var target = new vtkTriangle(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkTriangle_New();
    #endregion
}
