// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// dataset represents arbitrary combinations of
/// all possible cell types
/// </summary>
/// <remarks>
/// vtkUnstructuredGrid is a data object that is a concrete implementation of
/// vtkDataSet. vtkUnstructuredGrid represents any combinations of any cell
/// types. This includes 0D (e.g., points), 1D (e.g., lines, polylines), 2D
/// (e.g., triangles, polygons), and 3D (e.g., hexahedron, tetrahedron,
/// polyhedron, etc.). vtkUnstructuredGrid provides random access to cells, as
/// well as topological information (such as lists of cells using each point).
/// </remarks>
public unsafe partial class vtkUnstructuredGrid : vtkUnstructuredGridBase
{
    static vtkUnstructuredGrid() => NativeModuleLoader.EnsureLoaded("VtkSharp.Native.CommonDataModel.dll");

    protected vtkUnstructuredGrid(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    /// <summary>
    /// Standard instantiation method.
    /// </summary>
    /// <remarks>
    /// The C# wrapper owns a native reference. Call Dispose() when finished to release that reference.
    /// </remarks>
    public new static vtkUnstructuredGrid New() => new(vtkUnstructuredGrid_New(), ownsReference: true);
    /// <summary>
    /// Wraps a live native object without adding a reference or taking ownership.
    /// </summary>
    /// <remarks>
    /// Dispose() does not release the borrowed reference. Keep the native object alive while using this wrapper.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type.
    /// </param>
    /// <returns>
    /// A wrapper that does not own a native reference.
    /// </returns>
    public new static vtkUnstructuredGrid FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    /// <summary>
    /// Takes ownership of one existing native reference without incrementing the reference count.
    /// </summary>
    /// <remarks>
    /// The caller transfers responsibility for releasing this reference to the wrapper; do not release it separately or transfer it twice. Call Dispose() when finished.
    /// </remarks>
    /// <param name="nativePointer">
    /// A non-null pointer to a live native object of the corresponding VTK type, with one owned reference to transfer.
    /// </param>
    /// <returns>
    /// A wrapper that releases the transferred reference on Dispose().
    /// </returns>
    public new static vtkUnstructuredGrid TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    /// <summary>
    /// Creates another wrapper for the same native object and increments its reference count by one.
    /// </summary>
    /// <remarks>
    /// The source wrapper's ownership is unchanged. Call Dispose() on the returned wrapper to release the additional reference. This does not copy the native object.
    /// </remarks>
    /// <param name="sourceObject">
    /// A wrapper for a native object that is still alive.
    /// </param>
    /// <returns>
    /// A wrapper that owns the additional native reference independently of the source wrapper.
    /// </returns>
    public new static vtkUnstructuredGrid Register(vtkUnstructuredGrid sourceObject)
    {
        var target = new vtkUnstructuredGrid(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport("VtkSharp.Native.CommonDataModel.dll")]
    private static extern nint vtkUnstructuredGrid_New();
    #endregion
}
