// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkTransformPolyDataFilter.h>

VTKSHARP_API vtkTransformPolyDataFilter* vtkTransformPolyDataFilter_New() { return vtkTransformPolyDataFilter::New(); }
