// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkPlane.h>

VTKSHARP_API vtkPlane* vtkPlane_New() { return vtkPlane::New(); }

VTKSHARP_API void vtkPlane_SetNormal(vtkPlane* self, double x, double y, double z) { self->SetNormal(x, y, z); }

VTKSHARP_API void vtkPlane_SetOrigin(vtkPlane* self, double x, double y, double z) { self->SetOrigin(x, y, z); }
