// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkAbstractPicker.h>

VTKSHARP_API void vtkAbstractPicker_GetPickPosition(vtkAbstractPicker* self, double* data) { self->GetPickPosition(data); }
