// <auto-generated/>
#include "vtksharp_api.h"
#include <vtkDiscretizableColorTransferFunction.h>

VTKSHARP_API vtkDiscretizableColorTransferFunction* vtkDiscretizableColorTransferFunction_New() { return vtkDiscretizableColorTransferFunction::New(); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_Build(vtkDiscretizableColorTransferFunction* self) { self->Build(); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_DiscretizeOff(vtkDiscretizableColorTransferFunction* self) { self->DiscretizeOff(); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_DiscretizeOn(vtkDiscretizableColorTransferFunction* self) { self->DiscretizeOn(); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_GetColor(vtkDiscretizableColorTransferFunction* self, double v, double* rgb) { self->GetColor(v, rgb); }

VTKSHARP_API vtkTypeBool vtkDiscretizableColorTransferFunction_GetDiscretize(vtkDiscretizableColorTransferFunction* self) { return self->GetDiscretize(); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_GetIndexedColor(vtkDiscretizableColorTransferFunction* self, vtkIdType i, double* rgba) { self->GetIndexedColor(i, rgba); }

VTKSHARP_API vtkIdType vtkDiscretizableColorTransferFunction_GetNumberOfAvailableColors(vtkDiscretizableColorTransferFunction* self) { return self->GetNumberOfAvailableColors(); }

VTKSHARP_API unsigned int vtkDiscretizableColorTransferFunction_GetNumberOfIndexedColors(vtkDiscretizableColorTransferFunction* self) { return self->GetNumberOfIndexedColors(); }

VTKSHARP_API vtkIdType vtkDiscretizableColorTransferFunction_GetNumberOfValues(vtkDiscretizableColorTransferFunction* self) { return self->GetNumberOfValues(); }

VTKSHARP_API double vtkDiscretizableColorTransferFunction_GetOpacity(vtkDiscretizableColorTransferFunction* self, double v) { return self->GetOpacity(v); }

VTKSHARP_API vtkTypeBool vtkDiscretizableColorTransferFunction_GetUseLogScale(vtkDiscretizableColorTransferFunction* self) { return self->GetUseLogScale(); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetAlpha(vtkDiscretizableColorTransferFunction* self, double alpha) { self->SetAlpha(alpha); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetDiscretize(vtkDiscretizableColorTransferFunction* self, vtkTypeBool _arg) { self->SetDiscretize(_arg); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetIndexedColor(vtkDiscretizableColorTransferFunction* self, unsigned int index, double r, double g, double b, double a) { self->SetIndexedColor(index, r, g, b, a); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetIndexedColorRGB(vtkDiscretizableColorTransferFunction* self, unsigned int index, const double* rgb) { self->SetIndexedColorRGB(index, rgb); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetIndexedColorRGBA(vtkDiscretizableColorTransferFunction* self, unsigned int index, const double* rgba) { self->SetIndexedColorRGBA(index, rgba); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetNanColor_doubleConstArray3(vtkDiscretizableColorTransferFunction* self, const double* rgb) { self->SetNanColor(rgb); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetNanColor_double_double_double(vtkDiscretizableColorTransferFunction* self, double r, double g, double b) { self->SetNanColor(r, g, b); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetNanOpacity(vtkDiscretizableColorTransferFunction* self, double a) { self->SetNanOpacity(a); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetNumberOfIndexedColors(vtkDiscretizableColorTransferFunction* self, unsigned int count) { self->SetNumberOfIndexedColors(count); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetNumberOfValues(vtkDiscretizableColorTransferFunction* self, vtkIdType _arg) { self->SetNumberOfValues(_arg); }

VTKSHARP_API void vtkDiscretizableColorTransferFunction_SetUseLogScale(vtkDiscretizableColorTransferFunction* self, vtkTypeBool useLogScale) { self->SetUseLogScale(useLogScale); }

VTKSHARP_API vtkTypeBool vtkDiscretizableColorTransferFunction_UsingLogScale(vtkDiscretizableColorTransferFunction* self) { return self->UsingLogScale(); }
