// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// superclass for all geometric transformations
/// </summary>
/// <remarks>
/// <para>
/// vtkAbstractTransform is the superclass for all VTK geometric
/// transformations.  The VTK transform hierarchy is split into two
/// major branches: warp transformations and homogeneous (including linear)
/// transformations.  The latter can be represented in terms of a 4x4
/// transformation matrix, the former cannot.
/// &lt;p&gt;Transformations can be pipelined through two mechanisms:
/// &lt;p&gt;1) GetInverse() returns the pipelined
/// inverse of a transformation i.e. if you modify the original transform,
/// any transform previously returned by the GetInverse() method will
/// automatically update itself according to the change.
/// &lt;p&gt;2) You can do pipelined concatenation of transformations through
/// the vtkGeneralTransform class, the vtkPerspectiveTransform class,
/// or the vtkTransform class.
/// </para>
/// <para>
/// See also: vtkGeneralTransform vtkWarpTransform vtkHomogeneousTransform
/// vtkLinearTransform vtkIdentityTransform
/// vtkTransformFilter vtkTransformFilter vtkImageReslice
/// vtkImplicitFunction
/// </para>
/// </remarks>
public unsafe partial class vtkAbstractTransform : vtkObject
{
    protected vtkAbstractTransform(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkAbstractTransform FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkAbstractTransform TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkAbstractTransform Register(vtkAbstractTransform sourceObject)
    {
        var target = new vtkAbstractTransform(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    /// <param name="point">
    /// Buffer length: 3 elements.
    /// </param>
    internal new double* TransformPoint_Internal(ReadOnlySpan<double> point)
    {
        fixed (double* pointPtr = point)
        {
            return vtkAbstractTransform_TransformPoint_doubleConstArray3(this.NativePointer, pointPtr);
        }
    }

    /// <summary>
    /// Apply the transformation to a double-precision coordinate.
    /// Use this if you are programming in Python or Java.
    /// </summary>
    internal new double* TransformPoint_Internal(double x, double y, double z)
    {
        return vtkAbstractTransform_TransformPoint_double_double_double(this.NativePointer, x, y, z);
    }

    /// <summary>
    /// Apply the transformation to a double-precision coordinate.
    /// You can use the same array to store both the input and output point.
    /// </summary>
    /// <param name="in">
    /// Buffer length: 3 elements.
    /// </param>
    /// <param name="out">
    /// Buffer length: 3 elements.
    /// </param>
    public new void TransformPoint(ReadOnlySpan<double> @in, Span<double> @out)
    {
        fixed (double* inPtr = @in)
        {
            fixed (double* outPtr = @out)
            {
                vtkAbstractTransform_TransformPoint_doubleConstArray3_doubleArray3(this.NativePointer, inPtr, outPtr);
            }
        }
    }

    /// <summary>
    /// Apply the transformation to a coordinate.  You can use the same
    /// array to store both the input and output point.
    /// </summary>
    /// <param name="in">
    /// Buffer length: 3 elements.
    /// </param>
    /// <param name="out">
    /// Buffer length: 3 elements.
    /// </param>
    public new void TransformPoint(ReadOnlySpan<float> @in, Span<float> @out)
    {
        fixed (float* inPtr = @in)
        {
            fixed (float* outPtr = @out)
            {
                vtkAbstractTransform_TransformPoint_floatConstArray3_floatArray3(this.NativePointer, inPtr, outPtr);
            }
        }
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double* vtkAbstractTransform_TransformPoint_doubleConstArray3(nint self, double* point);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern double* vtkAbstractTransform_TransformPoint_double_double_double(nint self, double x, double y, double z);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkAbstractTransform_TransformPoint_doubleConstArray3_doubleArray3(nint self, double* @in, double* @out);

    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern void vtkAbstractTransform_TransformPoint_floatConstArray3_floatArray3(nint self, float* @in, float* @out);
    #endregion
}
