// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkAbstractTransform : vtkObject
{
    protected vtkAbstractTransform(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkAbstractTransform WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkAbstractTransform Register(vtkAbstractTransform sourceObject)
    {
        var target = new vtkAbstractTransform(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
