// <auto-generated/>
// Documentation derived from VTK headers. See VTK-LICENSE.txt.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

/// <summary>
/// abstract superclass for linear transformations
/// </summary>
/// <remarks>
/// <para>
/// vtkLinearTransform provides a generic interface for linear
/// (affine or 12 degree-of-freedom) geometric transformations.
/// </para>
/// <para>
/// @warning
/// Portions of this class (i.e., when transforming arrays of points and/or
/// associated attributes such as normals and vectors) has been threaded with
/// vtkSMPTools. Using TBB or other non-sequential type (set in the CMake
/// variable VTK_SMP_IMPLEMENTATION_TYPE) may improve performance
/// significantly.
/// </para>
/// <para>
/// @sa
/// vtkTransform vtkIdentityTransform
/// </para>
/// </remarks>
public unsafe partial class vtkLinearTransform : vtkHomogeneousTransform
{
    protected vtkLinearTransform(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkLinearTransform FromBorrowedPointer(nint nativePointer) => new(nativePointer, ownsReference: false);
    public new static vtkLinearTransform TakeReference(nint nativePointer) => new(nativePointer, ownsReference: true);

    public new static vtkLinearTransform Register(vtkLinearTransform sourceObject)
    {
        var target = new vtkLinearTransform(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    #endregion
}
