// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace VtkSharp;

public unsafe partial class vtkTransform : vtkLinearTransform
{
    protected vtkTransform(nint nativePointer, bool ownsReference) : base(nativePointer, ownsReference) { }
    public new static vtkTransform New() => new(vtkTransform_New(), ownsReference: true);
    public new static vtkTransform WeakReference(nint nativePointer) => new(nativePointer, ownsReference: false);

    public new static vtkTransform Register(vtkTransform sourceObject)
    {
        var target = new vtkTransform(sourceObject.NativePointer, true);
        target.Register();
        return target;
    }

    #region Interop
    [DllImport(InteropInfo.NativeLibraryName)]
    private static extern nint vtkTransform_New();
    #endregion
}
